server:
  name: bbs
  version: 1.0.0
  mode: ${SERVICE_MODE:dev}
  http:
    network: tcp
    host: ${HTTP_HOST:0.0.0.0}
    port: ${HTTP_PORT:8001}
    timeout: 5s
data:
  redis:
    addr: ${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:"123456"}
    dial_timeout: 5s
    db: 0
    read_timeout: 5s
    write_timeout: 5s
    pool_size: 150
    min_idle_conns: 30
    pool_timeout: 2s
    conn_max_idle_time: 600s
    conn_max_life_time: 1800s
  consul:
    address: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}
    datacenter: dc1
    token: ${CONSUL_ACL_APP_TOKEN:token}
    dial_timeout: 5s
trace:
  enable_otel: false # 是否采集并上报链路数据
  endpoint: ${OTEL_ENDPOINT:127.0.0.1:4317}  # OTel Collector 地址
  insecure: true
  sampler: 1  # 100% 采样率
