server:
  name: bbs
  version: 1.0.0
  mode: ${SERVICE_MODE:dev}
  http:
    host: ${HTTP_HOST:0.0.0.0}
    port: ${HTTP_PORT:8001}
    timeout: 5s
data:
  consul:
    address: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}
    datacenter: dc1
    token: ${CONSUL_ACL_APP_TOKEN:token}
    dial_timeout: 5s
trace:
  enable_otel: true # 是否采集并上报链路数据
  endpoint: ${OTEL_ENDPOINT:127.0.0.1:4317}  # OTel Collector 地址
  insecure: true
  sampler: 1  # 100% 采样率
