syntax = "proto3";
package kratos.api.bootstrap;

option go_package = "im/internal/conf/bootstrap;bootstrap";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Config config = 2;
  Log log = 3;
}

message Server {
  string name = 1;
  string version = 2;
  string mode = 3;
}

message Config {
  Consul consul = 1;
  message Consul {
    string address = 1;
    string token = 2;
    string path = 3;
    google.protobuf.Duration timeout = 4;
  }
}

message Log {
  string level = 1; // debug, info, warn, error, fatal, panic
  string file = 2;
}
