syntax = "proto3";

package common.api.notify.v1;

option go_package = "common/api/common/v1;v1";

enum NotificationStatus {
  NotificationStatusNormal = 0; // 正常
  NotificationStatusCancel = 1; // 取消
}

enum NotificationChannel {
  NotificationChannelEmail = 0; // 邮件
  NotificationChannelSMS = 1; // 短信
  NotificationChannelWebSite = 2; // 网站
}

enum NotificationType {
  NotificationTypeNormal = 0; // 普通
  NotificationTypeSystem = 1; // 系统

  NotificationTypeUserRegisterVerifyCode = 99; // 用户注册验证码
  NotificationTypeUserRegister = 100; // 用户注册
  NotificationTypeUserFollow = 101; // 用户关注
  NotificationTypeUserBlock = 102; // 用户拉黑

  NotificationTypeArticlePublish = 200; // 文章发布
  NotificationTypeArticleLike = 201; // 文章点赞
  NotificationTypeArticleThank = 202; // 文章感谢
  NotificationTypeArticleCollect = 203; // 文章收藏
  NotificationTypeArticleWatch = 204; // 文章关注
  NotificationTypeArticleReward = 205; // 文章打赏
  NotificationTypeArticleAt = 206; // 文章@
  NotificationTypeArticleVote = 207; // 文章投票
  NotificationTypeArticleLottery = 208;// 文章抽奖
  NotificationTypeArticleLotteryWinner = 209; // 抽奖中奖

  NotificationTypeCommentPublish = 300; // 评论发布
  NotificationTypeCommentLike = 301; // 评论点赞
  NotificationTypeCommentThank = 302; // 评论感谢
  NotificationTypeCommentCollect = 303; // 评论收藏
  NotificationTypeCommentAt = 304; // 评论@

}
