syntax = "proto3";

package common.api.notify.v1;

option go_package = "common/gen/notify/v1;v1";

enum NotificationStatus {
  NOTIFICATION_STATUS_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_STATUS_NORMAL      = 1; // 正常
  NOTIFICATION_STATUS_CANCEL      = 2; // 取消
}

enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_CHANNEL_EMAIL       = 1; // 邮件
  NOTIFICATION_CHANNEL_SMS         = 2; // 短信
  NOTIFICATION_CHANNEL_WEBSITE     = 3; // 网站
}

enum NotificationType {
  NOTIFICATION_TYPE_UNSPECIFIED = 0; // 未指定

  // 通用类型
  NOTIFICATION_TYPE_NORMAL = 1; // 普通
  NOTIFICATION_TYPE_SYSTEM = 2; // 系统

  // 用户相关（100 段）
  NOTIFICATION_TYPE_USER_REGISTER_VERIFY_CODE = 99;  // 用户注册验证码
  NOTIFICATION_TYPE_USER_REGISTER             = 100; // 用户注册
  NOTIFICATION_TYPE_USER_FOLLOW               = 101; // 用户关注
  NOTIFICATION_TYPE_USER_BLOCK                = 102; // 用户拉黑

  // 文章相关（200 段）
  NOTIFICATION_TYPE_ARTICLE_PUBLISH        = 200; // 文章发布
  NOTIFICATION_TYPE_ARTICLE_LIKE           = 201; // 文章点赞
  NOTIFICATION_TYPE_ARTICLE_THANK          = 202; // 文章感谢
  NOTIFICATION_TYPE_ARTICLE_COLLECT        = 203; // 文章收藏
  NOTIFICATION_TYPE_ARTICLE_WATCH          = 204; // 文章关注
  NOTIFICATION_TYPE_ARTICLE_REWARD         = 205; // 文章打赏
  NOTIFICATION_TYPE_ARTICLE_AT             = 206; // 文章 @
  NOTIFICATION_TYPE_ARTICLE_VOTE           = 207; // 文章投票
  NOTIFICATION_TYPE_ARTICLE_LOTTERY        = 208; // 文章抽奖
  NOTIFICATION_TYPE_ARTICLE_LOTTERY_WINNER = 209; // 抽奖中奖

  // 评论相关（300 段）
  NOTIFICATION_TYPE_COMMENT_PUBLISH = 300; // 评论发布
  NOTIFICATION_TYPE_COMMENT_LIKE    = 301; // 评论点赞
  NOTIFICATION_TYPE_COMMENT_THANK   = 302; // 评论感谢
  NOTIFICATION_TYPE_COMMENT_COLLECT = 303; // 评论收藏
  NOTIFICATION_TYPE_COMMENT_AT      = 304; // 评论 @
}
