syntax = "proto3";

package common.api.user.v1;

import "google/api/annotations.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";
import "common/v1/common.proto";

option go_package = "common/api/user/v1;v1";

// Notification_Template 服务
service NotifyNotificationTemplateService {

  // 查询通知模板
  rpc Page (NotificationTemplatePageRequest) returns (NotificationTemplatePageReply) {
    option (google.api.http) = {
      post: "/v1/notificationTemplate/page"
      body: "*"
    };
  }

  // 添加通知模板
  rpc Add (NotificationTemplateAddRequest) returns (NotificationTemplateAddReply) {
    option (google.api.http) = {
      post: "/v1/notificationTemplate/add"
      body: "*"
    };
  }

  // 更新通知模板
  rpc Update (NotificationTemplateUpdateRequest) returns (NotificationTemplateUpdateReply) {
    option (google.api.http) = {
      post: "/v1/notificationTemplate/update"
      body: "*"
    };
  }

}

// 实体定义

message NotificationTemplate {
  // 创建时间
  google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  google.protobuf.Timestamp updated_at = 1001;

  // 主键
  int64 id = 3;
  // 通知类型
  int32 notification_type = 5;
  // 通知渠道
  int32 channel = 6;
  // 模板标题
  string title = 4;
  // 模板内容
  string content = 7;
  // 处理器链（有序执行）
  repeated string processors = 8;
  // 是否启用
  bool enable = 9;
}

// 查询参数定义

message NotificationTemplateQueryParams {
  // 主键
  repeated int64 ids = 2;
  // 通知类型
  optional int32 notification_type = 5;
  // 通知渠道
  optional int32 channel = 6;
  // 模板内容
  optional string content = 7;
  // 处理器链（有序执行）
  repeated string processors = 8;
  // 是否启用
  optional bool enable = 9;
}

// 请求/响应结构定义

message NotificationTemplatePageRequest {
  // 分页参数
  common.v1.PageRequest page = 1;
  // 查询参数
  NotificationTemplateQueryParams query = 2;
}
message NotificationTemplatePageReply {
  // 分页信息
  common.v1.PageReply page = 1;
  // 通知元数据信息
  repeated NotificationTemplate rows = 2;
}

message NotificationTemplateAddRequest {
  // 模板信息
  NotificationTemplate notification_template = 2;
}
message NotificationTemplateAddReply {
  NotificationTemplate notification_template = 1;
}

message NotificationTemplateUpdateRequest {
  // 主键
  int64 ids = 2;
  // 通知类型
  optional int32 notification_type = 5;
  // 通知渠道
  optional int32 channel = 6;
  // 模板内容
  optional string content = 7;
  // 处理器链（有序执行）
  repeated string processors = 8;
  // 是否启用
  optional bool enable = 9;
}
message NotificationTemplateUpdateReply {
  NotificationTemplate notification_template = 1;
}