syntax = "proto3";

package common.api.app.bbs.v1.content;

option go_package = "common/proto/gen/bbs/v1/content/enum;enum";

// 文章发布状态。
enum ArticlePublishStatus {
  ARTICLE_PUBLISH_STATUS_UNSPECIFIED = 0; // 未指定
  ARTICLE_PUBLISH_STATUS_DRAFT = 1; // 草稿
  ARTICLE_PUBLISH_STATUS_PUBLISHED = 2; // 已发布
  ARTICLE_PUBLISH_STATUS_ARCHIVED = 3; // 已归档
}

// 文章可见范围。
enum ArticleVisibility {
  ARTICLE_VISIBILITY_UNSPECIFIED = 0; // 未指定
  ARTICLE_VISIBILITY_PUBLIC = 1; // 公开
  ARTICLE_VISIBILITY_PRIVATE = 2; // 私有
}

// 内容管理限制。
enum ContentRestriction {
  CONTENT_RESTRICTION_UNSPECIFIED = 0; // 未指定
  CONTENT_RESTRICTION_NONE = 1; // 无管理限制
  CONTENT_RESTRICTION_HIDDEN = 2; // 管理隐藏
  CONTENT_RESTRICTION_LOCKED = 3; // 管理锁定
}

// 文章类型。
enum ArticleType {
  ARTICLE_TYPE_UNSPECIFIED = 0; // 未指定
  ARTICLE_TYPE_NORMAL = 1; // 普通文章
  ARTICLE_TYPE_QA = 2; // 问答文章
}

// 文章排序方式。
enum ArticleOrder {
  ARTICLE_ORDER_UNSPECIFIED = 0; // 未指定
  ARTICLE_ORDER_NEWEST = 1; // 最新优先
  ARTICLE_ORDER_HOTTEST = 2; // 热度优先
}
