server:
  name: monolith
  version: 1.0.0
  mode: ${SERVICE_MODE:dev}
http:
  network: tcp
  host: ${MONOLITH_HTTP_HOST:0.0.0.0}
  port: ${MONOLITH_HTTP_PORT:8000}
  timeout: 5s
grpc:
  network: tcp
  host: ${MONOLITH_GRPC_HOST:0.0.0.0}
  port: ${MONOLITH_GRPC_PORT:9000}
  timeout: 5s
consul:
  address: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}
  datacenter: dc1
  token: ${CONSUL_ACL_APP_TOKEN:token}
  dial_timeout: 5s
modules:
  user:
    enabled: true
    bootstrap: ../user/configs/bootstrap.yaml
    config: ../user/configs/config.yaml
  bbs:
    enabled: true
    bootstrap: ../bbs/configs/bootstrap.yaml
    config: ../bbs/configs/config.yaml
  content:
    enabled: true
    bootstrap: ../content/configs/bootstrap.yaml
    config: ../content/configs/config.yaml
  economy:
    enabled: true
    bootstrap: ../economy/configs/bootstrap.yaml
    config: ../economy/configs/config.yaml
  game_town:
    enabled: true
    bootstrap: ../game_town/configs/bootstrap.yaml
    config: ../game_town/configs/config.yaml
  im:
    enabled: true
    bootstrap: ../im/configs/bootstrap.yaml
    config: ../im/configs/config.yaml
  notify:
    enabled: true
    bootstrap: ../notify/configs/bootstrap.yaml
    config: ../notify/configs/config.yaml
  platform:
    enabled: true
    bootstrap: ../platform/configs/bootstrap.yaml
    config: ../platform/configs/config.yaml
  push_hub:
    enabled: true
    bootstrap: ../push_hub/configs/bootstrap.yaml
    config: ../push_hub/configs/config.yaml
  push_node:
    enabled: true
    bootstrap: ../push_node/configs/bootstrap.yaml
    config: ../push_node/configs/config.yaml
  scheduler:
    enabled: true
    bootstrap: ../scheduler/configs/bootstrap.yaml
    config: ../scheduler/configs/config.yaml
