server:
  name: infra-service
  version: 1.0.0
  mode: dev
  register_address: ${REGISTER_ADDRESS:127.0.0.1} # 服务注册地址
  http:
    host: 0.0.0.0
    port: 8001
    timeout: 5s
  grpc:
    host: 0.0.0.0
    port: 9001
    timeout: 5s
  oss:
    provider: "qiniu"
    minio:

    qiniu:
      access_key: "L8l6DGiYXzmx0IVT0GpIxI-Mj8LqfoIKF6iAnrWa"
      secret_key: "qY6ohp-qZEtd20NZN94o7TScg3IeEGSZe-ZRsVXW"
      bucket: "bass-test"
      timeout: 300s
      size_min: 0  # 单位 MB
      size_max: 20 # 单位 MB
      callback_url: "https://treble.sxisa.com/api/user/v1/oss/qiniu/uploadCallback"
data:
  database:
    driver: "postgres"
    source: "postgresql://bass:123456@127.0.0.1:5432/bass?sslmode=disable" # postgresql://<user>:<pass>@<host>/<database>
    merge: true # 是否同步表到数据库
  redis:
    addr: 127.0.0.1:16379
    password: "123456"
    dial_timeout: 5s
    db: 0
    read_timeout: 5s
    write_timeout: 5s
    pool_size: 150
    min_idle_conns: 30
    pool_timeout: 2s
    conn_max_idle_time: 600s
    conn_max_life_time: 1800s
  rabbitmq:
    url: "amqp://root:123456@127.0.0.1:5672/admin_vhost"
    heartbeat: 10s            # 心跳，秒
    dial_timeout: 5s          # 连接超时，秒
    prefetch_count: 10        # Qos，未确认消息最大数量
    prefetch_global: false    # Qos 是否全局
    delivery_mode: 2          # 消息持久化 1: transient, 2: persistent
    auto_ack: false           # 是否自动确认消息
  consul:
    address: "127.0.0.1:8500"
    datacenter: "dc1"
    token: "token"
    dial_timeout: "5s"
trace:
  enable_otel: false # 是否采集上报到 otel
  endpoint: "127.0.0.1:4317"  # OTel Collector 地址
  insecure: true
  sampler: 1  # 100% 采样率
