/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.api;

import com.bass.bbs.ApiException;
import com.bass.bbs.model.CreateDomainReq;
import com.bass.bbs.model.CreateDomainResp;
import com.bass.bbs.model.ListDomainsReq;
import com.bass.bbs.model.ListDomainsResp;
import com.bass.bbs.model.UpdateDomainReq;
import com.bass.bbs.model.UpdateDomainResp;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for DomainService
 */
@Disabled
public class DomainServiceTest {

    private final DomainService api = new DomainService();

    
    /**
     * 
     *
     * 查询领域列表。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void callListTest() throws ApiException {
        ListDomainsReq listDomainsReq = null;
        
        DomainService.APIcallListRequest request = DomainService.APIcallListRequest.newBuilder()
          .listDomainsReq(listDomainsReq)
          .build();
        ListDomainsResp response = 
        api.callList(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 创建领域。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        CreateDomainReq createDomainReq = null;
        
        DomainService.APIcreateRequest request = DomainService.APIcreateRequest.newBuilder()
          .createDomainReq(createDomainReq)
          .build();
        CreateDomainResp response = 
        api.create(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 更新领域。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateTest() throws ApiException {
        UpdateDomainReq updateDomainReq = null;
        
        DomainService.APIupdateRequest request = DomainService.APIupdateRequest.newBuilder()
          .updateDomainReq(updateDomainReq)
          .build();
        UpdateDomainResp response = 
        api.update(request);

        // TODO: test validations
    }
    
}
