/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.api;

import com.bass.bbs.ApiException;
import com.bass.bbs.model.BlockRelationReq;
import com.bass.bbs.model.FollowRelationReq;
import com.bass.bbs.model.GetStatusRelationReq;
import com.bass.bbs.model.GetStatusRelationResp;
import com.bass.bbs.model.ListBlockedRelationsReq;
import com.bass.bbs.model.ListBlockedRelationsResp;
import com.bass.bbs.model.ListFollowersRelationsReq;
import com.bass.bbs.model.ListFollowersRelationsResp;
import com.bass.bbs.model.ListFollowingRelationsReq;
import com.bass.bbs.model.ListFollowingRelationsResp;
import com.bass.bbs.model.UnblockRelationReq;
import com.bass.bbs.model.UnfollowRelationReq;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for RelationService
 */
@Disabled
public class RelationServiceTest {

    private final RelationService api = new RelationService();

    
    /**
     * 
     *
     * 当前账号拉黑目标账号。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void blockTest() throws ApiException {
        BlockRelationReq blockRelationReq = null;
        
        RelationService.APIblockRequest request = RelationService.APIblockRequest.newBuilder()
          .blockRelationReq(blockRelationReq)
          .build();
        Object response = 
        api.block(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 当前账号关注目标账号。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void followTest() throws ApiException {
        FollowRelationReq followRelationReq = null;
        
        RelationService.APIfollowRequest request = RelationService.APIfollowRequest.newBuilder()
          .followRelationReq(followRelationReq)
          .build();
        Object response = 
        api.follow(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 查询当前账号与目标账号之间的关系。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws ApiException {
        GetStatusRelationReq getStatusRelationReq = null;
        
        RelationService.APIgetStatusRequest request = RelationService.APIgetStatusRequest.newBuilder()
          .getStatusRelationReq(getStatusRelationReq)
          .build();
        GetStatusRelationResp response = 
        api.getStatus(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 分页查询当前账号拉黑的账号列表。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listBlockedTest() throws ApiException {
        ListBlockedRelationsReq listBlockedRelationsReq = null;
        
        RelationService.APIlistBlockedRequest request = RelationService.APIlistBlockedRequest.newBuilder()
          .listBlockedRelationsReq(listBlockedRelationsReq)
          .build();
        ListBlockedRelationsResp response = 
        api.listBlocked(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 分页查询当前账号的粉丝账号列表。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFollowersTest() throws ApiException {
        ListFollowersRelationsReq listFollowersRelationsReq = null;
        
        RelationService.APIlistFollowersRequest request = RelationService.APIlistFollowersRequest.newBuilder()
          .listFollowersRelationsReq(listFollowersRelationsReq)
          .build();
        ListFollowersRelationsResp response = 
        api.listFollowers(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 分页查询当前账号关注的账号列表。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listFollowingTest() throws ApiException {
        ListFollowingRelationsReq listFollowingRelationsReq = null;
        
        RelationService.APIlistFollowingRequest request = RelationService.APIlistFollowingRequest.newBuilder()
          .listFollowingRelationsReq(listFollowingRelationsReq)
          .build();
        ListFollowingRelationsResp response = 
        api.listFollowing(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 当前账号取消拉黑目标账号。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unblockTest() throws ApiException {
        UnblockRelationReq unblockRelationReq = null;
        
        RelationService.APIunblockRequest request = RelationService.APIunblockRequest.newBuilder()
          .unblockRelationReq(unblockRelationReq)
          .build();
        Object response = 
        api.unblock(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 当前账号取消关注目标账号。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void unfollowTest() throws ApiException {
        UnfollowRelationReq unfollowRelationReq = null;
        
        RelationService.APIunfollowRequest request = RelationService.APIunfollowRequest.newBuilder()
          .unfollowRelationReq(unfollowRelationReq)
          .build();
        Object response = 
        api.unfollow(request);

        // TODO: test validations
    }
    
}
