syntax = "proto3";

package common.api.app.bbs.v1.content;

import "bbs/v1/content/model.proto";
import "common/common.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/content;content";

// 内容板块接口。
service DomainService {
  // 分页查询内容板块列表。
  rpc List(ListDomains.Request) returns (ListDomains.Reply) {
    option (google.api.http) = {
      post: "/v1/content/domain/list"
      body: "*"
    };
  }
}

// 分页查询内容板块列表。
message ListDomains {
  message Request {
    // 分页参数。
    common.PageRequest page = 1;
    // 查询条件。
    DomainQuery query = 2;
  }
  message Reply {
    // 分页结果。
    common.PageReply page = 1;
    // 内容板块列表。
    repeated Domain rows = 2;
  }
}
