syntax = "proto3";

package common.api.app.bbs.v1.content;

import "bbs/v1/content/model.proto";
import "common/common.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/content;content";

// 标签接口。
service TagService {
  // 分页查询标签列表。
  rpc List(ListTags.Request) returns (ListTags.Reply) {
    option (google.api.http) = {
      post: "/v1/content/tag/list"
      body: "*"
    };
  }
}

// 分页查询标签列表。
message ListTags {
  message Request {
    // 分页参数。
    common.PageRequest page = 1;
    // 查询条件。
    TagQuery query = 2;
  }
  message Reply {
    // 分页结果。
    common.PageReply page = 1;
    // 标签列表。
    repeated Tag rows = 2;
  }
}
