// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: im/v1/chat_group.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IMChatGroupService_Create_FullMethodName = "/common.api.im.v1.IMChatGroupService/Create"
	IMChatGroupService_Page_FullMethodName   = "/common.api.im.v1.IMChatGroupService/Page"
)

// IMChatGroupServiceClient is the client API for IMChatGroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatGroup 服务
type IMChatGroupServiceClient interface {
	// 创建群组
	Create(ctx context.Context, in *ChatGroupCreateRequest, opts ...grpc.CallOption) (*ChatGroupCreateReply, error)
	// 查询群组列表
	Page(ctx context.Context, in *ChatGroupPageRequest, opts ...grpc.CallOption) (*ChatGroupPageReply, error)
}

type iMChatGroupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIMChatGroupServiceClient(cc grpc.ClientConnInterface) IMChatGroupServiceClient {
	return &iMChatGroupServiceClient{cc}
}

func (c *iMChatGroupServiceClient) Create(ctx context.Context, in *ChatGroupCreateRequest, opts ...grpc.CallOption) (*ChatGroupCreateReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatGroupCreateReply)
	err := c.cc.Invoke(ctx, IMChatGroupService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iMChatGroupServiceClient) Page(ctx context.Context, in *ChatGroupPageRequest, opts ...grpc.CallOption) (*ChatGroupPageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChatGroupPageReply)
	err := c.cc.Invoke(ctx, IMChatGroupService_Page_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IMChatGroupServiceServer is the server API for IMChatGroupService service.
// All implementations must embed UnimplementedIMChatGroupServiceServer
// for forward compatibility.
//
// ChatGroup 服务
type IMChatGroupServiceServer interface {
	// 创建群组
	Create(context.Context, *ChatGroupCreateRequest) (*ChatGroupCreateReply, error)
	// 查询群组列表
	Page(context.Context, *ChatGroupPageRequest) (*ChatGroupPageReply, error)
	mustEmbedUnimplementedIMChatGroupServiceServer()
}

// UnimplementedIMChatGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIMChatGroupServiceServer struct{}

func (UnimplementedIMChatGroupServiceServer) Create(context.Context, *ChatGroupCreateRequest) (*ChatGroupCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedIMChatGroupServiceServer) Page(context.Context, *ChatGroupPageRequest) (*ChatGroupPageReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Page not implemented")
}
func (UnimplementedIMChatGroupServiceServer) mustEmbedUnimplementedIMChatGroupServiceServer() {}
func (UnimplementedIMChatGroupServiceServer) testEmbeddedByValue()                            {}

// UnsafeIMChatGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IMChatGroupServiceServer will
// result in compilation errors.
type UnsafeIMChatGroupServiceServer interface {
	mustEmbedUnimplementedIMChatGroupServiceServer()
}

func RegisterIMChatGroupServiceServer(s grpc.ServiceRegistrar, srv IMChatGroupServiceServer) {
	// If the following call pancis, it indicates UnimplementedIMChatGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IMChatGroupService_ServiceDesc, srv)
}

func _IMChatGroupService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMChatGroupServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMChatGroupService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMChatGroupServiceServer).Create(ctx, req.(*ChatGroupCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IMChatGroupService_Page_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatGroupPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IMChatGroupServiceServer).Page(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IMChatGroupService_Page_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IMChatGroupServiceServer).Page(ctx, req.(*ChatGroupPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IMChatGroupService_ServiceDesc is the grpc.ServiceDesc for IMChatGroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IMChatGroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "common.api.im.v1.IMChatGroupService",
	HandlerType: (*IMChatGroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _IMChatGroupService_Create_Handler,
		},
		{
			MethodName: "Page",
			Handler:    _IMChatGroupService_Page_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im/v1/chat_group.proto",
}
