syntax = "proto3";
package kratos.api.conf;

option go_package = "notify/internal/conf/conf;conf";

import "google/protobuf/duration.proto";

message Bootstrap {
  Server server = 1;
  Data data = 2;
  Registry registry = 3;
  Trace trace = 4;
  Email email = 5;
  SmsConfig sms = 6;
}

message Server {
  string name = 1;
  string version = 2;
  string mode = 3;
  message HTTP {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  message GRPC {
    string network = 1;
    string addr = 2;
    google.protobuf.Duration timeout = 3;
  }
  HTTP http = 4;
  GRPC grpc = 5;
}

message Data {
  message Database {
    string driver = 1;
    string source = 2;
    bool merge = 3;
  }
  message Redis {
    string addr = 1;
    string password = 2;
    int32 db = 3;
    google.protobuf.Duration dial_timeout = 4;
    google.protobuf.Duration read_timeout = 5;
    google.protobuf.Duration write_timeout = 6;
    int32 pool_size = 7;
    int32 min_idle_conns = 8;
    google.protobuf.Duration pool_timeout = 9;
    google.protobuf.Duration conn_max_idle_time = 10;
    google.protobuf.Duration conn_max_life_time = 11;
  }
  message RabbitMQ {
    string url = 1;
    google.protobuf.Duration heartbeat = 2;
    google.protobuf.Duration dial_timeout = 3;
    int32 prefetch_count = 4;
    bool prefetch_global = 5;
    int32 delivery_mode = 6;
    bool auto_ack = 7;
  }
  Database database = 1;
  Redis redis = 2;
  RabbitMQ rabbitmq = 3;
}

message Registry {
  message Etcd {
    repeated string endpoints = 1;
    string username = 2;
    string password = 3;
    google.protobuf.Duration timeout = 4;
    google.protobuf.Duration auto_sync_interval = 5;
    google.protobuf.Duration dial_keep_alive_time = 6;
    google.protobuf.Duration dial_keep_alive_timeout = 7;
    bool permit_without_leader = 8;
  }
  Etcd etcd = 1;
}

message Trace {
  bool enable_otel = 1;
  string endpoint = 2;
  bool insecure = 3;
  double sampler = 4;
}

message Email {
  bool enable = 1;          // 是否启用邮件
  string smtp_host = 2;     // SMTP 服务器地址
  uint32 smtp_port = 3;     // SMTP 端口
  string username = 4;      // SMTP 用户名
  string password = 5;      // SMTP 密码
  string from = 6;          // 发件人邮箱
}

message SmsConfig {
  string provider = 1;
  message TencentSmsConfig {
    string secret_id = 1;
    string secret_key = 2;
    string diyu = 3;
    string sms_sdk_app_id = 4;
    string sign_name = 5;
    string template_id = 6;
  }
  TencentSmsConfig tencent = 2;
}

