/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the GetCurrentLocationResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCurrentLocationResp{}

// GetCurrentLocationResp struct for GetCurrentLocationResp
type GetCurrentLocationResp struct {
	Location *RespLocation `json:"location,omitempty"`
}

// NewGetCurrentLocationResp instantiates a new GetCurrentLocationResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCurrentLocationResp() *GetCurrentLocationResp {
	this := GetCurrentLocationResp{}
	return &this
}

// NewGetCurrentLocationRespWithDefaults instantiates a new GetCurrentLocationResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCurrentLocationRespWithDefaults() *GetCurrentLocationResp {
	this := GetCurrentLocationResp{}
	return &this
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *GetCurrentLocationResp) GetLocation() RespLocation {
	if o == nil || IsNil(o.Location) {
		var ret RespLocation
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCurrentLocationResp) GetLocationOk() (*RespLocation, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *GetCurrentLocationResp) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given RespLocation and assigns it to the Location field.
func (o *GetCurrentLocationResp) SetLocation(v RespLocation) {
	o.Location = &v
}

func (o GetCurrentLocationResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCurrentLocationResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	return toSerialize, nil
}

type NullableGetCurrentLocationResp struct {
	value *GetCurrentLocationResp
	isSet bool
}

func (v NullableGetCurrentLocationResp) Get() *GetCurrentLocationResp {
	return v.value
}

func (v *NullableGetCurrentLocationResp) Set(val *GetCurrentLocationResp) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCurrentLocationResp) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCurrentLocationResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCurrentLocationResp(val *GetCurrentLocationResp) *NullableGetCurrentLocationResp {
	return &NullableGetCurrentLocationResp{value: val, isSet: true}
}

func (v NullableGetCurrentLocationResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCurrentLocationResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


