/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the ListDomainsResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListDomainsResp{}

// ListDomainsResp struct for ListDomainsResp
type ListDomainsResp struct {
	Page *PageResp `json:"page,omitempty"`
	Rows []RespDomain `json:"rows,omitempty"`
}

// NewListDomainsResp instantiates a new ListDomainsResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListDomainsResp() *ListDomainsResp {
	this := ListDomainsResp{}
	return &this
}

// NewListDomainsRespWithDefaults instantiates a new ListDomainsResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListDomainsRespWithDefaults() *ListDomainsResp {
	this := ListDomainsResp{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ListDomainsResp) GetPage() PageResp {
	if o == nil || IsNil(o.Page) {
		var ret PageResp
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDomainsResp) GetPageOk() (*PageResp, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ListDomainsResp) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given PageResp and assigns it to the Page field.
func (o *ListDomainsResp) SetPage(v PageResp) {
	o.Page = &v
}

// GetRows returns the Rows field value if set, zero value otherwise.
func (o *ListDomainsResp) GetRows() []RespDomain {
	if o == nil || IsNil(o.Rows) {
		var ret []RespDomain
		return ret
	}
	return o.Rows
}

// GetRowsOk returns a tuple with the Rows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListDomainsResp) GetRowsOk() ([]RespDomain, bool) {
	if o == nil || IsNil(o.Rows) {
		return nil, false
	}
	return o.Rows, true
}

// HasRows returns a boolean if a field has been set.
func (o *ListDomainsResp) HasRows() bool {
	if o != nil && !IsNil(o.Rows) {
		return true
	}

	return false
}

// SetRows gets a reference to the given []RespDomain and assigns it to the Rows field.
func (o *ListDomainsResp) SetRows(v []RespDomain) {
	o.Rows = v
}

func (o ListDomainsResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListDomainsResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.Rows) {
		toSerialize["rows"] = o.Rows
	}
	return toSerialize, nil
}

type NullableListDomainsResp struct {
	value *ListDomainsResp
	isSet bool
}

func (v NullableListDomainsResp) Get() *ListDomainsResp {
	return v.value
}

func (v *NullableListDomainsResp) Set(val *ListDomainsResp) {
	v.value = val
	v.isSet = true
}

func (v NullableListDomainsResp) IsSet() bool {
	return v.isSet
}

func (v *NullableListDomainsResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListDomainsResp(val *ListDomainsResp) *NullableListDomainsResp {
	return &NullableListDomainsResp{value: val, isSet: true}
}

func (v NullableListDomainsResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListDomainsResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


