/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the CreateCharacterReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCharacterReq{}

// CreateCharacterReq struct for CreateCharacterReq
type CreateCharacterReq struct {
	Name *string `json:"name,omitempty"`
}

// NewCreateCharacterReq instantiates a new CreateCharacterReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCharacterReq() *CreateCharacterReq {
	this := CreateCharacterReq{}
	return &this
}

// NewCreateCharacterReqWithDefaults instantiates a new CreateCharacterReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCharacterReqWithDefaults() *CreateCharacterReq {
	this := CreateCharacterReq{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateCharacterReq) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCharacterReq) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateCharacterReq) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateCharacterReq) SetName(v string) {
	o.Name = &v
}

func (o CreateCharacterReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCharacterReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableCreateCharacterReq struct {
	value *CreateCharacterReq
	isSet bool
}

func (v NullableCreateCharacterReq) Get() *CreateCharacterReq {
	return v.value
}

func (v *NullableCreateCharacterReq) Set(val *CreateCharacterReq) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCharacterReq) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCharacterReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCharacterReq(val *CreateCharacterReq) *NullableCreateCharacterReq {
	return &NullableCreateCharacterReq{value: val, isSet: true}
}

func (v NullableCreateCharacterReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCharacterReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


