/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListArticleTagsReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListArticleTagsReq{}

// ListArticleTagsReq struct for ListArticleTagsReq
type ListArticleTagsReq struct {
	ArticleId string `json:"article_id"`
}

type _ListArticleTagsReq ListArticleTagsReq

// NewListArticleTagsReq instantiates a new ListArticleTagsReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListArticleTagsReq(articleId string) *ListArticleTagsReq {
	this := ListArticleTagsReq{}
	this.ArticleId = articleId
	return &this
}

// NewListArticleTagsReqWithDefaults instantiates a new ListArticleTagsReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListArticleTagsReqWithDefaults() *ListArticleTagsReq {
	this := ListArticleTagsReq{}
	return &this
}

// GetArticleId returns the ArticleId field value
func (o *ListArticleTagsReq) GetArticleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleId
}

// GetArticleIdOk returns a tuple with the ArticleId field value
// and a boolean to check if the value has been set.
func (o *ListArticleTagsReq) GetArticleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleId, true
}

// SetArticleId sets field value
func (o *ListArticleTagsReq) SetArticleId(v string) {
	o.ArticleId = v
}

func (o ListArticleTagsReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListArticleTagsReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["article_id"] = o.ArticleId
	return toSerialize, nil
}

func (o *ListArticleTagsReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListArticleTagsReq := _ListArticleTagsReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListArticleTagsReq)

	if err != nil {
		return err
	}

	*o = ListArticleTagsReq(varListArticleTagsReq)

	return err
}

type NullableListArticleTagsReq struct {
	value *ListArticleTagsReq
	isSet bool
}

func (v NullableListArticleTagsReq) Get() *ListArticleTagsReq {
	return v.value
}

func (v *NullableListArticleTagsReq) Set(val *ListArticleTagsReq) {
	v.value = val
	v.isSet = true
}

func (v NullableListArticleTagsReq) IsSet() bool {
	return v.isSet
}

func (v *NullableListArticleTagsReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListArticleTagsReq(val *ListArticleTagsReq) *NullableListArticleTagsReq {
	return &NullableListArticleTagsReq{value: val, isSet: true}
}

func (v NullableListArticleTagsReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListArticleTagsReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


