// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"common/pkg/util/jwt"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"im/internal/conf"
	"im/internal/data"
	"im/internal/data/client"
	"im/internal/server"
	"im/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, helper *log.Helper) (*kratos.App, func(), error) {
	genClient, cleanup, err := client.NewDataBaseClient(helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	consulClient, cleanup2, err := data.NewConsulClient(helper, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	redisClient, cleanup3, err := data.NewRedisClient(helper, bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rabbitMQClient, cleanup4, err := data.NewRabbitMQClient(helper, bootstrap)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseService := service.NewBaseService(bootstrap, helper, genClient, consulClient, redisClient, rabbitMQClient)
	systemService := service.NewSystemService(baseService)
	v := service.ProvideServices(systemService)
	tokenCache := jwt.NewTokenCache(helper, redisClient)
	grpcServer := server.NewGRPCServer(bootstrap, logger, v, tokenCache)
	httpServer := server.NewHTTPServer(bootstrap, logger, v, tokenCache)
	app := newApp(logger, grpcServer, httpServer, consulClient)
	return app, func() {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
