syntax = "proto3";
package kratos.api.platform.config;

import "common/config.proto";
import "google/protobuf/duration.proto";

option go_package = "platform/internal/config;config";

message Bootstrap {
  common.api.app.common.Server server = 1;
  common.api.app.common.HTTP http = 2;
  common.api.app.common.GRPC grpc = 3;
  common.api.app.common.Consul consul = 4;
  common.api.app.common.Database database = 5;
  common.api.app.common.Redis redis = 6;
  common.api.app.common.Nats nats = 7;
  common.api.app.common.Trace trace = 8;
  common.api.app.common.Observability observability = 9;
  Platform platform = 21;
}

message Platform {
  IpData ip_data = 1;
  Oss oss = 2;

  message IpData {
    bool enable = 1;
    string ipv4_xdb_path = 2;
    string ipv6_xdb_path = 3;
    string cache_policy = 4;
    string ipv4_source_url = 5;
    string ipv6_source_url = 6;
  }

  message Oss {
    string provider = 1;
    Qiniu qiniu = 10;
    Minio minio = 11;

    message Qiniu {
      string access_key = 1;
      string secret_key = 2;
      string bucket = 3;
      google.protobuf.Duration timeout = 4;
      int64 size_min = 5;
      int64 size_max = 6;
      string callback_url = 7;
      bool increment_audit = 8;
      string increment_audit_callback_url = 9;
    }

    message Minio {
      string endpoint = 1;
      string access_key = 2;
      string secret_key = 3;
      string bucket = 4;
      bool use_ssl = 5;
      google.protobuf.Duration timeout = 6;
    }
  }
}
