// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"common/pkg/util"
	"connector/internal/biz"
	"connector/internal/conf"
	"connector/internal/data"
	"connector/internal/server"
	"connector/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, helper *log.Helper) (*kratos.App, func(), error) {
	baseService := service.NewBaseService(bootstrap, helper)
	eventPool, cleanup, err := util.NewEventPool(helper)
	if err != nil {
		return nil, nil, err
	}
	baseDomain := biz.NewBaseDomain(bootstrap, helper, eventPool)
	baseRepo := data.NewBaseRepo(bootstrap, helper)
	systemService := service.NewSystemService(baseService, baseDomain, baseRepo)
	sessionDomain := biz.NewSessionDomain(baseDomain, eventPool)
	callbackService := service.NewCallbackService(baseService, sessionDomain)
	v := service.ProvideServices(systemService, callbackService)
	grpcServer := server.NewGRPCServer(bootstrap, logger, v)
	websocketService := service.NewWebsocketService(baseService, sessionDomain, eventPool)
	httpServer := server.NewHTTPServer(bootstrap, logger, v, websocketService)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
