// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"common/pkg/util"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"user/internal/biz"
	"user/internal/conf"
	"user/internal/data"
	"user/internal/data/base"
	"user/internal/data/client"
	"user/internal/server"
	"user/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger, helper *log.Helper) (*kratos.App, func(), error) {
	etcdClient, cleanup, err := data.NewEtcdClient(helper, bootstrap)
	if err != nil {
		return nil, nil, err
	}
	genClient, cleanup2, err := client.NewDataBaseClient(helper, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseService := service.NewBaseService(bootstrap, helper, etcdClient, genClient)
	systemService := service.NewSystemService(baseService)
	verifyService := service.NewVerifyService()
	redisClient, cleanup3, err := data.NewRedisClient(helper, bootstrap)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	rabbitMQClient, cleanup4, err := data.NewRabbitMQClient(helper, bootstrap)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPool, cleanup5, err := util.NewEventPool(helper)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	baseDomain := biz.NewBaseDomain(bootstrap, helper, genClient, etcdClient, redisClient, rabbitMQClient, eventPool)
	baseData := base.NewBaseData(bootstrap, helper, genClient, etcdClient, redisClient, rabbitMQClient)
	userRepo := data.NewUserRepo(baseData)
	tokenCache := util.NewTokenCache(helper, redisClient)
	tokenService := biz.NewTokenService(bootstrap)
	authenticationDomain, err := biz.NewAuthenticationDomain(baseDomain, userRepo, tokenCache, tokenService)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authenticationService := service.NewAuthenticationService(baseService, verifyService, authenticationDomain, userRepo)
	userDomain, err := biz.NewUserDomain(baseDomain)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userService := service.NewUserService(baseService, authenticationDomain, userDomain, userRepo)
	userRelationRepo := data.NewUserRelationRepo(baseData)
	userRelationDomain, err := biz.NewUserRelationDomain(baseDomain, userRelationRepo, userRepo)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userRelationService := service.NewUserRelationService(baseService, userRelationDomain)
	twoFactorAuthenticationDomain, err := biz.NewTwoFactorAuthenticationDomain(baseDomain, userRepo)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	twoFactorAuthenticationService := service.NewTwoFactorAuthenticationService(baseService, twoFactorAuthenticationDomain)
	v := service.ProvideServices(systemService, authenticationService, userService, userRelationService, twoFactorAuthenticationService)
	grpcServer := server.NewGRPCServer(bootstrap, logger, v, tokenCache)
	httpServer := server.NewHTTPServer(bootstrap, logger, v, tokenCache)
	app := newApp(logger, helper, grpcServer, httpServer, etcdClient)
	return app, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}
