syntax = "proto3";

package common.api.app.bbs.v1.user;

import "google/api/annotations.proto";
import "bbs/v1/user/enum.proto";
import "common/enums/language.proto";

option go_package = "common/proto/gen/bbs/v1/user;user";

// 账号地理资料接口。
service LocationService {
  // 获取当前账号的地理资料。
  rpc GetCurrent(GetCurrentLocation.Req) returns (GetCurrentLocation.Resp) {
    option (google.api.http) = {
      post: "/v1/user/location/get-current"
      body: "*"
    };
  }

  // 更新当前账号的地理资料。
  rpc UpsertCurrent(UpsertCurrentLocation.Req) returns (UpsertCurrentLocation.Resp) {
    option (google.api.http) = {
      post: "/v1/user/location/upsert-current"
      body: "*"
    };
  }
}

// 获取当前账号的地理资料。
message GetCurrentLocation {
  message Req {}
  message Resp {

    message Location {
      // 账号 ID。
      int64 user_id = 1;
      // 国家或地区。
      optional string country = 2;
      // 省份或州。
      optional string province = 3;
      // 城市。
      optional string city = 4;
    }
    // 当前账号地理资料。
    Location location = 1;
  }
}

// 更新当前账号的地理资料。
message UpsertCurrentLocation {
  message Req {
    // 国家或地区。
    optional string country = 1;
    // 省份或州。
    optional string province = 2;
    // 城市。
    optional string city = 3;
  }
  message Resp {

    message Location {
      // 账号 ID。
      int64 user_id = 1;
      // 国家或地区。
      optional string country = 2;
      // 省份或州。
      optional string province = 3;
      // 城市。
      optional string city = 4;
    }
    // 更新后的账号地理资料。
    Location location = 1;
  }
}
