/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.bass.bbs.api;

import com.bass.bbs.ApiClient;
import com.bass.bbs.ApiException;
import com.bass.bbs.ApiResponse;
import com.bass.bbs.Configuration;
import com.bass.bbs.Pair;

import com.bass.bbs.model.GetCurrentPrivacySettingReply;
import com.bass.bbs.model.UpdateCurrentPrivacySettingReply;
import com.bass.bbs.model.UpdateCurrentPrivacySettingRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class PrivacySettingServiceApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public PrivacySettingServiceApi() {
    this(Configuration.getDefaultApiClient());
  }

  public PrivacySettingServiceApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceGetCurrentRequest}
   * @return GetCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public GetCurrentPrivacySettingReply privacySettingServiceGetCurrent(APIPrivacySettingServiceGetCurrentRequest apiRequest) throws ApiException {
    return privacySettingServiceGetCurrent(apiRequest, null);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceGetCurrentRequest}
   * @param headers Optional headers to include in the request
   * @return GetCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public GetCurrentPrivacySettingReply privacySettingServiceGetCurrent(APIPrivacySettingServiceGetCurrentRequest apiRequest, Map<String, String> headers) throws ApiException {
    @javax.annotation.Nonnull
    Object body = apiRequest.body();
    return privacySettingServiceGetCurrent(body, headers);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceGetCurrentRequest}
   * @return ApiResponse&lt;GetCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetCurrentPrivacySettingReply> privacySettingServiceGetCurrentWithHttpInfo(APIPrivacySettingServiceGetCurrentRequest apiRequest) throws ApiException {
    return privacySettingServiceGetCurrentWithHttpInfo(apiRequest, null);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceGetCurrentRequest}
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetCurrentPrivacySettingReply> privacySettingServiceGetCurrentWithHttpInfo(APIPrivacySettingServiceGetCurrentRequest apiRequest, Map<String, String> headers) throws ApiException {
    Object body = apiRequest.body();
    return privacySettingServiceGetCurrentWithHttpInfo(body, headers);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param body  (required)
   * @return GetCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public GetCurrentPrivacySettingReply privacySettingServiceGetCurrent(@javax.annotation.Nonnull Object body) throws ApiException {
    return privacySettingServiceGetCurrent(body, null);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param body  (required)
   * @param headers Optional headers to include in the request
   * @return GetCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public GetCurrentPrivacySettingReply privacySettingServiceGetCurrent(@javax.annotation.Nonnull Object body, Map<String, String> headers) throws ApiException {
    ApiResponse<GetCurrentPrivacySettingReply> localVarResponse = privacySettingServiceGetCurrentWithHttpInfo(body, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param body  (required)
   * @return ApiResponse&lt;GetCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetCurrentPrivacySettingReply> privacySettingServiceGetCurrentWithHttpInfo(@javax.annotation.Nonnull Object body) throws ApiException {
    return privacySettingServiceGetCurrentWithHttpInfo(body, null);
  }

  /**
   * 
   * 获取当前登录账号的隐私设置
   * @param body  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GetCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GetCurrentPrivacySettingReply> privacySettingServiceGetCurrentWithHttpInfo(@javax.annotation.Nonnull Object body, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = privacySettingServiceGetCurrentRequestBuilder(body, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("privacySettingServiceGetCurrent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<GetCurrentPrivacySettingReply>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        GetCurrentPrivacySettingReply responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GetCurrentPrivacySettingReply>() {});
        

        return new ApiResponse<GetCurrentPrivacySettingReply>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder privacySettingServiceGetCurrentRequestBuilder(@javax.annotation.Nonnull Object body, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'body' is set
    if (body == null) {
      throw new ApiException(400, "Missing the required parameter 'body' when calling privacySettingServiceGetCurrent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/user/privacy-setting/get-current";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(body);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }


  public static final class APIPrivacySettingServiceGetCurrentRequest {
    @javax.annotation.Nonnull
    private Object body; //  (required)

    private APIPrivacySettingServiceGetCurrentRequest(Builder builder) {
      this.body = builder.body;
    }
    @javax.annotation.Nonnull
    public Object body() {
      return body;
    }
    public static Builder newBuilder() {
      return new Builder();
    }

    public static class Builder {
      private Object body;

      public Builder body(@javax.annotation.Nonnull Object body) {
        this.body = body;
        return this;
      }
      public APIPrivacySettingServiceGetCurrentRequest build() {
        return new APIPrivacySettingServiceGetCurrentRequest(this);
      }
    }
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceUpdateCurrentRequest}
   * @return UpdateCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public UpdateCurrentPrivacySettingReply privacySettingServiceUpdateCurrent(APIPrivacySettingServiceUpdateCurrentRequest apiRequest) throws ApiException {
    return privacySettingServiceUpdateCurrent(apiRequest, null);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceUpdateCurrentRequest}
   * @param headers Optional headers to include in the request
   * @return UpdateCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public UpdateCurrentPrivacySettingReply privacySettingServiceUpdateCurrent(APIPrivacySettingServiceUpdateCurrentRequest apiRequest, Map<String, String> headers) throws ApiException {
    @javax.annotation.Nonnull
    UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest = apiRequest.updateCurrentPrivacySettingRequest();
    return privacySettingServiceUpdateCurrent(updateCurrentPrivacySettingRequest, headers);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceUpdateCurrentRequest}
   * @return ApiResponse&lt;UpdateCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateCurrentPrivacySettingReply> privacySettingServiceUpdateCurrentWithHttpInfo(APIPrivacySettingServiceUpdateCurrentRequest apiRequest) throws ApiException {
    return privacySettingServiceUpdateCurrentWithHttpInfo(apiRequest, null);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param apiRequest {@link APIPrivacySettingServiceUpdateCurrentRequest}
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UpdateCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateCurrentPrivacySettingReply> privacySettingServiceUpdateCurrentWithHttpInfo(APIPrivacySettingServiceUpdateCurrentRequest apiRequest, Map<String, String> headers) throws ApiException {
    UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest = apiRequest.updateCurrentPrivacySettingRequest();
    return privacySettingServiceUpdateCurrentWithHttpInfo(updateCurrentPrivacySettingRequest, headers);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param updateCurrentPrivacySettingRequest  (required)
   * @return UpdateCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public UpdateCurrentPrivacySettingReply privacySettingServiceUpdateCurrent(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest) throws ApiException {
    return privacySettingServiceUpdateCurrent(updateCurrentPrivacySettingRequest, null);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param updateCurrentPrivacySettingRequest  (required)
   * @param headers Optional headers to include in the request
   * @return UpdateCurrentPrivacySettingReply
   * @throws ApiException if fails to make API call
   */
  public UpdateCurrentPrivacySettingReply privacySettingServiceUpdateCurrent(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<UpdateCurrentPrivacySettingReply> localVarResponse = privacySettingServiceUpdateCurrentWithHttpInfo(updateCurrentPrivacySettingRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param updateCurrentPrivacySettingRequest  (required)
   * @return ApiResponse&lt;UpdateCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateCurrentPrivacySettingReply> privacySettingServiceUpdateCurrentWithHttpInfo(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest) throws ApiException {
    return privacySettingServiceUpdateCurrentWithHttpInfo(updateCurrentPrivacySettingRequest, null);
  }

  /**
   * 
   * 更新当前登录账号的隐私设置
   * @param updateCurrentPrivacySettingRequest  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;UpdateCurrentPrivacySettingReply&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<UpdateCurrentPrivacySettingReply> privacySettingServiceUpdateCurrentWithHttpInfo(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = privacySettingServiceUpdateCurrentRequestBuilder(updateCurrentPrivacySettingRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("privacySettingServiceUpdateCurrent", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<UpdateCurrentPrivacySettingReply>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        UpdateCurrentPrivacySettingReply responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<UpdateCurrentPrivacySettingReply>() {});
        

        return new ApiResponse<UpdateCurrentPrivacySettingReply>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder privacySettingServiceUpdateCurrentRequestBuilder(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'updateCurrentPrivacySettingRequest' is set
    if (updateCurrentPrivacySettingRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'updateCurrentPrivacySettingRequest' when calling privacySettingServiceUpdateCurrent");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/user/privacy-setting/update-current";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(updateCurrentPrivacySettingRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }


  public static final class APIPrivacySettingServiceUpdateCurrentRequest {
    @javax.annotation.Nonnull
    private UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest; //  (required)

    private APIPrivacySettingServiceUpdateCurrentRequest(Builder builder) {
      this.updateCurrentPrivacySettingRequest = builder.updateCurrentPrivacySettingRequest;
    }
    @javax.annotation.Nonnull
    public UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest() {
      return updateCurrentPrivacySettingRequest;
    }
    public static Builder newBuilder() {
      return new Builder();
    }

    public static class Builder {
      private UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest;

      public Builder updateCurrentPrivacySettingRequest(@javax.annotation.Nonnull UpdateCurrentPrivacySettingRequest updateCurrentPrivacySettingRequest) {
        this.updateCurrentPrivacySettingRequest = updateCurrentPrivacySettingRequest;
        return this;
      }
      public APIPrivacySettingServiceUpdateCurrentRequest build() {
        return new APIPrivacySettingServiceUpdateCurrentRequest(this);
      }
    }
  }

}
