/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProfileVisibility
 */
class ProfileVisibilityTest {
    private final ProfileVisibility model = new ProfileVisibility();

    /**
     * Model tests for ProfileVisibility
     */
    @Test
    void testProfileVisibility() {
        // TODO: test ProfileVisibility
    }

    /**
     * Test the property 'articles'
     */
    @Test
    void articlesTest() {
        // TODO: test articles
    }

    /**
     * Test the property 'comments'
     */
    @Test
    void commentsTest() {
        // TODO: test comments
    }

    /**
     * Test the property 'followers'
     */
    @Test
    void followersTest() {
        // TODO: test followers
    }

    /**
     * Test the property 'following'
     */
    @Test
    void followingTest() {
        // TODO: test following
    }

}
