syntax = "proto3";

package common.api.app.notify.v1;

option go_package = "common/api/gen/notify/v1;v1";

enum NotificationStatus {
  NOTIFICATION_STATUS_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_STATUS_NORMAL = 1; // 正常
  NOTIFICATION_STATUS_CANCEL = 2; // 取消
}

enum NotificationChannel {
  NOTIFICATION_CHANNEL_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_CHANNEL_EMAIL = 1; // 邮件
  NOTIFICATION_CHANNEL_SMS = 2; // 短信
  NOTIFICATION_CHANNEL_STATION = 3; // 站内信
  NOTIFICATION_CHANNEL_WEBHOOK = 4; // Webhook
}

enum NotificationDeliveryStatus {
  NOTIFICATION_DELIVERY_STATUS_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_DELIVERY_STATUS_PENDING = 1; // 等待投递
  NOTIFICATION_DELIVERY_STATUS_SENDING = 2; // 正在投递
  NOTIFICATION_DELIVERY_STATUS_SENT = 3; // 已投递
  NOTIFICATION_DELIVERY_STATUS_FAILED = 4; // 投递失败
}
