syntax = "proto3";

package common.api.app.notify.v1;

import "google/api/annotations.proto";
import "common/v1/common.proto";
import "notify/v1/model.proto";

option go_package = "common/api/gen/notify/v1;v1";

// NotificationRecord 服务
service NotifyNotificationRecordService {

  // 查询通知详情数据
  rpc Page (PageNotificationRecord.Request) returns (PageNotificationRecord.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-record/page"
      body: "*"
    };
  }

  // 已读
  rpc Read (ReadNotificationRecord.Request) returns (ReadNotificationRecord.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-record/read"
      body: "*"
    };
  }

}

message PageNotificationRecord {
  message Request {
    // 分页参数
    common.v1.PageRequest page = 1;
    // 查询条件
    NotificationRecordQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.v1.PageReply page = 1;
    // 通知记录列表
    repeated NotificationRecord rows = 2;
  }
}

message ReadNotificationRecord {
  message Request {
    // 通知 ID 列表
    repeated int64 ids = 1;
    // 已读时间范围
    common.v1.TimeRange read_time_range = 2;
    // 通知记录 ID 列表
    repeated int64 notification_record_ids = 3;
  }
  message Reply {
    // 已读数量
    int32 count = 1;
  }
}