syntax = "proto3";

package common.api.app.notify.v1;

import "common/common.proto";
import "google/api/annotations.proto";
import "notify/v1/enum.proto";
import "notify/v1/model.proto";
import "validate/validate.proto";

option go_package = "common/api/gen/notify/v1;v1";

// NotificationTemplate 服务
service NotifyNotificationTemplateService {
  // 查询通知模板
  rpc Page(PageNotificationTemplate.Request) returns (PageNotificationTemplate.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-template/page"
      body: "*"
    };
  }

  // 添加通知模板
  rpc Add(AddNotificationTemplate.Request) returns (AddNotificationTemplate.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-template/add"
      body: "*"
    };
  }

  // 更新通知模板
  rpc Update(UpdateNotificationTemplate.Request) returns (UpdateNotificationTemplate.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-template/update"
      body: "*"
    };
  }
}

message PageNotificationTemplate {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询条件
    NotificationTemplateQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 模板列表
    repeated NotificationTemplate rows = 2;
  }
}

message AddNotificationTemplate {
  message Request {
    // 通知模板
    NotificationTemplate notification_template = 2;
  }
  message Reply {
    // 添加后的模板
    NotificationTemplate notification_template = 1;
  }
}

message UpdateNotificationTemplate {
  message Request {
    // 模板 ID
    int64 id = 1;
    // 通知类型
    optional NotificationType notification_type = 5 [(validate.rules).enum = {
      defined_only: true
      not_in: [0]
    }];
    // 通知渠道
    optional NotificationChannel channel = 6 [(validate.rules).enum = {
      defined_only: true
      not_in: [0]
    }];
    // 内容模板
    optional string content = 7;
    // 是否启用
    optional bool enable = 9;
  }
  message Reply {
    // 更新后的模板
    NotificationTemplate notification_template = 1;
  }
}
