syntax = "proto3";

package common.api.app.notify.v1;

import "google/api/annotations.proto";
import "common/v1/common.proto";
import "notify/v1/model.proto";

option go_package = "common/api/gen/notify/v1;v1";

// NotificationMeta 服务
service NotifyNotificationMetaService {

  // 查询通知元数据
  rpc Page (PageNotificationMetaMeta.Request) returns (PageNotificationMetaMeta.Reply) {
    option (google.api.http) = {
      post: "/v1/notification-meta/page"
      body: "*"
    };
  }

}

message PageNotificationMetaMeta {
  message Request {
    // 分页参数
    common.v1.PageRequest page = 1;
    // 查询条件
    NotificationMetaQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.v1.PageReply page = 1;
    // 元数据列表
    repeated NotificationMeta rows = 2;
  }
}