syntax = "proto3";

package common.api.app.notify.v1;

import "common/common.proto";
import "google/api/annotations.proto";
import "notify/v1/oss_model.proto";

option go_package = "common/api/gen/notify/v1;v1";

service NotifyOssService {
  rpc GetUploadToken(GetUploadTokenOss.Request) returns (GetUploadTokenOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/get-upload-token"
      body: "*"
    };
  }

  rpc Audit(AuditOss.Request) returns (AuditOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/audit"
      body: "*"
    };
  }

  rpc Page(PageOssOss.Request) returns (PageOssOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/page"
      body: "*"
    };
  }

  rpc QiniuUploadCallback(QiniuUploadCallbackOss.Request) returns (QiniuUploadCallbackOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/qiniu/upload-callback"
      body: "*"
    };
  }

  rpc QiniuIncrementAuditCallback(QiniuIncrementAuditCallbackOss.Request) returns (QiniuIncrementAuditCallbackOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/qiniu/increment-audit-callback"
      body: "*"
    };
  }
}

message GetUploadTokenOss {
  message Request {
    int32 num = 1;
  }
  message Reply {
    repeated UploadToken upload_token = 1;
  }
}

message AuditOss {
  message Request {
    string key = 1;
    bool status = 2;
    optional string reason = 3;
  }
  message Reply {}
}

message PageOssOss {
  message Request {
    common.PageRequest page = 1;
    OssQueryParams query = 2;
  }
  message Reply {
    common.PageReply page = 1;
    repeated Oss rows = 2;
  }
}

message QiniuUploadCallbackOss {
  message Request {
    string key = 1;
    string hash = 2;
    int64 size = 3;
    string bucket = 4;
    string name = 5;
    string mime_type = 6;
    int64 upload_by = 7;
    string upload_by_name = 8;
  }
  message Reply {}
}

message QiniuIncrementAuditCallbackOss {
  message Request {
    string id = 1;
    string pipeline = 2;
    int32 code = 3;
    string desc = 4;
    string reqid = 5;
    string inputBucket = 6;
    string inputKey = 7;
    repeated Item items = 8;
  }
  message Reply {}
}
