syntax = "proto3";

package common.api.app.game_town.v1;

import "game_town/v1/enum.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "common/proto/gen/game_town/v1;v1";

service GameTownSessionService {
  rpc Start(StartGameTownSession.Request) returns (StartGameTownSession.Response) {} // 开始会话。
  rpc End(EndGameTownSession.Request) returns (EndGameTownSession.Response) {} // 结束会话。
}

message StartGameTownSession {
  message Request {
      optional int64 player_id = 1; // 玩家 ID
      GameTownSessionClientType client_type = 2; // 客户端类型
    }
  message Response {

    message GameTownSession {
        google.protobuf.Timestamp created_at = 1000; // 创建时间
        google.protobuf.Timestamp updated_at = 1001; // 更新时间
        int64 id = 1; // 会话 ID
        optional int64 player_id = 2; // 玩家 ID
        optional int64 current_world_id = 3; // 当前世界 ID
        GameTownSessionClientType client_type = 4; // 客户端类型
        google.protobuf.Timestamp started_at = 5; // 开始时间
        google.protobuf.Timestamp last_seen_at = 6; // 最近活跃时间
        optional google.protobuf.Timestamp ended_at = 7; // 结束时间
      }
      GameTownSession row = 1; // 会话
    }
}

message EndGameTownSession {
  message Request {
      int64 id = 1; // 会话 ID
    }
  message Response {

    message GameTownSession {
        google.protobuf.Timestamp created_at = 1000; // 创建时间
        google.protobuf.Timestamp updated_at = 1001; // 更新时间
        int64 id = 1; // 会话 ID
        optional int64 player_id = 2; // 玩家 ID
        optional int64 current_world_id = 3; // 当前世界 ID
        GameTownSessionClientType client_type = 4; // 客户端类型
        google.protobuf.Timestamp started_at = 5; // 开始时间
        google.protobuf.Timestamp last_seen_at = 6; // 最近活跃时间
        optional google.protobuf.Timestamp ended_at = 7; // 结束时间
      }
      GameTownSession row = 1; // 会话
    }
}
