syntax = "proto3";

package common.api.app.im.v1;

import "common/common.proto";
import "google/api/annotations.proto";
import "im/v1/model.proto";

option go_package = "common/api/gen/im/v1;v1";

// ChatSession 服务
service IMChatSessionService {
  // 免打扰
  rpc MarkMuted(MarkMutedChatSession.Request) returns (MarkMutedChatSession.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-session/mute"
      body: "*"
    };
  }

  // 置顶
  rpc MarkPinned(MarkPinnedChatSession.Request) returns (MarkPinnedChatSession.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-session/pin"
      body: "*"
    };
  }

  // 标为已读
  rpc MarkRead(MarkReadChatSession.Request) returns (MarkReadChatSession.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-session/mark-read"
      body: "*"
    };
  }

  // 查询会话数据
  rpc List(ListChatSessions.Request) returns (ListChatSessions.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-session/list"
      body: "*"
    };
  }
}

message MarkMutedChatSession {
  message Request {
    // 会话ID
    repeated int64 ids = 1;
    // 是否免打扰
    bool disturb = 2;
  }
  message Reply {}
}

message MarkPinnedChatSession {
  message Request {
    // 会话ID
    repeated int64 ids = 1;
    // 是否置顶
    bool top = 2;
  }
  message Reply {}
}

message MarkReadChatSession {
  message Request {
    // 会话ID
    repeated int64 ids = 1;
  }
  message Reply {}
}

message ListChatSessions {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询参数
    ChatSessionQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 消息信息
    repeated ChatSession rows = 2;
  }
}
