syntax = "proto3";

package common.api.app.im.v1;

import "common/common.proto";
import "google/api/annotations.proto";
import "im/v1/enum.proto";
import "im/v1/model.proto";

option go_package = "common/api/gen/im/v1;v1";

// ChatMessage 服务
service IMChatMessageService {
  // 发送消息
  rpc Send(SendChatMessage.Request) returns (SendChatMessage.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-message/send"
      body: "*"
    };
  }

  // 撤回消息
  rpc Revoke(RevokeChatMessage.Request) returns (RevokeChatMessage.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-message/revoke"
      body: "*"
    };
  }

  // 查询消息数据
  rpc Page(PageChatMessage.Request) returns (PageChatMessage.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-message/page"
      body: "*"
    };
  }
}

message SendChatMessage {
  message Request {
    // 接收者 ID
    int64 receiver_id = 1;
    // 接收者类型
    ReceiverType receiver_type = 2;
    // 消息类型
    MessageType type = 5;
    // 内容
    string content = 6;
  }
  message Reply {}
}

message RevokeChatMessage {
  message Request {
    // 主键
    int64 id = 1;
  }
  message Reply {}
}

message PageChatMessage {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询参数
    ChatMessageQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 消息信息
    repeated ChatMessage rows = 2;
  }
}
