// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: im/v1/chat_session.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationIMChatSessionServiceMarkMuted = "/common.api.im.v1.IMChatSessionService/MarkMuted"
const OperationIMChatSessionServiceMarkPinned = "/common.api.im.v1.IMChatSessionService/MarkPinned"
const OperationIMChatSessionServiceMarkRead = "/common.api.im.v1.IMChatSessionService/MarkRead"
const OperationIMChatSessionServicePage = "/common.api.im.v1.IMChatSessionService/Page"

type IMChatSessionServiceHTTPServer interface {
	// MarkMuted 免打扰
	MarkMuted(context.Context, *ChatSessionMarkMutedRequest) (*ChatSessionMarkMutedReply, error)
	// MarkPinned 置顶
	MarkPinned(context.Context, *ChatSessionMarkPinnedRequest) (*ChatSessionMarkPinnedReply, error)
	// MarkRead 标为已读
	MarkRead(context.Context, *ChatSessionMarkReadRequest) (*ChatSessionMarkReadReply, error)
	// Page 查询会话数据
	Page(context.Context, *ChatSessionPageRequest) (*ChatSessionPageReply, error)
}

func RegisterIMChatSessionServiceHTTPServer(s *http.Server, srv IMChatSessionServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/chatSession/markMuted", _IMChatSessionService_MarkMuted0_HTTP_Handler(srv))
	r.POST("/v1/chatSession/markPinned", _IMChatSessionService_MarkPinned0_HTTP_Handler(srv))
	r.POST("/v1/chatSession/markRead", _IMChatSessionService_MarkRead0_HTTP_Handler(srv))
	r.POST("/v1/chatSession/page", _IMChatSessionService_Page7_HTTP_Handler(srv))
}

func _IMChatSessionService_MarkMuted0_HTTP_Handler(srv IMChatSessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatSessionMarkMutedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIMChatSessionServiceMarkMuted)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkMuted(ctx, req.(*ChatSessionMarkMutedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSessionMarkMutedReply)
		return ctx.Result(200, reply)
	}
}

func _IMChatSessionService_MarkPinned0_HTTP_Handler(srv IMChatSessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatSessionMarkPinnedRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIMChatSessionServiceMarkPinned)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkPinned(ctx, req.(*ChatSessionMarkPinnedRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSessionMarkPinnedReply)
		return ctx.Result(200, reply)
	}
}

func _IMChatSessionService_MarkRead0_HTTP_Handler(srv IMChatSessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatSessionMarkReadRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIMChatSessionServiceMarkRead)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.MarkRead(ctx, req.(*ChatSessionMarkReadRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSessionMarkReadReply)
		return ctx.Result(200, reply)
	}
}

func _IMChatSessionService_Page7_HTTP_Handler(srv IMChatSessionServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ChatSessionPageRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationIMChatSessionServicePage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Page(ctx, req.(*ChatSessionPageRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ChatSessionPageReply)
		return ctx.Result(200, reply)
	}
}

type IMChatSessionServiceHTTPClient interface {
	// MarkMuted 免打扰
	MarkMuted(ctx context.Context, req *ChatSessionMarkMutedRequest, opts ...http.CallOption) (rsp *ChatSessionMarkMutedReply, err error)
	// MarkPinned 置顶
	MarkPinned(ctx context.Context, req *ChatSessionMarkPinnedRequest, opts ...http.CallOption) (rsp *ChatSessionMarkPinnedReply, err error)
	// MarkRead 标为已读
	MarkRead(ctx context.Context, req *ChatSessionMarkReadRequest, opts ...http.CallOption) (rsp *ChatSessionMarkReadReply, err error)
	// Page 查询会话数据
	Page(ctx context.Context, req *ChatSessionPageRequest, opts ...http.CallOption) (rsp *ChatSessionPageReply, err error)
}

type IMChatSessionServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewIMChatSessionServiceHTTPClient(client *http.Client) IMChatSessionServiceHTTPClient {
	return &IMChatSessionServiceHTTPClientImpl{client}
}

// MarkMuted 免打扰
func (c *IMChatSessionServiceHTTPClientImpl) MarkMuted(ctx context.Context, in *ChatSessionMarkMutedRequest, opts ...http.CallOption) (*ChatSessionMarkMutedReply, error) {
	var out ChatSessionMarkMutedReply
	pattern := "/v1/chatSession/markMuted"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIMChatSessionServiceMarkMuted))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MarkPinned 置顶
func (c *IMChatSessionServiceHTTPClientImpl) MarkPinned(ctx context.Context, in *ChatSessionMarkPinnedRequest, opts ...http.CallOption) (*ChatSessionMarkPinnedReply, error) {
	var out ChatSessionMarkPinnedReply
	pattern := "/v1/chatSession/markPinned"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIMChatSessionServiceMarkPinned))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// MarkRead 标为已读
func (c *IMChatSessionServiceHTTPClientImpl) MarkRead(ctx context.Context, in *ChatSessionMarkReadRequest, opts ...http.CallOption) (*ChatSessionMarkReadReply, error) {
	var out ChatSessionMarkReadReply
	pattern := "/v1/chatSession/markRead"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIMChatSessionServiceMarkRead))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Page 查询会话数据
func (c *IMChatSessionServiceHTTPClientImpl) Page(ctx context.Context, in *ChatSessionPageRequest, opts ...http.CallOption) (*ChatSessionPageReply, error) {
	var out ChatSessionPageReply
	pattern := "/v1/chatSession/page"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationIMChatSessionServicePage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
