syntax = "proto3";

package common.api.app.im.v1;

import "google/api/annotations.proto";
import "common/common.proto";
import "im/v1/model.proto";

option go_package = "common/api/gen/im/v1;v1";

// ChatGroup 服务
service IMChatGroupService {

  // 创建群组
  rpc Create (CreateChatGroup.Request) returns (CreateChatGroup.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-group/create"
      body: "*"
    };
  }

  // 解散群组
  rpc Dismiss (DismissChatGroup.Request) returns (DismissChatGroup.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-group/dismiss"
      body: "*"
    };
  }

  // 查询群组列表
  rpc Page (PageChatGroup.Request) returns (PageChatGroup.Reply) {
    option (google.api.http) = {
      post: "/v1/chat-group/page"
      body: "*"
    };
  }

}

message CreateChatGroup {
  message Request {
    // 群名称
    string name = 2;
    // 群头像
    optional string avatar = 3;
    // 群简介
    optional string introduction = 4;
  }
  message Reply {}
}

message DismissChatGroup {
  message Request {
    // 群组ID
    int64 id = 1;
  }
  message Reply {}
}

message PageChatGroup {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询参数
    ChatGroupQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 群组列表
    repeated ChatGroup rows = 2;
  }
}