syntax = "proto3";

package common.api.connector.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "common/v1/common.proto";
import "signal/v1/model.proto";

option go_package = "common/api/connector/v1;v1";

// 服务
service ConnectorService {
  // ping
  rpc Ping(PingRequest) returns (PingReply) {
    option (google.api.http) = {
      get: "/v1/ping"
    };
  }

  // 工作量证明
  rpc Pow(PowRequest) returns (PowReply) {
    option (google.api.http) = {
      post: "/v1/pow"
      body: "*"
    };
  }

  // Session 会话
  rpc Session(SessionRequest) returns (SessionReply) {
    option (google.api.http) = {
      post: "/v1/session"
      body: "*"
    };
  }

  // 发送消息
  rpc Send(SendRequest) returns (SendReply) {
    option (google.api.http) = {
      post: "/v1/send"
      body: "*"
    };
  }
}

// 参数

message PingRequest {}
message PingReply {}

message PowRequest {
  // 初始字符串
  string challenge = 1 [(validate.rules).string.min_len = 1];
  // 难度
  int32 difficulty = 2 [(validate.rules).int32.gt = 0];
}
message PowReply {
  // 计算次数
  string nonce = 1;
  // 计算结果
  string hash_hex = 2;
}

message SessionRequest {}
message SessionReply {
  // 在线会话 id 列表
  repeated string session_ids = 1;
}

message SendRequest {
  // 消息
  repeated signal.v1.Message messages = 1;
}
message SendReply {}
