syntax = "proto3";

package common.api.connector.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";
import "google/protobuf/timestamp.proto";
import "common/v1/common.proto";

option go_package = "common/api/connector/v1;v1";

// Health 服务
service ConnectorHealthService {
  // ping
  rpc Ping(PingRequest) returns (PingResponse) {
    option (google.api.http) = {
      get: "/v1/health/ping"
    };
  }

  // 工作量证明
  rpc Pow(PowRequest) returns (PowResponse) {
    option (google.api.http) = {
      post: "/v1/health/pow"
      body: "*"
    };
  }
}

// 参数

message PingRequest {}
message PingResponse {}

message PowRequest {
  // 初始字符串
  string challenge = 1 [(validate.rules).string.min_len = 1];
  // 难度
  int32 difficulty = 2 [(validate.rules).int32.gt = 0];
}
message PowResponse {
  // 计算次数
  string nonce = 1;
  // 计算结果
  string hash_hex = 2;
}

