// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: user/v1/authentication.proto

package v1

import (
	_ "common/api/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// 密码
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// 用户名
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// 昵称
	Nickname      *string `protobuf:"bytes,4,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEmailRequest) Reset() {
	*x = RegisterEmailRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailRequest) ProtoMessage() {}

func (x *RegisterEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailRequest.ProtoReflect.Descriptor instead.
func (*RegisterEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterEmailRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterEmailRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterEmailRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

type RegisterEmailReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码令牌
	CodeToken string `protobuf:"bytes,1,opt,name=code_token,json=codeToken,proto3" json:"code_token,omitempty"`
	// 验证码（仅供调试使用）
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEmailReply) Reset() {
	*x = RegisterEmailReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailReply) ProtoMessage() {}

func (x *RegisterEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailReply.ProtoReflect.Descriptor instead.
func (*RegisterEmailReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterEmailReply) GetCodeToken() string {
	if x != nil {
		return x.CodeToken
	}
	return ""
}

func (x *RegisterEmailReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type RegisterEmailVerifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证码
	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	// 验证码令牌
	CodeToken     string `protobuf:"bytes,2,opt,name=code_token,json=codeToken,proto3" json:"code_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEmailVerifyRequest) Reset() {
	*x = RegisterEmailVerifyRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEmailVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailVerifyRequest) ProtoMessage() {}

func (x *RegisterEmailVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailVerifyRequest.ProtoReflect.Descriptor instead.
func (*RegisterEmailVerifyRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterEmailVerifyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RegisterEmailVerifyRequest) GetCodeToken() string {
	if x != nil {
		return x.CodeToken
	}
	return ""
}

type RegisterEmailVerifyReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterEmailVerifyReply) Reset() {
	*x = RegisterEmailVerifyReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterEmailVerifyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterEmailVerifyReply) ProtoMessage() {}

func (x *RegisterEmailVerifyReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterEmailVerifyReply.ProtoReflect.Descriptor instead.
func (*RegisterEmailVerifyReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{3}
}

type ExistEmailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邮箱
	Email         string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistEmailRequest) Reset() {
	*x = ExistEmailRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistEmailRequest) ProtoMessage() {}

func (x *ExistEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistEmailRequest.ProtoReflect.Descriptor instead.
func (*ExistEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *ExistEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ExistEmailReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否存在
	Exist         *bool `protobuf:"varint,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistEmailReply) Reset() {
	*x = ExistEmailReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistEmailReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistEmailReply) ProtoMessage() {}

func (x *ExistEmailReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistEmailReply.ProtoReflect.Descriptor instead.
func (*ExistEmailReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{5}
}

func (x *ExistEmailReply) GetExist() bool {
	if x != nil && x.Exist != nil {
		return *x.Exist
	}
	return false
}

type ExistUsernameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 用户名
	Username      string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistUsernameRequest) Reset() {
	*x = ExistUsernameRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistUsernameRequest) ProtoMessage() {}

func (x *ExistUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistUsernameRequest.ProtoReflect.Descriptor instead.
func (*ExistUsernameRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{6}
}

func (x *ExistUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ExistUsernameReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否存在
	Exist         *bool `protobuf:"varint,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistUsernameReply) Reset() {
	*x = ExistUsernameReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistUsernameReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistUsernameReply) ProtoMessage() {}

func (x *ExistUsernameReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistUsernameReply.ProtoReflect.Descriptor instead.
func (*ExistUsernameReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{7}
}

func (x *ExistUsernameReply) GetExist() bool {
	if x != nil && x.Exist != nil {
		return *x.Exist
	}
	return false
}

type ExistPhoneRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 手机号
	Phone         string `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistPhoneRequest) Reset() {
	*x = ExistPhoneRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistPhoneRequest) ProtoMessage() {}

func (x *ExistPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistPhoneRequest.ProtoReflect.Descriptor instead.
func (*ExistPhoneRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{8}
}

func (x *ExistPhoneRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type ExistPhoneReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 是否存在
	Exist         *bool `protobuf:"varint,1,opt,name=exist,proto3,oneof" json:"exist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistPhoneReply) Reset() {
	*x = ExistPhoneReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistPhoneReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistPhoneReply) ProtoMessage() {}

func (x *ExistPhoneReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistPhoneReply.ProtoReflect.Descriptor instead.
func (*ExistPhoneReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{9}
}

func (x *ExistPhoneReply) GetExist() bool {
	if x != nil && x.Exist != nil {
		return *x.Exist
	}
	return false
}

type LoginAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 账号（用户名/邮箱）
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	// 密码
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountRequest) Reset() {
	*x = LoginAccountRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountRequest) ProtoMessage() {}

func (x *LoginAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountRequest.ProtoReflect.Descriptor instead.
func (*LoginAccountRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{10}
}

func (x *LoginAccountRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *LoginAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginAccountReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 登录令牌
	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// 用户信息
	User          *User `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginAccountReply) Reset() {
	*x = LoginAccountReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginAccountReply) ProtoMessage() {}

func (x *LoginAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginAccountReply.ProtoReflect.Descriptor instead.
func (*LoginAccountReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{11}
}

func (x *LoginAccountReply) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginAccountReply) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_user_v1_authentication_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{12}
}

type LogoutReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReply) Reset() {
	*x = LogoutReply{}
	mi := &file_user_v1_authentication_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReply) ProtoMessage() {}

func (x *LogoutReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_authentication_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReply.ProtoReflect.Descriptor instead.
func (*LogoutReply) Descriptor() ([]byte, []int) {
	return file_user_v1_authentication_proto_rawDescGZIP(), []int{13}
}

var File_user_v1_authentication_proto protoreflect.FileDescriptor

const file_user_v1_authentication_proto_rawDesc = "" +
	"\n" +
	"\x1cuser/v1/authentication.proto\x12\x12common.api.user.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x12user/v1/user.proto\"\x98\x01\n" +
	"\x14RegisterEmailRequest\x12\"\n" +
	"\x05email\x18\x01 \x01(\tB\f\xfaB\tr\a\x10\x05\x18\xc0\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\bnickname\x18\x04 \x01(\tH\x00R\bnickname\x88\x01\x01B\v\n" +
	"\t_nickname\"G\n" +
	"\x12RegisterEmailReply\x12\x1d\n" +
	"\n" +
	"code_token\x18\x01 \x01(\tR\tcodeToken\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"j\n" +
	"\x1aRegisterEmailVerifyRequest\x12-\n" +
	"\x04code\x18\x01 \x01(\tB\x19\xfaB\x16r\x14\x10\x06\x18\x062\x0e^[A-Za-z0-9]+$R\x04code\x12\x1d\n" +
	"\n" +
	"code_token\x18\x02 \x01(\tR\tcodeToken\"\x1a\n" +
	"\x18RegisterEmailVerifyReply\"7\n" +
	"\x11ExistEmailRequest\x12\"\n" +
	"\x05email\x18\x01 \x01(\tB\f\xfaB\tr\a\x10\x05\x18\xc0\x02`\x01R\x05email\"6\n" +
	"\x0fExistEmailReply\x12\x19\n" +
	"\x05exist\x18\x01 \x01(\bH\x00R\x05exist\x88\x01\x01B\b\n" +
	"\x06_exist\"_\n" +
	"\x14ExistUsernameRequest\x12G\n" +
	"\busername\x18\x01 \x01(\tB+\xfaB(r&\x10\x02\x18 2 ^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$R\busername\"9\n" +
	"\x12ExistUsernameReply\x12\x19\n" +
	"\x05exist\x18\x01 \x01(\bH\x00R\x05exist\x88\x01\x01B\b\n" +
	"\x06_exist\"\x82\x01\n" +
	"\x11ExistPhoneRequest\x12m\n" +
	"\x05phone\x18\x01 \x01(\tBW\xfaBTrR\x10\v\x18\v2L^(13[0-9]|14[01456879]|15[0-35-9]|16[2567]|17[0-8]|18[0-9]|19[0-35-9])\\d{8}$R\x05phone\"6\n" +
	"\x0fExistPhoneReply\x12\x19\n" +
	"\x05exist\x18\x01 \x01(\bH\x00R\x05exist\x88\x01\x01B\b\n" +
	"\x06_exist\"K\n" +
	"\x13LoginAccountRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"W\n" +
	"\x11LoginAccountReply\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12,\n" +
	"\x04user\x18\x02 \x01(\v2\x18.common.api.user.v1.UserR\x04user\"\x0f\n" +
	"\rLogoutRequest\"\r\n" +
	"\vLogoutReply2\xf8\a\n" +
	"\x19UserAuthenticationService\x12\x8f\x01\n" +
	"\rRegisterEmail\x12(.common.api.user.v1.RegisterEmailRequest\x1a&.common.api.user.v1.RegisterEmailReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/authentication/register/email\x12\xa8\x01\n" +
	"\x13RegisterEmailVerify\x12..common.api.user.v1.RegisterEmailVerifyRequest\x1a,.common.api.user.v1.RegisterEmailVerifyReply\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/authentication/register/email/verify\x12\x83\x01\n" +
	"\n" +
	"ExistEmail\x12%.common.api.user.v1.ExistEmailRequest\x1a#.common.api.user.v1.ExistEmailReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/authentication/exist/email\x12\x83\x01\n" +
	"\n" +
	"ExistPhone\x12%.common.api.user.v1.ExistPhoneRequest\x1a#.common.api.user.v1.ExistPhoneReply\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/authentication/exist/phone\x12\x8f\x01\n" +
	"\rExistUsername\x12(.common.api.user.v1.ExistUsernameRequest\x1a&.common.api.user.v1.ExistUsernameReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/v1/authentication/exist/username\x12\x8b\x01\n" +
	"\fLoginAccount\x12'.common.api.user.v1.LoginAccountRequest\x1a%.common.api.user.v1.LoginAccountReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/authentication/login/account\x12r\n" +
	"\x06Logout\x12!.common.api.user.v1.LogoutRequest\x1a\x1f.common.api.user.v1.LogoutReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/authentication/logoutB\x17Z\x15common/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_authentication_proto_rawDescOnce sync.Once
	file_user_v1_authentication_proto_rawDescData []byte
)

func file_user_v1_authentication_proto_rawDescGZIP() []byte {
	file_user_v1_authentication_proto_rawDescOnce.Do(func() {
		file_user_v1_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_authentication_proto_rawDesc), len(file_user_v1_authentication_proto_rawDesc)))
	})
	return file_user_v1_authentication_proto_rawDescData
}

var file_user_v1_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_user_v1_authentication_proto_goTypes = []any{
	(*RegisterEmailRequest)(nil),       // 0: common.api.user.v1.RegisterEmailRequest
	(*RegisterEmailReply)(nil),         // 1: common.api.user.v1.RegisterEmailReply
	(*RegisterEmailVerifyRequest)(nil), // 2: common.api.user.v1.RegisterEmailVerifyRequest
	(*RegisterEmailVerifyReply)(nil),   // 3: common.api.user.v1.RegisterEmailVerifyReply
	(*ExistEmailRequest)(nil),          // 4: common.api.user.v1.ExistEmailRequest
	(*ExistEmailReply)(nil),            // 5: common.api.user.v1.ExistEmailReply
	(*ExistUsernameRequest)(nil),       // 6: common.api.user.v1.ExistUsernameRequest
	(*ExistUsernameReply)(nil),         // 7: common.api.user.v1.ExistUsernameReply
	(*ExistPhoneRequest)(nil),          // 8: common.api.user.v1.ExistPhoneRequest
	(*ExistPhoneReply)(nil),            // 9: common.api.user.v1.ExistPhoneReply
	(*LoginAccountRequest)(nil),        // 10: common.api.user.v1.LoginAccountRequest
	(*LoginAccountReply)(nil),          // 11: common.api.user.v1.LoginAccountReply
	(*LogoutRequest)(nil),              // 12: common.api.user.v1.LogoutRequest
	(*LogoutReply)(nil),                // 13: common.api.user.v1.LogoutReply
	(*User)(nil),                       // 14: common.api.user.v1.User
}
var file_user_v1_authentication_proto_depIdxs = []int32{
	14, // 0: common.api.user.v1.LoginAccountReply.user:type_name -> common.api.user.v1.User
	0,  // 1: common.api.user.v1.UserAuthenticationService.RegisterEmail:input_type -> common.api.user.v1.RegisterEmailRequest
	2,  // 2: common.api.user.v1.UserAuthenticationService.RegisterEmailVerify:input_type -> common.api.user.v1.RegisterEmailVerifyRequest
	4,  // 3: common.api.user.v1.UserAuthenticationService.ExistEmail:input_type -> common.api.user.v1.ExistEmailRequest
	8,  // 4: common.api.user.v1.UserAuthenticationService.ExistPhone:input_type -> common.api.user.v1.ExistPhoneRequest
	6,  // 5: common.api.user.v1.UserAuthenticationService.ExistUsername:input_type -> common.api.user.v1.ExistUsernameRequest
	10, // 6: common.api.user.v1.UserAuthenticationService.LoginAccount:input_type -> common.api.user.v1.LoginAccountRequest
	12, // 7: common.api.user.v1.UserAuthenticationService.Logout:input_type -> common.api.user.v1.LogoutRequest
	1,  // 8: common.api.user.v1.UserAuthenticationService.RegisterEmail:output_type -> common.api.user.v1.RegisterEmailReply
	3,  // 9: common.api.user.v1.UserAuthenticationService.RegisterEmailVerify:output_type -> common.api.user.v1.RegisterEmailVerifyReply
	5,  // 10: common.api.user.v1.UserAuthenticationService.ExistEmail:output_type -> common.api.user.v1.ExistEmailReply
	9,  // 11: common.api.user.v1.UserAuthenticationService.ExistPhone:output_type -> common.api.user.v1.ExistPhoneReply
	7,  // 12: common.api.user.v1.UserAuthenticationService.ExistUsername:output_type -> common.api.user.v1.ExistUsernameReply
	11, // 13: common.api.user.v1.UserAuthenticationService.LoginAccount:output_type -> common.api.user.v1.LoginAccountReply
	13, // 14: common.api.user.v1.UserAuthenticationService.Logout:output_type -> common.api.user.v1.LogoutReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_user_v1_authentication_proto_init() }
func file_user_v1_authentication_proto_init() {
	if File_user_v1_authentication_proto != nil {
		return
	}
	file_user_v1_user_proto_init()
	file_user_v1_authentication_proto_msgTypes[0].OneofWrappers = []any{}
	file_user_v1_authentication_proto_msgTypes[5].OneofWrappers = []any{}
	file_user_v1_authentication_proto_msgTypes[7].OneofWrappers = []any{}
	file_user_v1_authentication_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_authentication_proto_rawDesc), len(file_user_v1_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_authentication_proto_goTypes,
		DependencyIndexes: file_user_v1_authentication_proto_depIdxs,
		MessageInfos:      file_user_v1_authentication_proto_msgTypes,
	}.Build()
	File_user_v1_authentication_proto = out.File
	file_user_v1_authentication_proto_goTypes = nil
	file_user_v1_authentication_proto_depIdxs = nil
}
