// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user/v1/oss.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UploadTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UploadTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadTokenRequestMultiError, or nil if none found.
func (m *UploadTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UploadTokenRequestMultiError(errors)
	}

	return nil
}

// UploadTokenRequestMultiError is an error wrapping multiple validation errors
// returned by UploadTokenRequest.ValidateAll() if the designated constraints
// aren't met.
type UploadTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadTokenRequestMultiError) AllErrors() []error { return m }

// UploadTokenRequestValidationError is the validation error returned by
// UploadTokenRequest.Validate if the designated constraints aren't met.
type UploadTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadTokenRequestValidationError) ErrorName() string {
	return "UploadTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadTokenRequestValidationError{}

// Validate checks the field values on UploadTokenReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadTokenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadTokenReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadTokenReplyMultiError, or nil if none found.
func (m *UploadTokenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadTokenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return UploadTokenReplyMultiError(errors)
	}

	return nil
}

// UploadTokenReplyMultiError is an error wrapping multiple validation errors
// returned by UploadTokenReply.ValidateAll() if the designated constraints
// aren't met.
type UploadTokenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadTokenReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadTokenReplyMultiError) AllErrors() []error { return m }

// UploadTokenReplyValidationError is the validation error returned by
// UploadTokenReply.Validate if the designated constraints aren't met.
type UploadTokenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadTokenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadTokenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadTokenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadTokenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadTokenReplyValidationError) ErrorName() string { return "UploadTokenReplyValidationError" }

// Error satisfies the builtin error interface
func (e UploadTokenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadTokenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadTokenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadTokenReplyValidationError{}
