syntax = "proto3";

package common.api.user.v1;

import "google/api/annotations.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";
import "common/v1/common.proto";

option go_package = "common/api/user/v1;v1";

// Oss 服务
service UserOssService {

  // 获取上传文件凭证
  rpc UploadToken (UploadTokenRequest) returns (UploadTokenReply) {
    option (google.api.http) = {
      post: "/v1/oss/uploadToken"
      body: "*"
    };
  }

  // 七牛上传回调
  rpc QiniuUploadCallback (QiniuUploadCallbackRequest) returns (QiniuUploadCallbackReply) {
    option (google.api.http) = {
      post: "/v1/oss/qiniu/uploadCallback"
      body: "*"
    };
  }

}

message UploadTokenRequest {
  // 上传文件数量
  int32 num = 1;
}
message UploadTokenReply {
  message UploadToken {
    // 文件key
    string key = 1;
    // 上传凭证
    string token = 2;
  }
  repeated UploadToken upload_token = 1;
}

message QiniuUploadCallbackRequest{
  string key = 1;
  string hash = 2;
  int64 size = 3;
  string bucket = 4;
  string name = 5;
  string mime_type = 6;
}
message QiniuUploadCallbackReply{}
