// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: user/v1/two_factor_authentication.proto

package v1

import (
	_ "common/api/common/v1"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTwoFactorAuthenticationValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 2FA 验证码
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationValidateRequest) Reset() {
	*x = UserTwoFactorAuthenticationValidateRequest{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationValidateRequest) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationValidateRequest.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationValidateRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *UserTwoFactorAuthenticationValidateRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserTwoFactorAuthenticationValidateReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 验证结果
	Verified      bool `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationValidateReply) Reset() {
	*x = UserTwoFactorAuthenticationValidateReply{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationValidateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationValidateReply) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationValidateReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationValidateReply.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationValidateReply) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *UserTwoFactorAuthenticationValidateReply) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type UserTwoFactorAuthenticationEnableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationEnableRequest) Reset() {
	*x = UserTwoFactorAuthenticationEnableRequest{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationEnableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationEnableRequest) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationEnableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationEnableRequest.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationEnableRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{2}
}

type UserTwoFactorAuthenticationEnableReply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 图片数据
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// 图片类型
	ContentType   string `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationEnableReply) Reset() {
	*x = UserTwoFactorAuthenticationEnableReply{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationEnableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationEnableReply) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationEnableReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationEnableReply.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationEnableReply) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *UserTwoFactorAuthenticationEnableReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UserTwoFactorAuthenticationEnableReply) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type UserTwoFactorAuthenticationDisableRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 2FA 验证码
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationDisableRequest) Reset() {
	*x = UserTwoFactorAuthenticationDisableRequest{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationDisableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationDisableRequest) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationDisableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationDisableRequest.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationDisableRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *UserTwoFactorAuthenticationDisableRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserTwoFactorAuthenticationDisableReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationDisableReply) Reset() {
	*x = UserTwoFactorAuthenticationDisableReply{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationDisableReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationDisableReply) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationDisableReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationDisableReply.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationDisableReply) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{5}
}

type UserTwoFactorAuthenticationConfirmRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 2FA 验证码
	Code          string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationConfirmRequest) Reset() {
	*x = UserTwoFactorAuthenticationConfirmRequest{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationConfirmRequest) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationConfirmRequest.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationConfirmRequest) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{6}
}

func (x *UserTwoFactorAuthenticationConfirmRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UserTwoFactorAuthenticationConfirmReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTwoFactorAuthenticationConfirmReply) Reset() {
	*x = UserTwoFactorAuthenticationConfirmReply{}
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTwoFactorAuthenticationConfirmReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTwoFactorAuthenticationConfirmReply) ProtoMessage() {}

func (x *UserTwoFactorAuthenticationConfirmReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_v1_two_factor_authentication_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTwoFactorAuthenticationConfirmReply.ProtoReflect.Descriptor instead.
func (*UserTwoFactorAuthenticationConfirmReply) Descriptor() ([]byte, []int) {
	return file_user_v1_two_factor_authentication_proto_rawDescGZIP(), []int{7}
}

var File_user_v1_two_factor_authentication_proto protoreflect.FileDescriptor

const file_user_v1_two_factor_authentication_proto_rawDesc = "" +
	"\n" +
	"'user/v1/two_factor_authentication.proto\x12\x12common.api.user.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x12user/v1/user.proto\"K\n" +
	"*UserTwoFactorAuthenticationValidateRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\x04code\"F\n" +
	"(UserTwoFactorAuthenticationValidateReply\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\"*\n" +
	"(UserTwoFactorAuthenticationEnableRequest\"_\n" +
	"&UserTwoFactorAuthenticationEnableReply\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\"J\n" +
	")UserTwoFactorAuthenticationDisableRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\x04code\")\n" +
	"'UserTwoFactorAuthenticationDisableReply\"J\n" +
	")UserTwoFactorAuthenticationConfirmRequest\x12\x1d\n" +
	"\x04code\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x06\x18\x06R\x04code\")\n" +
	"'UserTwoFactorAuthenticationConfirmReply2\xd5\x05\n" +
	"\"UserTwoFactorAuthenticationService\x12\xae\x01\n" +
	"\bValidate\x12>.common.api.user.v1.UserTwoFactorAuthenticationValidateRequest\x1a<.common.api.user.v1.UserTwoFactorAuthenticationValidateReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/v1/user/2FA/validate\x12\xa3\x01\n" +
	"\x06Enable\x12<.common.api.user.v1.UserTwoFactorAuthenticationEnableRequest\x1a:.common.api.user.v1.UserTwoFactorAuthenticationEnableReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/user/2FA/enable\x12\xaa\x01\n" +
	"\aDisable\x12=.common.api.user.v1.UserTwoFactorAuthenticationDisableRequest\x1a;.common.api.user.v1.UserTwoFactorAuthenticationDisableReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/user/2FA/disable\x12\xaa\x01\n" +
	"\aConfirm\x12=.common.api.user.v1.UserTwoFactorAuthenticationConfirmRequest\x1a;.common.api.user.v1.UserTwoFactorAuthenticationConfirmReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/user/2FA/confirmB\x17Z\x15common/api/user/v1;v1b\x06proto3"

var (
	file_user_v1_two_factor_authentication_proto_rawDescOnce sync.Once
	file_user_v1_two_factor_authentication_proto_rawDescData []byte
)

func file_user_v1_two_factor_authentication_proto_rawDescGZIP() []byte {
	file_user_v1_two_factor_authentication_proto_rawDescOnce.Do(func() {
		file_user_v1_two_factor_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_v1_two_factor_authentication_proto_rawDesc), len(file_user_v1_two_factor_authentication_proto_rawDesc)))
	})
	return file_user_v1_two_factor_authentication_proto_rawDescData
}

var file_user_v1_two_factor_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_v1_two_factor_authentication_proto_goTypes = []any{
	(*UserTwoFactorAuthenticationValidateRequest)(nil), // 0: common.api.user.v1.UserTwoFactorAuthenticationValidateRequest
	(*UserTwoFactorAuthenticationValidateReply)(nil),   // 1: common.api.user.v1.UserTwoFactorAuthenticationValidateReply
	(*UserTwoFactorAuthenticationEnableRequest)(nil),   // 2: common.api.user.v1.UserTwoFactorAuthenticationEnableRequest
	(*UserTwoFactorAuthenticationEnableReply)(nil),     // 3: common.api.user.v1.UserTwoFactorAuthenticationEnableReply
	(*UserTwoFactorAuthenticationDisableRequest)(nil),  // 4: common.api.user.v1.UserTwoFactorAuthenticationDisableRequest
	(*UserTwoFactorAuthenticationDisableReply)(nil),    // 5: common.api.user.v1.UserTwoFactorAuthenticationDisableReply
	(*UserTwoFactorAuthenticationConfirmRequest)(nil),  // 6: common.api.user.v1.UserTwoFactorAuthenticationConfirmRequest
	(*UserTwoFactorAuthenticationConfirmReply)(nil),    // 7: common.api.user.v1.UserTwoFactorAuthenticationConfirmReply
}
var file_user_v1_two_factor_authentication_proto_depIdxs = []int32{
	0, // 0: common.api.user.v1.UserTwoFactorAuthenticationService.Validate:input_type -> common.api.user.v1.UserTwoFactorAuthenticationValidateRequest
	2, // 1: common.api.user.v1.UserTwoFactorAuthenticationService.Enable:input_type -> common.api.user.v1.UserTwoFactorAuthenticationEnableRequest
	4, // 2: common.api.user.v1.UserTwoFactorAuthenticationService.Disable:input_type -> common.api.user.v1.UserTwoFactorAuthenticationDisableRequest
	6, // 3: common.api.user.v1.UserTwoFactorAuthenticationService.Confirm:input_type -> common.api.user.v1.UserTwoFactorAuthenticationConfirmRequest
	1, // 4: common.api.user.v1.UserTwoFactorAuthenticationService.Validate:output_type -> common.api.user.v1.UserTwoFactorAuthenticationValidateReply
	3, // 5: common.api.user.v1.UserTwoFactorAuthenticationService.Enable:output_type -> common.api.user.v1.UserTwoFactorAuthenticationEnableReply
	5, // 6: common.api.user.v1.UserTwoFactorAuthenticationService.Disable:output_type -> common.api.user.v1.UserTwoFactorAuthenticationDisableReply
	7, // 7: common.api.user.v1.UserTwoFactorAuthenticationService.Confirm:output_type -> common.api.user.v1.UserTwoFactorAuthenticationConfirmReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_v1_two_factor_authentication_proto_init() }
func file_user_v1_two_factor_authentication_proto_init() {
	if File_user_v1_two_factor_authentication_proto != nil {
		return
	}
	file_user_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_v1_two_factor_authentication_proto_rawDesc), len(file_user_v1_two_factor_authentication_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_v1_two_factor_authentication_proto_goTypes,
		DependencyIndexes: file_user_v1_two_factor_authentication_proto_depIdxs,
		MessageInfos:      file_user_v1_two_factor_authentication_proto_msgTypes,
	}.Build()
	File_user_v1_two_factor_authentication_proto = out.File
	file_user_v1_two_factor_authentication_proto_goTypes = nil
	file_user_v1_two_factor_authentication_proto_depIdxs = nil
}
