// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: user/v1/user_relation.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUserUserRelationServiceBlock = "/common.api.user.v1.UserUserRelationService/Block"
const OperationUserUserRelationServiceFollow = "/common.api.user.v1.UserUserRelationService/Follow"
const OperationUserUserRelationServicePage = "/common.api.user.v1.UserUserRelationService/Page"

type UserUserRelationServiceHTTPServer interface {
	// Block 屏蔽用户
	Block(context.Context, *BlockRequest) (*BlockReply, error)
	// Follow 关注用户
	Follow(context.Context, *FollowRequest) (*FollowReply, error)
	// Page 查询用户关系
	Page(context.Context, *PageUserRelationRequest) (*PageUserRelationReply, error)
}

func RegisterUserUserRelationServiceHTTPServer(s *http.Server, srv UserUserRelationServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/userRelation/follow", _UserUserRelationService_Follow0_HTTP_Handler(srv))
	r.POST("/api/v1/userRelation/block", _UserUserRelationService_Block0_HTTP_Handler(srv))
	r.POST("/api/v1/userRelation/page", _UserUserRelationService_Page9_HTTP_Handler(srv))
}

func _UserUserRelationService_Follow0_HTTP_Handler(srv UserUserRelationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FollowRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUserRelationServiceFollow)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Follow(ctx, req.(*FollowRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FollowReply)
		return ctx.Result(200, reply)
	}
}

func _UserUserRelationService_Block0_HTTP_Handler(srv UserUserRelationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in BlockRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUserRelationServiceBlock)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Block(ctx, req.(*BlockRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*BlockReply)
		return ctx.Result(200, reply)
	}
}

func _UserUserRelationService_Page9_HTTP_Handler(srv UserUserRelationServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PageUserRelationRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserUserRelationServicePage)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Page(ctx, req.(*PageUserRelationRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PageUserRelationReply)
		return ctx.Result(200, reply)
	}
}

type UserUserRelationServiceHTTPClient interface {
	// Block 屏蔽用户
	Block(ctx context.Context, req *BlockRequest, opts ...http.CallOption) (rsp *BlockReply, err error)
	// Follow 关注用户
	Follow(ctx context.Context, req *FollowRequest, opts ...http.CallOption) (rsp *FollowReply, err error)
	// Page 查询用户关系
	Page(ctx context.Context, req *PageUserRelationRequest, opts ...http.CallOption) (rsp *PageUserRelationReply, err error)
}

type UserUserRelationServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserUserRelationServiceHTTPClient(client *http.Client) UserUserRelationServiceHTTPClient {
	return &UserUserRelationServiceHTTPClientImpl{client}
}

// Block 屏蔽用户
func (c *UserUserRelationServiceHTTPClientImpl) Block(ctx context.Context, in *BlockRequest, opts ...http.CallOption) (*BlockReply, error) {
	var out BlockReply
	pattern := "/api/v1/userRelation/block"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserUserRelationServiceBlock))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Follow 关注用户
func (c *UserUserRelationServiceHTTPClientImpl) Follow(ctx context.Context, in *FollowRequest, opts ...http.CallOption) (*FollowReply, error) {
	var out FollowReply
	pattern := "/api/v1/userRelation/follow"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserUserRelationServiceFollow))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// Page 查询用户关系
func (c *UserUserRelationServiceHTTPClientImpl) Page(ctx context.Context, in *PageUserRelationRequest, opts ...http.CallOption) (*PageUserRelationReply, error) {
	var out PageUserRelationReply
	pattern := "/api/v1/userRelation/page"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUserUserRelationServicePage))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
