name: bass-application

networks:
  bass:
    driver: bridge
    external: true

services:
  treble:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/treble:latest
    container_name: treble
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "2324:2324"
    networks:
      - bass

  bbs:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/bbs:latest
    container_name: bbs
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8001:8001"
      - "9001:9001"
    networks:
      - bass

  user:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/user:latest
    container_name: user
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8101:8101"
      - "9101:9101"
    networks:
      - bass

  content:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/content:latest
    container_name: content
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8102:8102"
      - "9102:9102"
    networks:
      - bass

  notify:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/notify:latest
    container_name: notify
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8103:8103"
      - "9103:9103"
    networks:
      - bass

  im:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/im:latest
    container_name: im
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8104:8104"
      - "9104:9104"
    networks:
      - bass

  platform:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/platform:latest
    container_name: platform
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8201:8201"
      - "9201:9201"
    networks:
      - bass

  scheduler:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/scheduler:latest
    container_name: scheduler
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8203:8203"
      - "9203:9203"
    networks:
      - bass
