global:
  name: bass-consul
  datacenter: dc1
  image: hashicorp/consul:2.0.0
  acls:
    # 查看 token: kubectl get secret bass-consul-bootstrap-acl-token -n <namespace> -o jsonpath='{.data.token}' | base64 -d
    manageSystemACLs: true

server:
  replicas: 1
  bootstrapExpect: 1
  storage: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

ui:
  enabled: true
  # 通过 Ingress 暴露，不使用 NodePort

connectInject:
  enabled: false
