fullnameOverride: bass-postgresql

auth:
  enablePostgresUser: true
  existingSecret: bass-postgres-secret
  secretKeys:
    adminPasswordKey: password
  username: "admin"
  password: ""
  database: "bass"

primary:
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 2Gi
  # ClusterIP，仅集群内访问
readReplicas:
  replicaCount: 0

architecture: standalone
