fullnameOverride: bass-redis

architecture: standalone

auth:
  enabled: true
  existingSecret: bass-redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  # ClusterIP，仅集群内访问
replica:
  replicaCount: 0

sentinel:
  enabled: false
