fullnameOverride: bass-redis

image:
  registry: registry-1.docker.io
  repository: bitnami/redis
  tag: ""
  digest: sha256:08863c2c3f4e051fb6139b38fa223e9c13be5033326a59bead182860d899bf98

architecture: standalone

auth:
  enabled: true
  existingSecret: bass-redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  # 仅集群内访问
replica:
  replicaCount: 0

sentinel:
  enabled: false
