server:
  name: platform
  version: 1.0.0
  mode: ${SERVICE_MODE:dev}
http:
  network: tcp
  host: ${HTTP_HOST:0.0.0.0}
  port: ${HTTP_PORT:8201}
  timeout: 5s
grpc:
  network: tcp
  host: ${GRPC_HOST:0.0.0.0}
  port: ${GRPC_PORT:9201}
  timeout: 5s
consul:
  address: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}
  datacenter: dc1
  token: ${CONSUL_ACL_APP_TOKEN:token}
  dial_timeout: 5s
database:
  driver: postgres
  source: postgresql://${POSTGRES_USER:admin}:${POSTGRES_PASSWORD:123456}@${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bass}?sslmode=disable
  merge: true
  debug: false
  slow_sql_threshold: 1s
  sample_rate: 1
redis:
  addr: ${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:"123456"}
  dial_timeout: 5s
  db: 0
  read_timeout: 5s
  write_timeout: 5s
  pool_size: 150
  min_idle_conns: 30
  pool_timeout: 2s
  conn_max_idle_time: 600s
  conn_max_life_time: 1800s
nats:
  host: ${NATS_HOST:127.0.0.1}
  port: ${NATS_PORT:4222}
  user: ${NATS_USER:admin}
  password: ${NATS_PASSWORD:"123456"}
  name: nats-platform
  timeout: 5s
  max_reconnects: 10
  reconnect_wait: 2s
  ping_interval: 30s
  flusher_timeout: 5s
  enable_jet_stream: false
  stream_name: ""
  jet_stream_domain: ""
trace:
  enable_otel: false
  endpoint: ${OTEL_ENDPOINT:127.0.0.1:4317}
  insecure: true
  sampler: 1
observability:
  enable_metrics: true
platform:
  ip_data:
    enable: true
    ipv4_xdb_path: configs/ip2region/ipv4.xdb
    ipv6_xdb_path: configs/ip2region/ipv6.xdb
    cache_policy: vectorindex
    ipv4_source_url: https://github.com/lionsoul2014/ip2region/raw/refs/heads/master/data/ip2region_v4.xdb
    ipv6_source_url: https://github.com/lionsoul2014/ip2region/raw/refs/heads/master/data/ip2region_v6.xdb
  oss:
    provider: minio
    minio:
      endpoint: ${MINIO_HOST:s3.dev.bass.local}:${MINIO_PORT:80}
      access_key: ${MINIO_ROOT_USER:admin}
      secret_key: ${MINIO_ROOT_PASSWORD:changemechangeme}
      bucket: ${MINIO_BUCKET:bass-assets}
      use_ssl: false
      timeout: ${MINIO_TIMEOUT:30s}
    qiniu:
      access_key: ${QINIU_ACCESS_KEY:}
      secret_key: ${QINIU_SECRET_KEY:}
      bucket: ${QINIU_BUCKET:bass-test}
      timeout: 300s
      size_min: 0
      size_max: 20
      callback_url: ${QINIU_CALLBACK_URL:}
      increment_audit: false
      increment_audit_callback_url: ${QINIU_INCREMENT_AUDIT_CALLBACK_URL:}
