syntax = "proto3";

package common.api.app.connector.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";
import "signal/v1/model.proto";

option go_package = "common/api/gen/connector/v1;v1";

// 服务
service ConnectorCallbackService {
  // ping
  rpc Ping(PingConnector.Request) returns (PingConnector.Reply) {
    option (google.api.http) = {
      post: "/v1/connector/ping"
      body:"*"
    };
  }

  // 工作量证明
  rpc Pow(PowConnector.Request) returns (PowConnector.Reply) {
    option (google.api.http) = {
      post: "/v1/connector/pow"
      body: "*"
    };
  }

  // Session 会话
  rpc Session(SessionConnector.Request) returns (SessionConnector.Reply) {
    option (google.api.http) = {
      post: "/v1/connector/session"
      body:"*"
    };
  }

  // 发送消息
  rpc Send(SendConnector.Request) returns (SendConnector.Reply) {
    option (google.api.http) = {
      post: "/v1/connector/send"
      body: "*"
    };
  }
}

message PingConnector {
  message Request {}
  message Reply {}
}

message PowConnector {
  message Request {
    // 初始字符串
    string challenge = 1 [(validate.rules).string.min_len = 1];
    // 难度
    int32 difficulty = 2 [(validate.rules).int32.gt = 0];
  }
  message Reply {
    // 计算次数
    string nonce = 1;
    // 计算结果
    string hash_hex = 2;
  }
}

message SessionConnector {
  message Request {}
  message Reply {
    // 在线会话 id 列表
    repeated string session_ids = 1;
  }
}

message SendConnector {
  message Request {
    // 消息
    repeated signal.v1.Message messages = 1;
  }
  message Reply {}
}
