/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccountProfile
 */
export interface AccountProfile {
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountProfile
     */
    introduction?: string;
    /**
     * 
     * @type {AccountProfileMbtiEnum}
     * @memberof AccountProfile
     */
    mbti?: AccountProfileMbtiEnum;
    /**
     * 
     * @type {AccountProfileStatusEnum}
     * @memberof AccountProfile
     */
    status?: AccountProfileStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof AccountProfile
     */
    followCount?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountProfile
     */
    followerCount?: number;
    /**
     * 
     * @type {Date}
     * @memberof AccountProfile
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccountProfile
     */
    updatedAt?: Date;
}


/**
 * @export
 */
export const AccountProfileMbtiEnum = {
    MBTI_UNSPECIFIED: 'MBTI_UNSPECIFIED',
    MBTI_INTJ: 'MBTI_INTJ',
    MBTI_INTP: 'MBTI_INTP',
    MBTI_ENTJ: 'MBTI_ENTJ',
    MBTI_ENTP: 'MBTI_ENTP',
    MBTI_INFJ: 'MBTI_INFJ',
    MBTI_INFP: 'MBTI_INFP',
    MBTI_ENFJ: 'MBTI_ENFJ',
    MBTI_ENFP: 'MBTI_ENFP',
    MBTI_ISTJ: 'MBTI_ISTJ',
    MBTI_ISFJ: 'MBTI_ISFJ',
    MBTI_ESTJ: 'MBTI_ESTJ',
    MBTI_ESFJ: 'MBTI_ESFJ',
    MBTI_ISTP: 'MBTI_ISTP',
    MBTI_ISFP: 'MBTI_ISFP',
    MBTI_ESTP: 'MBTI_ESTP',
    MBTI_ESFP: 'MBTI_ESFP'
} as const;
export type AccountProfileMbtiEnum = typeof AccountProfileMbtiEnum[keyof typeof AccountProfileMbtiEnum];

/**
 * @export
 */
export const AccountProfileStatusEnum = {
    ACCOUNT_STATUS_UNSPECIFIED: 'ACCOUNT_STATUS_UNSPECIFIED',
    ACCOUNT_STATUS_NORMAL: 'ACCOUNT_STATUS_NORMAL',
    ACCOUNT_STATUS_BANNED: 'ACCOUNT_STATUS_BANNED',
    ACCOUNT_STATUS_CANCELLED: 'ACCOUNT_STATUS_CANCELLED'
} as const;
export type AccountProfileStatusEnum = typeof AccountProfileStatusEnum[keyof typeof AccountProfileStatusEnum];


/**
 * Check if a given object implements the AccountProfile interface.
 */
export function instanceOfAccountProfile(value: object): value is AccountProfile {
    return true;
}

export function AccountProfileFromJSON(json: any): AccountProfile {
    return AccountProfileFromJSONTyped(json, false);
}

export function AccountProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountProfile {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'url': json['url'] == null ? undefined : json['url'],
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'introduction': json['introduction'] == null ? undefined : json['introduction'],
        'mbti': json['mbti'] == null ? undefined : json['mbti'],
        'status': json['status'] == null ? undefined : json['status'],
        'followCount': json['follow_count'] == null ? undefined : json['follow_count'],
        'followerCount': json['follower_count'] == null ? undefined : json['follower_count'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function AccountProfileToJSON(json: any): AccountProfile {
    return AccountProfileToJSONTyped(json, false);
}

export function AccountProfileToJSONTyped(value?: AccountProfile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'nickname': value['nickname'],
        'url': value['url'],
        'avatar_url': value['avatarUrl'],
        'introduction': value['introduction'],
        'mbti': value['mbti'],
        'status': value['status'],
        'follow_count': value['followCount'],
        'follower_count': value['followerCount'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

