/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleViewerActionState } from './ArticleViewerActionState';
import {
    ArticleViewerActionStateFromJSON,
    ArticleViewerActionStateFromJSONTyped,
    ArticleViewerActionStateToJSON,
    ArticleViewerActionStateToJSONTyped,
} from './ArticleViewerActionState';
import type { AccountProfile } from './AccountProfile';
import {
    AccountProfileFromJSON,
    AccountProfileFromJSONTyped,
    AccountProfileToJSON,
    AccountProfileToJSONTyped,
} from './AccountProfile';

/**
 * 文章列表项。
 * @export
 * @interface ArticleListItem
 */
export interface ArticleListItem {
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    contentRender?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleListItem
     */
    hasPostscript?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleListItem
     */
    hasReward?: boolean;
    /**
     * 
     * @type {ArticleListItemTypeEnum}
     * @memberof ArticleListItem
     */
    type?: ArticleListItemTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    statement?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleListItem
     */
    commentable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ArticleListItem
     */
    anonymous?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    viewCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    thankCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    likeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    collectCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    watchCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    replyCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleListItem
     */
    bountyPoints?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    acceptedAnswerId?: string;
    /**
     * 
     * @type {AccountProfile}
     * @memberof ArticleListItem
     */
    authorUser?: AccountProfile;
    /**
     * 
     * @type {AccountProfile}
     * @memberof ArticleListItem
     */
    lastReplyUser?: AccountProfile;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    lastReplyAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    coverImageUrl?: string;
    /**
     * 
     * @type {ArticleViewerActionState}
     * @memberof ArticleListItem
     */
    viewerActionState?: ArticleViewerActionState;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    publishedAt?: string;
    /**
     * 
     * @type {ArticleListItemPublishStatusEnum}
     * @memberof ArticleListItem
     */
    publishStatus?: ArticleListItemPublishStatusEnum;
    /**
     * 
     * @type {ArticleListItemVisibilityEnum}
     * @memberof ArticleListItem
     */
    visibility?: ArticleListItemVisibilityEnum;
    /**
     * 
     * @type {ArticleListItemRestrictionEnum}
     * @memberof ArticleListItem
     */
    restriction?: ArticleListItemRestrictionEnum;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    editedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleListItem
     */
    updatedAt?: string;
}


/**
 * @export
 */
export const ArticleListItemTypeEnum = {
    ARTICLE_TYPE_UNSPECIFIED: 'ARTICLE_TYPE_UNSPECIFIED',
    ARTICLE_TYPE_NORMAL: 'ARTICLE_TYPE_NORMAL',
    ARTICLE_TYPE_QA: 'ARTICLE_TYPE_QA'
} as const;
export type ArticleListItemTypeEnum = typeof ArticleListItemTypeEnum[keyof typeof ArticleListItemTypeEnum];

/**
 * @export
 */
export const ArticleListItemPublishStatusEnum = {
    ARTICLE_PUBLISH_STATUS_UNSPECIFIED: 'ARTICLE_PUBLISH_STATUS_UNSPECIFIED',
    ARTICLE_PUBLISH_STATUS_DRAFT: 'ARTICLE_PUBLISH_STATUS_DRAFT',
    ARTICLE_PUBLISH_STATUS_PUBLISHED: 'ARTICLE_PUBLISH_STATUS_PUBLISHED',
    ARTICLE_PUBLISH_STATUS_ARCHIVED: 'ARTICLE_PUBLISH_STATUS_ARCHIVED'
} as const;
export type ArticleListItemPublishStatusEnum = typeof ArticleListItemPublishStatusEnum[keyof typeof ArticleListItemPublishStatusEnum];

/**
 * @export
 */
export const ArticleListItemVisibilityEnum = {
    ARTICLE_VISIBILITY_UNSPECIFIED: 'ARTICLE_VISIBILITY_UNSPECIFIED',
    ARTICLE_VISIBILITY_PUBLIC: 'ARTICLE_VISIBILITY_PUBLIC',
    ARTICLE_VISIBILITY_PRIVATE: 'ARTICLE_VISIBILITY_PRIVATE'
} as const;
export type ArticleListItemVisibilityEnum = typeof ArticleListItemVisibilityEnum[keyof typeof ArticleListItemVisibilityEnum];

/**
 * @export
 */
export const ArticleListItemRestrictionEnum = {
    CONTENT_RESTRICTION_UNSPECIFIED: 'CONTENT_RESTRICTION_UNSPECIFIED',
    CONTENT_RESTRICTION_NONE: 'CONTENT_RESTRICTION_NONE',
    CONTENT_RESTRICTION_HIDDEN: 'CONTENT_RESTRICTION_HIDDEN',
    CONTENT_RESTRICTION_LOCKED: 'CONTENT_RESTRICTION_LOCKED'
} as const;
export type ArticleListItemRestrictionEnum = typeof ArticleListItemRestrictionEnum[keyof typeof ArticleListItemRestrictionEnum];


/**
 * Check if a given object implements the ArticleListItem interface.
 */
export function instanceOfArticleListItem(value: object): value is ArticleListItem {
    return true;
}

export function ArticleListItemFromJSON(json: any): ArticleListItem {
    return ArticleListItemFromJSONTyped(json, false);
}

export function ArticleListItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleListItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'content': json['content'] == null ? undefined : json['content'],
        'contentRender': json['content_render'] == null ? undefined : json['content_render'],
        'hasPostscript': json['has_postscript'] == null ? undefined : json['has_postscript'],
        'hasReward': json['has_reward'] == null ? undefined : json['has_reward'],
        'type': json['type'] == null ? undefined : json['type'],
        'statement': json['statement'] == null ? undefined : json['statement'],
        'commentable': json['commentable'] == null ? undefined : json['commentable'],
        'anonymous': json['anonymous'] == null ? undefined : json['anonymous'],
        'viewCount': json['view_count'] == null ? undefined : json['view_count'],
        'thankCount': json['thank_count'] == null ? undefined : json['thank_count'],
        'likeCount': json['like_count'] == null ? undefined : json['like_count'],
        'collectCount': json['collect_count'] == null ? undefined : json['collect_count'],
        'watchCount': json['watch_count'] == null ? undefined : json['watch_count'],
        'replyCount': json['reply_count'] == null ? undefined : json['reply_count'],
        'bountyPoints': json['bounty_points'] == null ? undefined : json['bounty_points'],
        'acceptedAnswerId': json['accepted_answer_id'] == null ? undefined : json['accepted_answer_id'],
        'authorUser': json['author_user'] == null ? undefined : AccountProfileFromJSON(json['author_user']),
        'lastReplyUser': json['last_reply_user'] == null ? undefined : AccountProfileFromJSON(json['last_reply_user']),
        'lastReplyAt': json['last_reply_at'] == null ? undefined : json['last_reply_at'],
        'coverImageUrl': json['cover_image_url'] == null ? undefined : json['cover_image_url'],
        'viewerActionState': json['viewer_action_state'] == null ? undefined : ArticleViewerActionStateFromJSON(json['viewer_action_state']),
        'publishedAt': json['published_at'] == null ? undefined : json['published_at'],
        'publishStatus': json['publish_status'] == null ? undefined : json['publish_status'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
        'restriction': json['restriction'] == null ? undefined : json['restriction'],
        'editedAt': json['edited_at'] == null ? undefined : json['edited_at'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function ArticleListItemToJSON(json: any): ArticleListItem {
    return ArticleListItemToJSONTyped(json, false);
}

export function ArticleListItemToJSONTyped(value?: ArticleListItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'content': value['content'],
        'content_render': value['contentRender'],
        'has_postscript': value['hasPostscript'],
        'has_reward': value['hasReward'],
        'type': value['type'],
        'statement': value['statement'],
        'commentable': value['commentable'],
        'anonymous': value['anonymous'],
        'view_count': value['viewCount'],
        'thank_count': value['thankCount'],
        'like_count': value['likeCount'],
        'collect_count': value['collectCount'],
        'watch_count': value['watchCount'],
        'reply_count': value['replyCount'],
        'bounty_points': value['bountyPoints'],
        'accepted_answer_id': value['acceptedAnswerId'],
        'author_user': AccountProfileToJSON(value['authorUser']),
        'last_reply_user': AccountProfileToJSON(value['lastReplyUser']),
        'last_reply_at': value['lastReplyAt'],
        'cover_image_url': value['coverImageUrl'],
        'viewer_action_state': ArticleViewerActionStateToJSON(value['viewerActionState']),
        'published_at': value['publishedAt'],
        'publish_status': value['publishStatus'],
        'visibility': value['visibility'],
        'restriction': value['restriction'],
        'edited_at': value['editedAt'],
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

