/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonApiAppBbsV1UserFollowRelationRequest
 */
export interface CommonApiAppBbsV1UserFollowRelationRequest {
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserFollowRelationRequest
     */
    targetId?: string;
}

/**
 * Check if a given object implements the CommonApiAppBbsV1UserFollowRelationRequest interface.
 */
export function instanceOfCommonApiAppBbsV1UserFollowRelationRequest(value: object): value is CommonApiAppBbsV1UserFollowRelationRequest {
    return true;
}

export function CommonApiAppBbsV1UserFollowRelationRequestFromJSON(json: any): CommonApiAppBbsV1UserFollowRelationRequest {
    return CommonApiAppBbsV1UserFollowRelationRequestFromJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserFollowRelationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonApiAppBbsV1UserFollowRelationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetId': json['target_id'] == null ? undefined : json['target_id'],
    };
}

export function CommonApiAppBbsV1UserFollowRelationRequestToJSON(json: any): CommonApiAppBbsV1UserFollowRelationRequest {
    return CommonApiAppBbsV1UserFollowRelationRequestToJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserFollowRelationRequestToJSONTyped(value?: CommonApiAppBbsV1UserFollowRelationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_id': value['targetId'],
    };
}

