/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonApiAppBbsV1UserGetProfileAccountRequest
 */
export interface CommonApiAppBbsV1UserGetProfileAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserGetProfileAccountRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the CommonApiAppBbsV1UserGetProfileAccountRequest interface.
 */
export function instanceOfCommonApiAppBbsV1UserGetProfileAccountRequest(value: object): value is CommonApiAppBbsV1UserGetProfileAccountRequest {
    return true;
}

export function CommonApiAppBbsV1UserGetProfileAccountRequestFromJSON(json: any): CommonApiAppBbsV1UserGetProfileAccountRequest {
    return CommonApiAppBbsV1UserGetProfileAccountRequestFromJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserGetProfileAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonApiAppBbsV1UserGetProfileAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function CommonApiAppBbsV1UserGetProfileAccountRequestToJSON(json: any): CommonApiAppBbsV1UserGetProfileAccountRequest {
    return CommonApiAppBbsV1UserGetProfileAccountRequestToJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserGetProfileAccountRequestToJSONTyped(value?: CommonApiAppBbsV1UserGetProfileAccountRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

