/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 账号偏好设置
 * @export
 * @interface CommonApiAppBbsV1UserPreference
 */
export interface CommonApiAppBbsV1UserPreference {
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    language?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    timezone?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    theme?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    mobileTheme?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    enableWebNotify?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommonApiAppBbsV1UserPreference
     */
    enableEmailSubscribe?: boolean;
}

/**
 * Check if a given object implements the CommonApiAppBbsV1UserPreference interface.
 */
export function instanceOfCommonApiAppBbsV1UserPreference(value: object): value is CommonApiAppBbsV1UserPreference {
    return true;
}

export function CommonApiAppBbsV1UserPreferenceFromJSON(json: any): CommonApiAppBbsV1UserPreference {
    return CommonApiAppBbsV1UserPreferenceFromJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserPreferenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonApiAppBbsV1UserPreference {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'language': json['language'] == null ? undefined : json['language'],
        'timezone': json['timezone'] == null ? undefined : json['timezone'],
        'theme': json['theme'] == null ? undefined : json['theme'],
        'mobileTheme': json['mobile_theme'] == null ? undefined : json['mobile_theme'],
        'enableWebNotify': json['enable_web_notify'] == null ? undefined : json['enable_web_notify'],
        'enableEmailSubscribe': json['enable_email_subscribe'] == null ? undefined : json['enable_email_subscribe'],
    };
}

export function CommonApiAppBbsV1UserPreferenceToJSON(json: any): CommonApiAppBbsV1UserPreference {
    return CommonApiAppBbsV1UserPreferenceToJSONTyped(json, false);
}

export function CommonApiAppBbsV1UserPreferenceToJSONTyped(value?: CommonApiAppBbsV1UserPreference | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'language': value['language'],
        'timezone': value['timezone'],
        'theme': value['theme'],
        'mobile_theme': value['mobileTheme'],
        'enable_web_notify': value['enableWebNotify'],
        'enable_email_subscribe': value['enableEmailSubscribe'],
    };
}

