/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Comment : 评论。
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Comment {
    /// 评论 ID。
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// 文章 ID。
    #[serde(rename = "article_id", skip_serializing_if = "Option::is_none")]
    pub article_id: Option<String>,
    /// 原始内容。
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// 渲染后的内容。
    #[serde(rename = "content_render", skip_serializing_if = "Option::is_none")]
    pub content_render: Option<String>,
    /// 评论层级。
    #[serde(rename = "level", skip_serializing_if = "Option::is_none")]
    pub level: Option<i32>,
    /// 父评论 ID。
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    /// 回复的评论 ID。
    #[serde(rename = "reply_id", skip_serializing_if = "Option::is_none")]
    pub reply_id: Option<String>,
    /// 评论状态。
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// 回复数量。
    #[serde(rename = "reply_count", skip_serializing_if = "Option::is_none")]
    pub reply_count: Option<i32>,
    /// 点赞数量。
    #[serde(rename = "like_count", skip_serializing_if = "Option::is_none")]
    pub like_count: Option<i32>,
    /// 感谢数量。
    #[serde(rename = "thank_count", skip_serializing_if = "Option::is_none")]
    pub thank_count: Option<i32>,
    /// 评论账号展示资料。
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<models::AccountProfile>,
    /// 被回复账号展示资料。
    #[serde(rename = "reply_user", skip_serializing_if = "Option::is_none")]
    pub reply_user: Option<models::AccountProfile>,
    /// 所属文章。
    #[serde(rename = "article", skip_serializing_if = "Option::is_none")]
    pub article: Option<models::Article>,
    /// 创建账号 ID。
    #[serde(rename = "created_by", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// 更新账号 ID。
    #[serde(rename = "updated_by", skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<String>,
    /// 创建时间。
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// 更新时间。
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl Comment {
    /// 评论。
    pub fn new() -> Comment {
        Comment {
            id: None,
            article_id: None,
            content: None,
            content_render: None,
            level: None,
            parent_id: None,
            reply_id: None,
            status: None,
            reply_count: None,
            like_count: None,
            thank_count: None,
            user: None,
            reply_user: None,
            article: None,
            created_by: None,
            updated_by: None,
            created_at: None,
            updated_at: None,
        }
    }
}
/// 评论状态。
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "COMMENT_STATUS_UNSPECIFIED")]
    CommentStatusUnspecified,
    #[serde(rename = "COMMENT_STATUS_NORMAL")]
    CommentStatusNormal,
    #[serde(rename = "COMMENT_STATUS_HIDDEN")]
    CommentStatusHidden,
}

impl Default for Status {
    fn default() -> Status {
        Self::CommentStatusUnspecified
    }
}

