/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleBrief } from './ArticleBrief';
import {
    ArticleBriefFromJSON,
    ArticleBriefFromJSONTyped,
    ArticleBriefToJSON,
    ArticleBriefToJSONTyped,
} from './ArticleBrief';
import type { AccountProfile } from './AccountProfile';
import {
    AccountProfileFromJSON,
    AccountProfileFromJSONTyped,
    AccountProfileToJSON,
    AccountProfileToJSONTyped,
} from './AccountProfile';
import type { CommentViewerActionState } from './CommentViewerActionState';
import {
    CommentViewerActionStateFromJSON,
    CommentViewerActionStateFromJSONTyped,
    CommentViewerActionStateToJSON,
    CommentViewerActionStateToJSONTyped,
} from './CommentViewerActionState';

/**
 * 评论详情。
 * @export
 * @interface CommentDetail
 */
export interface CommentDetail {
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    articleId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    content?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    contentRender?: string;
    /**
     * 
     * @type {number}
     * @memberof CommentDetail
     */
    level?: number;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    parentId?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    replyId?: string;
    /**
     * 
     * @type {number}
     * @memberof CommentDetail
     */
    replyCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDetail
     */
    likeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CommentDetail
     */
    thankCount?: number;
    /**
     * 
     * @type {AccountProfile}
     * @memberof CommentDetail
     */
    user?: AccountProfile;
    /**
     * 
     * @type {AccountProfile}
     * @memberof CommentDetail
     */
    replyUser?: AccountProfile;
    /**
     * 
     * @type {ArticleBrief}
     * @memberof CommentDetail
     */
    article?: ArticleBrief;
    /**
     * 
     * @type {CommentViewerActionState}
     * @memberof CommentDetail
     */
    viewerActionState?: CommentViewerActionState;
    /**
     * 
     * @type {CommentDetailRestrictionEnum}
     * @memberof CommentDetail
     */
    restriction?: CommentDetailRestrictionEnum;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    deletedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    updatedBy?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof CommentDetail
     */
    updatedAt?: string;
}


/**
 * @export
 */
export const CommentDetailRestrictionEnum = {
    CONTENT_RESTRICTION_UNSPECIFIED: 'CONTENT_RESTRICTION_UNSPECIFIED',
    CONTENT_RESTRICTION_NONE: 'CONTENT_RESTRICTION_NONE',
    CONTENT_RESTRICTION_HIDDEN: 'CONTENT_RESTRICTION_HIDDEN',
    CONTENT_RESTRICTION_LOCKED: 'CONTENT_RESTRICTION_LOCKED'
} as const;
export type CommentDetailRestrictionEnum = typeof CommentDetailRestrictionEnum[keyof typeof CommentDetailRestrictionEnum];


/**
 * Check if a given object implements the CommentDetail interface.
 */
export function instanceOfCommentDetail(value: object): value is CommentDetail {
    return true;
}

export function CommentDetailFromJSON(json: any): CommentDetail {
    return CommentDetailFromJSONTyped(json, false);
}

export function CommentDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'articleId': json['article_id'] == null ? undefined : json['article_id'],
        'content': json['content'] == null ? undefined : json['content'],
        'contentRender': json['content_render'] == null ? undefined : json['content_render'],
        'level': json['level'] == null ? undefined : json['level'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'replyId': json['reply_id'] == null ? undefined : json['reply_id'],
        'replyCount': json['reply_count'] == null ? undefined : json['reply_count'],
        'likeCount': json['like_count'] == null ? undefined : json['like_count'],
        'thankCount': json['thank_count'] == null ? undefined : json['thank_count'],
        'user': json['user'] == null ? undefined : AccountProfileFromJSON(json['user']),
        'replyUser': json['reply_user'] == null ? undefined : AccountProfileFromJSON(json['reply_user']),
        'article': json['article'] == null ? undefined : ArticleBriefFromJSON(json['article']),
        'viewerActionState': json['viewer_action_state'] == null ? undefined : CommentViewerActionStateFromJSON(json['viewer_action_state']),
        'restriction': json['restriction'] == null ? undefined : json['restriction'],
        'deletedAt': json['deleted_at'] == null ? undefined : json['deleted_at'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
    };
}

export function CommentDetailToJSON(json: any): CommentDetail {
    return CommentDetailToJSONTyped(json, false);
}

export function CommentDetailToJSONTyped(value?: CommentDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'article_id': value['articleId'],
        'content': value['content'],
        'content_render': value['contentRender'],
        'level': value['level'],
        'parent_id': value['parentId'],
        'reply_id': value['replyId'],
        'reply_count': value['replyCount'],
        'like_count': value['likeCount'],
        'thank_count': value['thankCount'],
        'user': AccountProfileToJSON(value['user']),
        'reply_user': AccountProfileToJSON(value['replyUser']),
        'article': ArticleBriefToJSON(value['article']),
        'viewer_action_state': CommentViewerActionStateToJSON(value['viewerActionState']),
        'restriction': value['restriction'],
        'deleted_at': value['deletedAt'],
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'created_at': value['createdAt'],
        'updated_at': value['updatedAt'],
    };
}

