/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleDetail } from './ArticleDetail';
import {
    ArticleDetailFromJSON,
    ArticleDetailFromJSONTyped,
    ArticleDetailToJSON,
    ArticleDetailToJSONTyped,
} from './ArticleDetail';

/**
 * 
 * @export
 * @interface CreateArticleReply
 */
export interface CreateArticleReply {
    /**
     * 
     * @type {ArticleDetail}
     * @memberof CreateArticleReply
     */
    article?: ArticleDetail;
}

/**
 * Check if a given object implements the CreateArticleReply interface.
 */
export function instanceOfCreateArticleReply(value: object): value is CreateArticleReply {
    return true;
}

export function CreateArticleReplyFromJSON(json: any): CreateArticleReply {
    return CreateArticleReplyFromJSONTyped(json, false);
}

export function CreateArticleReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateArticleReply {
    if (json == null) {
        return json;
    }
    return {
        
        'article': json['article'] == null ? undefined : ArticleDetailFromJSON(json['article']),
    };
}

export function CreateArticleReplyToJSON(json: any): CreateArticleReply {
    return CreateArticleReplyToJSONTyped(json, false);
}

export function CreateArticleReplyToJSONTyped(value?: CreateArticleReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ArticleDetailToJSON(value['article']),
    };
}

