/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentRequest
 */
export interface CreateCommentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    articleId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentRequest
     */
    replyId?: string;
}

/**
 * Check if a given object implements the CreateCommentRequest interface.
 */
export function instanceOfCreateCommentRequest(value: object): value is CreateCommentRequest {
    if (!('articleId' in value) || value['articleId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateCommentRequestFromJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestFromJSONTyped(json, false);
}

export function CreateCommentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'],
        'content': json['content'],
        'replyId': json['reply_id'] == null ? undefined : json['reply_id'],
    };
}

export function CreateCommentRequestToJSON(json: any): CreateCommentRequest {
    return CreateCommentRequestToJSONTyped(json, false);
}

export function CreateCommentRequestToJSONTyped(value?: CreateCommentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article_id': value['articleId'],
        'content': value['content'],
        'reply_id': value['replyId'],
    };
}

