/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RespDomain } from './RespDomain';
import {
    RespDomainFromJSON,
    RespDomainFromJSONTyped,
    RespDomainToJSON,
    RespDomainToJSONTyped,
} from './RespDomain';

/**
 * 
 * @export
 * @interface CreateDomainResp
 */
export interface CreateDomainResp {
    /**
     * 
     * @type {RespDomain}
     * @memberof CreateDomainResp
     */
    domain?: RespDomain;
}

/**
 * Check if a given object implements the CreateDomainResp interface.
 */
export function instanceOfCreateDomainResp(value: object): value is CreateDomainResp {
    return true;
}

export function CreateDomainRespFromJSON(json: any): CreateDomainResp {
    return CreateDomainRespFromJSONTyped(json, false);
}

export function CreateDomainRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateDomainResp {
    if (json == null) {
        return json;
    }
    return {
        
        'domain': json['domain'] == null ? undefined : RespDomainFromJSON(json['domain']),
    };
}

export function CreateDomainRespToJSON(json: any): CreateDomainResp {
    return CreateDomainRespToJSONTyped(json, false);
}

export function CreateDomainRespToJSONTyped(value?: CreateDomainResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'domain': RespDomainToJSON(value['domain']),
    };
}

