/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCurrentTotpReply {
    /// TOTP 认证状态。
    #[serde(rename = "totp", skip_serializing_if = "Option::is_none")]
    pub totp: Option<models::Totp>,
}

impl GetCurrentTotpReply {
    pub fn new() -> GetCurrentTotpReply {
        GetCurrentTotpReply {
            totp: None,
        }
    }
}

