/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCurrentPrivacySettingResp {
    #[serde(rename = "privacy_setting", skip_serializing_if = "Option::is_none")]
    pub privacy_setting: Option<models::RespPrivacySetting>,
}

impl GetCurrentPrivacySettingResp {
    pub fn new() -> GetCurrentPrivacySettingResp {
        GetCurrentPrivacySettingResp {
            privacy_setting: None,
        }
    }
}

