/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PageReply
 */
export interface PageReply {
    /**
     * 总数
     * @type {number}
     * @memberof PageReply
     */
    total?: number;
    /**
     * 页码
     * @type {number}
     * @memberof PageReply
     */
    page?: number;
    /**
     * 页大小
     * @type {number}
     * @memberof PageReply
     */
    size?: number;
}

/**
 * Check if a given object implements the PageReply interface.
 */
export function instanceOfPageReply(value: object): value is PageReply {
    return true;
}

export function PageReplyFromJSON(json: any): PageReply {
    return PageReplyFromJSONTyped(json, false);
}

export function PageReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageReply {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'page': json['page'] == null ? undefined : json['page'],
        'size': json['size'] == null ? undefined : json['size'],
    };
}

export function PageReplyToJSON(json: any): PageReply {
    return PageReplyToJSONTyped(json, false);
}

export function PageReplyToJSONTyped(value?: PageReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'page': value['page'],
        'size': value['size'],
    };
}

