/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 账号隐私设置。
 * @export
 * @interface PrivacySetting
 */
export interface PrivacySetting {
    /**
     * 账号 ID。
     * @type {string}
     * @memberof PrivacySetting
     */
    userId?: string;
    /**
     * 是否公开积分。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicPoints?: boolean;
    /**
     * 是否公开粉丝列表。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicFollowers?: boolean;
    /**
     * 是否公开文章列表。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicArticles?: boolean;
    /**
     * 是否公开评论列表。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicComments?: boolean;
    /**
     * 是否公开在线状态。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicOnlineStatus?: boolean;
    /**
     * 是否公开地理资料。
     * @type {boolean}
     * @memberof PrivacySetting
     */
    publicLocation?: boolean;
}

/**
 * Check if a given object implements the PrivacySetting interface.
 */
export function instanceOfPrivacySetting(value: object): value is PrivacySetting {
    return true;
}

export function PrivacySettingFromJSON(json: any): PrivacySetting {
    return PrivacySettingFromJSONTyped(json, false);
}

export function PrivacySettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivacySetting {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'publicPoints': json['public_points'] == null ? undefined : json['public_points'],
        'publicFollowers': json['public_followers'] == null ? undefined : json['public_followers'],
        'publicArticles': json['public_articles'] == null ? undefined : json['public_articles'],
        'publicComments': json['public_comments'] == null ? undefined : json['public_comments'],
        'publicOnlineStatus': json['public_online_status'] == null ? undefined : json['public_online_status'],
        'publicLocation': json['public_location'] == null ? undefined : json['public_location'],
    };
}

export function PrivacySettingToJSON(json: any): PrivacySetting {
    return PrivacySettingToJSONTyped(json, false);
}

export function PrivacySettingToJSONTyped(value?: PrivacySetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'public_points': value['publicPoints'],
        'public_followers': value['publicFollowers'],
        'public_articles': value['publicArticles'],
        'public_comments': value['publicComments'],
        'public_online_status': value['publicOnlineStatus'],
        'public_location': value['publicLocation'],
    };
}

