/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDraftArticleRequest {
    /// 文章保存内容。
    #[serde(rename = "article")]
    pub article: models::ArticleSave,
}

impl UpdateDraftArticleRequest {
    pub fn new(article: models::ArticleSave) -> UpdateDraftArticleRequest {
        UpdateDraftArticleRequest {
            article,
        }
    }
}

