/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateArticleRequest {
    #[serde(rename = "article_id")]
    pub article_id: String,
    #[serde(rename = "article")]
    pub article: models::RequestArticle,
}

impl UpdateArticleRequest {
    pub fn new(article_id: String, article: models::RequestArticle) -> UpdateArticleRequest {
        UpdateArticleRequest {
            article_id,
            article,
        }
    }
}

