/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpsertCurrentLocationRequest {
    /// 国家或地区。
    #[serde(rename = "country", skip_serializing_if = "Option::is_none")]
    pub country: Option<String>,
    /// 省份或州。
    #[serde(rename = "province", skip_serializing_if = "Option::is_none")]
    pub province: Option<String>,
    /// 城市。
    #[serde(rename = "city", skip_serializing_if = "Option::is_none")]
    pub city: Option<String>,
}

impl UpsertCurrentLocationRequest {
    pub fn new() -> UpsertCurrentLocationRequest {
        UpsertCurrentLocationRequest {
            country: None,
            province: None,
            city: None,
        }
    }
}

