/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertCurrentLocationRequest
 */
export interface UpsertCurrentLocationRequest {
    /**
     * 国家或地区。
     * @type {string}
     * @memberof UpsertCurrentLocationRequest
     */
    country?: string;
    /**
     * 省份或州。
     * @type {string}
     * @memberof UpsertCurrentLocationRequest
     */
    province?: string;
    /**
     * 城市。
     * @type {string}
     * @memberof UpsertCurrentLocationRequest
     */
    city?: string;
}

/**
 * Check if a given object implements the UpsertCurrentLocationRequest interface.
 */
export function instanceOfUpsertCurrentLocationRequest(value: object): value is UpsertCurrentLocationRequest {
    return true;
}

export function UpsertCurrentLocationRequestFromJSON(json: any): UpsertCurrentLocationRequest {
    return UpsertCurrentLocationRequestFromJSONTyped(json, false);
}

export function UpsertCurrentLocationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertCurrentLocationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'province': json['province'] == null ? undefined : json['province'],
        'city': json['city'] == null ? undefined : json['city'],
    };
}

export function UpsertCurrentLocationRequestToJSON(json: any): UpsertCurrentLocationRequest {
    return UpsertCurrentLocationRequestToJSONTyped(json, false);
}

export function UpsertCurrentLocationRequestToJSONTyped(value?: UpsertCurrentLocationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'province': value['province'],
        'city': value['city'],
    };
}

