server:
  app: FishPi
  name: user-service
  version: 1.0.0
  mode: dev
  http:
    addr: 0.0.0.0:8001
    timeout: 5s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 5s
data:
  database:
    driver: "postgres"
    source: "postgresql://bass:123456@127.0.0.1:5432/bass?sslmode=disable" # postgresql://<user>:<pass>@<host>/<database>
    merge: true # 是否同步表到数据库
  redis:
    addr: 127.0.0.1:6379
    password: "123456"
    db: 0
    read_timeout: 1s
    write_timeout: 1s
  rabbitmq:
    url: "amqp://admin:123456@127.0.0.1:5672/dev_vhost"
    heartbeat: 10s            # 心跳，秒
    dial_timeout: 5s          # 连接超时，秒
    prefetch_count: 10        # Qos，未确认消息最大数量
    prefetch_global: false    # Qos 是否全局
    delivery_mode: 2          # 消息持久化 1: transient, 2: persistent
    auto_ack: false           # 是否自动确认消息


registry:
  etcd:
    endpoints:
      - 127.0.0.1:2379
    username: "root"
    password: "123456"
    timeout: 5s

trace:
  enable_otel: false # 是否采集上报到 otel
  endpoint: "127.0.0.1:4317"  # OTel Collector 地址
  insecure: true
  sampler: 1  # 100% 采样率

jwt:
  secret: "qbceKQYgXXffTxVBgGrX"
  expires: 864000s
  email_expire: 300s

oss:
  local:
    avatar: "https://treble.sxisa.com/v1/user/avatar/%s" # /v1/user/avatar/{name}
  qiniu:
    access_key: "L8l6DGiYXzmx0IVT0GpIxI-Mj8LqfoIKF6iAnrWa"
    secret_key: "qY6ohp-qZEtd20NZN94o7TScg3IeEGSZe-ZRsVXW"
    bucket: "bass-test"
    timeout: 300s
