version: '3.9'

services:
  postgres:
    image: postgres:18.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker-data/postgres:/var/lib/postgresql/18/data

  redis:
    image: redis:8.2.2
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - /opt/docker-data/redis:/data

  etcd:
    image: bitnami/etcd:3.6.5
    container_name: etcd
    restart: always
    environment:
      - ETCD_ROOT_PASSWORD=123456
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=no
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - /opt/docker-data/etcd:/bitnami/etcd

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: admin_vhost
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"   # AMQP 接口
      - "15672:15672" # Web 管理界面
    volumes:
      - /opt/docker-data/rabbitmq:/var/lib/rabbitmq