version: '3.9'

name: bass-application

networks:
  microservice:
    driver: bridge

services:
  treble:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/treble:latest
    container_name: treble-service
    restart: always
    env_file:
      - .env
    ports:
      - "2324:2324"
    networks:
      - microservice

  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/gateway:latest
    container_name: gateway-service
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - microservice

  infra:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/infra:latest
    container_name: infra-service
    restart: always
    ports:
      - "8001:8000"
      - "9001:9000"
    networks:
      - microservice

  user:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/user:latest
    container_name: user-service
    restart: always
    ports:
      - "8002:8000"
      - "9002:9000"
    networks:
      - microservice

  content:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/content:latest
    container_name: content-service
    restart: always
    ports:
      - "8003:8000"
      - "9003:9000"
    networks:
      - microservice

  notify:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/notify:latest
    container_name: notify-service
    restart: always
    ports:
      - "8004:8000"
      - "9004:9000"
    networks:
      - microservice

  im:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/im:latest
    container_name: im-service
    restart: always
    ports:
      - "8005:8000"
      - "9005:9000"
    networks:
      - microservice

  signal:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/signal:latest
    container_name: signal-service
    restart: always
    ports:
      - "8006:8000"
      - "9006:9000"
    networks:
      - microservice

  connector:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/connector:latest
    container_name: connector-service
    restart: always
    ports:
      - "8007:8000"
      - "9007:9000"
    networks:
      - microservice
