syntax = "proto3";

package common.api.app.notify.v1;

option go_package = "common/proto/gen/notify/v1/enum;enum";

enum NotificationChannelStatus {
  NOTIFICATION_CHANNEL_STATUS_UNSPECIFIED = 0; // 未指定
  NOTIFICATION_CHANNEL_STATUS_PROCESSING = 1; // 正在处理
  NOTIFICATION_CHANNEL_STATUS_SUCCEEDED = 2; // 已成功
  NOTIFICATION_CHANNEL_STATUS_SKIPPED = 3; // 已跳过
  NOTIFICATION_CHANNEL_STATUS_FAILED = 4; // 明确失败
  NOTIFICATION_CHANNEL_STATUS_UNKNOWN = 5; // 结果不确定
  NOTIFICATION_CHANNEL_STATUS_INTERNAL_ERROR = 6; // 内部错误
  NOTIFICATION_CHANNEL_STATUS_RATE_LIMITED = 7; // 已被限流
}
