fullnameOverride: bass-nats

config:
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      dir: /data
      pvc:
        enabled: true
        size: 5Gi
    merge:
      max_memory_store: 1G
      max_file_store: 10G
  monitor:
    enabled: true
    port: 8222
  merge:
    authorization:
      users:
        - user: << $NATS_USER >>
          password: << $NATS_PASSWORD >>

statefulSet:
  replicas: 1

promExporter:
  enabled: false

service:
  # 仅集群内访问。
  enabled: true
  ports:
    monitor:
      enabled: true

container:
  image:
    repository: nats
    tag: 2.14.2
  env:
    NATS_USER:
      valueFrom:
        secretKeyRef:
          name: bass-nats-secret
          key: NATS_USER
    NATS_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: bass-nats-secret
          key: NATS_PASSWORD
  merge:
    resources:
      requests:
        cpu: "100m"
        memory: 128Mi
      limits:
        cpu: "200m"
        memory: 256Mi

natsBox:
  enabled: true
  merge:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
