syntax = "proto3";

package common.api.app.scheduler.v1;

option go_package = "common/proto/gen/scheduler/v1/enum;enum";

enum SchedulerTaskExecutionStatus {
  SCHEDULER_TASK_EXECUTION_STATUS_UNSPECIFIED = 0; // 未指定。
  SCHEDULER_TASK_EXECUTION_STATUS_PENDING = 1; // 等待执行。
  SCHEDULER_TASK_EXECUTION_STATUS_RUNNING = 2; // 正在运行。
  SCHEDULER_TASK_EXECUTION_STATUS_SUCCESS = 3; // 执行成功。
  SCHEDULER_TASK_EXECUTION_STATUS_FAILED = 4; // 执行失败且不再重试。
  SCHEDULER_TASK_EXECUTION_STATUS_TIMEOUT = 5; // 执行超时且不再重试。
  SCHEDULER_TASK_EXECUTION_STATUS_CANCELED = 6; // 已取消。
  SCHEDULER_TASK_EXECUTION_STATUS_SKIPPED = 7; // 已跳过。
  SCHEDULER_TASK_EXECUTION_STATUS_RETRY_PENDING = 8; // 等待重试。
}
