syntax = "proto3";

package common.api.app.scheduler.v1;

option go_package = "common/proto/gen/scheduler/v1/enum;enum";

enum SchedulerTaskKey {
  SCHEDULER_TASK_KEY_UNSPECIFIED = 0; // 未指定。
  SCHEDULER_TASK_KEY_NOOP_SCHEDULED_DEFAULT = 1; // 默认 noop 定时任务。
  SCHEDULER_TASK_KEY_NOOP_DELAYED_DEFAULT = 2; // 默认 noop 延迟任务。
  SCHEDULER_TASK_KEY_USER_OUTBOX_PUBLISH_BATCH_DEFAULT = 3; // 用户 Outbox 默认定时补漏任务。
  SCHEDULER_TASK_KEY_USER_OUTBOX_PUBLISH_BATCH_DELAYED_DEFAULT = 4; // 用户 Outbox 默认延迟补漏任务。
  SCHEDULER_TASK_KEY_USER_UNBAN_ACCOUNTS_DEFAULT = 5; // 用户默认批量解封任务。
  SCHEDULER_TASK_KEY_CONTENT_OUTBOX_PUBLISH_BATCH_DEFAULT = 6; // 内容 Outbox 默认定时补漏任务。
  SCHEDULER_TASK_KEY_CONTENT_OUTBOX_PUBLISH_BATCH_DELAYED_DEFAULT = 7; // 内容 Outbox 默认延迟补漏任务。
}
