syntax = "proto3";

package common.api.app.scheduler.v1;

option go_package = "common/proto/gen/scheduler/v1/enum;enum";

enum SchedulerTaskKey {
  SCHEDULER_TASK_KEY_UNSPECIFIED = 0; // 未指定

  // 公共任务 10000-10999
  SCHEDULER_TASK_KEY_NOOP_SCHEDULED_DEFAULT = 10000; // 默认 noop 定时任务
  SCHEDULER_TASK_KEY_NOOP_DELAYED_DEFAULT = 10001; // 默认 noop 延迟任务

  // user 任务 11000-11999
  SCHEDULER_TASK_KEY_USER_OUTBOX_PUBLISH_BATCH_DEFAULT = 11000; // 用户 Outbox 默认定时补漏任务
  SCHEDULER_TASK_KEY_USER_OUTBOX_PUBLISH_BATCH_DELAYED_DEFAULT = 11001; // 用户 Outbox 默认延迟补漏任务
  SCHEDULER_TASK_KEY_USER_UNBAN_ACCOUNTS_DEFAULT = 11002; // 用户默认批量解封任务

  // content 任务 12000-12999
  SCHEDULER_TASK_KEY_CONTENT_OUTBOX_PUBLISH_BATCH_DEFAULT = 12000; // 内容 Outbox 默认定时补漏任务
  SCHEDULER_TASK_KEY_CONTENT_OUTBOX_PUBLISH_BATCH_DELAYED_DEFAULT = 12001; // 内容 Outbox 默认延迟补漏任务
  SCHEDULER_TASK_KEY_CONTENT_PUBLISH_SCHEDULED_ARTICLES_DEFAULT = 12002; // 内容默认发布到期定时文章任务
  SCHEDULER_TASK_KEY_CONTENT_FLUSH_ARTICLE_VIEWS_DEFAULT = 12003; // 内容默认刷新文章浏览量任务
}
