syntax = "proto3";

package common.api.app.scheduler.v1;

option go_package = "common/proto/gen/scheduler/v1/enum;enum";

enum SchedulerTaskHandlerName {
  SCHEDULER_TASK_HANDLER_NAME_UNSPECIFIED = 0; // 未指定

  // 公共任务 10000-10999
  SCHEDULER_TASK_HANDLER_NAME_NOOP = 10000; // 空任务

  // user 任务 11000-11999
  SCHEDULER_TASK_HANDLER_NAME_USER_OUTBOX_PUBLISH_BATCH = 11000; // 用户 Outbox 批量投递
  SCHEDULER_TASK_HANDLER_NAME_USER_UNBAN_ACCOUNTS = 11001; // 用户批量解封

  // content 任务 12000-12999
  SCHEDULER_TASK_HANDLER_NAME_CONTENT_OUTBOX_PUBLISH_BATCH = 12000; // 内容 Outbox 批量投递
  SCHEDULER_TASK_HANDLER_NAME_CONTENT_PUBLISH_SCHEDULED_ARTICLES = 12001; // 发布到期定时文章
  SCHEDULER_TASK_HANDLER_NAME_CONTENT_FLUSH_ARTICLE_VIEWS = 12002; // 刷新文章浏览量
}
