syntax = "proto3";

package common.api.app.bbs.v1.notify;

import "bbs/v1/notify/model.proto";
import "common/enums/event.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/notify;notify";

service NotificationSettingService {
  rpc ListCurrent(ListCurrentNotificationSetting.Request) returns (ListCurrentNotificationSetting.Reply) {
    option (google.api.http) = {
      post: "/v1/notify/setting/list-current"
      body: "*"
    };
  }
  rpc UpdateCurrent(UpdateCurrentNotificationSetting.Request) returns (UpdateCurrentNotificationSetting.Reply) {
    option (google.api.http) = {
      post: "/v1/notify/setting/update-current"
      body: "*"
    };
  }
}

message ListCurrentNotificationSetting {
  message Request {
    NotificationSettingQuery query = 1;
  }
  message Reply {
    repeated NotificationSetting rows = 1;
  }
}

message UpdateCurrentNotificationSetting {
  message Request {
    common.enums.EventType event_type = 1;
    NotificationChannel channel = 2;
    bool enable = 3;
  }
  message Reply {
    NotificationSetting notification_setting = 1;
  }
}
