/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import com.bass.bbs.model.ArticlePostscript;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AddPostscriptReply
 */
class AddPostscriptReplyTest {
    private final AddPostscriptReply model = new AddPostscriptReply();

    /**
     * Model tests for AddPostscriptReply
     */
    @Test
    void testAddPostscriptReply() {
        // TODO: test AddPostscriptReply
    }

    /**
     * Test the property 'postscript'
     */
    @Test
    void postscriptTest() {
        // TODO: test postscript
    }

}
