/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import com.bass.bbs.model.ReqArticle;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateDraftArticleReq
 */
class CreateDraftArticleReqTest {
    private final CreateDraftArticleReq model = new CreateDraftArticleReq();

    /**
     * Model tests for CreateDraftArticleReq
     */
    @Test
    void testCreateDraftArticleReq() {
        // TODO: test CreateDraftArticleReq
    }

    /**
     * Test the property 'article'
     */
    @Test
    void articleTest() {
        // TODO: test article
    }

}
