/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import com.bass.bbs.model.RespAccount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GetCurrentAccountResp
 */
class GetCurrentAccountRespTest {
    private final GetCurrentAccountResp model = new GetCurrentAccountResp();

    /**
     * Model tests for GetCurrentAccountResp
     */
    @Test
    void testGetCurrentAccountResp() {
        // TODO: test GetCurrentAccountResp
    }

    /**
     * Test the property 'account'
     */
    @Test
    void accountTest() {
        // TODO: test account
    }

}
