syntax = "proto3";

package common.api.app.bbs.v1.content;

import "bbs/v1/content/article.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

option go_package = "common/proto/gen/bbs/v1/content;content";

// PostscriptService 提供 BBS 文章附言接口。
service PostscriptService {
  // 添加文章附言。
  rpc Add(AddPostscript.Req) returns (AddPostscript.Resp) {
    option (google.api.http) = {
      post: "/v1/content/postscript/add"
      body: "*"
    };
  }

  // 查询文章附言列表。
  rpc List(ListPostscripts.Req) returns (ListPostscripts.Resp) {
    option (google.api.http) = {
      post: "/v1/content/postscript/list"
      body: "*"
    };
  }
}

message AddPostscript {
  message Req {
    int64 article_id = 1; // 必填，文章 ID。
    string content = 2; // 必填，附言内容。
    option (gnostic.openapi.v3.schema) = {
      required: "article_id"
      required: "content"
    };
  }
  message Resp {
    ArticlePostscript postscript = 1; // 创建后的文章附言。
  }
}

message ListPostscripts {
  message Req {
    int64 article_id = 1; // 必填，文章 ID。
    option (gnostic.openapi.v3.schema) = {
      required: "article_id"
    };
  }
  message Resp {
    repeated ArticlePostscript rows = 1; // 文章附言列表。
  }
}
