syntax = "proto3";

package common.api.app.push_hub.v1;

import "google/protobuf/timestamp.proto";
import "push_hub/v1/enum.proto";

option go_package = "common/proto/gen/push_hub/v1;v1";

// 推送事件
message PushEvent {
  int64 id = 1;
  PushEventType type = 2;
  int64 user_id = 3;
  string payload = 4;
  google.protobuf.Timestamp created_at = 1000;
}

// 节点信息
message NodeInfo {
  string node_id = 1;
  string address = 2;
  int64 connection_count = 3;
  NodeStatus status = 4;
  google.protobuf.Timestamp registered_at = 1000;
  google.protobuf.Timestamp last_heartbeat_at = 1001;
}
