syntax = "proto3";

package common.api.app.common.enums;

option go_package = "common/api/gen/common/enums;enums";

// ==================== user ====================

message UserRegisterPayload {
  int64 user_id = 1;
}

message UserLoginPayload {
  int64 user_id = 1;
  string name = 2;
  string account = 3;
  string ip = 4;
  string user_agent = 5;
  string device_id = 6;
  string platform = 7;
  string request_id = 8;
}

message UserLogoutPayload {
  int64 user_id = 1;
  string name = 2;
}

message UserFollowPayload {
  int64 sender_id = 1;
  int64 followed_id = 3;
}

message UserUnfollowPayload {
  int64 sender_id = 1;
  int64 followed_id = 3;
}

message UserBlockPayload {
  int64 sender_id = 1;
  int64 blocked_id = 3;
}

message UserUnblockPayload {
  int64 sender_id = 1;
  int64 unblocked_id = 3;
}

message UserTfaEnablePayload {
  int64 user_id = 1;
}

message UserTfaDisablePayload {
  int64 user_id = 1;
}

// ==================== article ====================

message ArticlePublishedPayload {
  int64 article_id = 3;
}

message ArticleLikedPayload {
  int64 sender_id = 1;
  int64 article_id = 3;
}

message ArticleThankedPayload {
  int64 sender_id = 1;
  int64 article_id = 3;
}

message ArticleCollectedPayload {
  int64 sender_id = 1;
  int64 article_id = 3;
}

message ArticleWatchedPayload {
  int64 sender_id = 1;
  int64 article_id = 3;
}

// ==================== comment ====================

message CommentPublishedPayload {
  int64 comment_id = 3;
}

message CommentLikedPayload {
  int64 sender_id = 1;
  int64 comment_id = 3;
}
