syntax = "proto3";

package common.api.app.game_idle.v1;

import "google/protobuf/timestamp.proto";

option go_package = "common/proto/gen/game_idle/v1;v1";

service ActionQueueService {
  rpc List(ListActionQueue.Request) returns (ListActionQueue.Resp) {}
  rpc Add(AddAction.Request) returns (AddAction.Resp) {}
  rpc Move(MoveAction.Request) returns (MoveAction.Resp) {}
  rpc Remove(RemoveAction.Request) returns (RemoveAction.Resp) {}
  rpc Clear(ClearActionQueue.Request) returns (ClearActionQueue.Resp) {}
}

message ListActionQueue {
  message Request {
    int64 character_id = 1; // 角色 ID
  }

  message Resp {
    ActionQueue queue = 1; // 行动队列
  }
}

message AddAction {
  message Request {
    int64 character_id = 1; // 角色 ID
    string action_id = 2; // 行动编码
    int64 times = 3; // 执行次数，-1 表示无限
    optional int32 position = 4; // 插入位置，从 0 开始；空值表示追加到队尾
  }

  message Resp {}
}

message MoveAction {
  message Request {
    int64 character_id = 1; // 角色 ID
    int32 current_position = 2; // 当前位置，从 0 开始
    int32 target_position = 3; // 目标位置，从 0 开始
  }

  message Resp {}
}

message RemoveAction {
  message Request {
    int64 character_id = 1; // 角色 ID
    int32 position = 2; // 移除位置，从 0 开始
  }

  message Resp {}
}

message ClearActionQueue {
  message Request {
    int64 character_id = 1; // 角色 ID
  }

  message Resp {}
}

message ActionQueue {
  int64 character_id = 1; // 角色 ID
  repeated ActionQueueItem items = 2; // 有序行动列表
}

message ActionQueueItem {
  string action_id = 1; // 行动编码
  int64 times = 2; // 剩余执行次数
  google.protobuf.Timestamp created_at = 3; // 创建时间
}
