syntax = "proto3";

package common.api.app.game_idle.v1;

import "game_idle/v1/enum/character.proto";
import "google/protobuf/timestamp.proto";

option go_package = "common/proto/gen/game_idle/v1;v1";

service GameIdleCharacterService {
  rpc Create(CreateGameIdleCharacter.Request) returns (CreateGameIdleCharacter.Resp) {}
  rpc Get(GetGameIdleCharacter.Request) returns (GetGameIdleCharacter.Resp) {}
}

message CreateGameIdleCharacter {
  message Request {
    int64 user_id = 1; // 用户 ID
    string name = 2; // 角色名称
  }

  message Resp {
    Character row = 1; // 角色
  }
}

message GetGameIdleCharacter {
  message Request {
    int64 user_id = 1; // 用户 ID
  }

  message Resp {
    repeated Character rows = 1; // 角色列表
  }
}

message Character {
  int64 id = 1; // 角色 ID
  int64 user_id = 2; // 用户 ID
  string name = 3; // 角色名称
  common.api.app.game_idle.v1.enum.GameIdleCharacterStatus status = 4; // 角色状态
  int32 slot = 5; // 角色槽位
  int32 action_queue_capacity = 6; // 行动队列容量上限
  int64 max_offline_seconds = 7; // 最大离线收益结算秒数
  google.protobuf.Timestamp created_at = 1000; // 创建时间
  google.protobuf.Timestamp updated_at = 1001; // 更新时间
}
