/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
)


type AuthServiceAPI interface {

	/*
	AuthServiceLoginPassword Method for AuthServiceLoginPassword

	使用密码登录账号

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceLoginPasswordRequest
	*/
	AuthServiceLoginPassword(ctx context.Context) ApiAuthServiceLoginPasswordRequest

	// AuthServiceLoginPasswordExecute executes the request
	//  @return CommonApiAppBbsV1UserLoginPasswordReply
	AuthServiceLoginPasswordExecute(r ApiAuthServiceLoginPasswordRequest) (*CommonApiAppBbsV1UserLoginPasswordReply, *http.Response, error)

	/*
	AuthServiceLogout Method for AuthServiceLogout

	登出当前登录账号

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceLogoutRequest
	*/
	AuthServiceLogout(ctx context.Context) ApiAuthServiceLogoutRequest

	// AuthServiceLogoutExecute executes the request
	//  @return map[string]interface{}
	AuthServiceLogoutExecute(r ApiAuthServiceLogoutRequest) (map[string]interface{}, *http.Response, error)

	/*
	AuthServiceRegisterEmail Method for AuthServiceRegisterEmail

	使用邮箱发起账号注册

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceRegisterEmailRequest
	*/
	AuthServiceRegisterEmail(ctx context.Context) ApiAuthServiceRegisterEmailRequest

	// AuthServiceRegisterEmailExecute executes the request
	//  @return CommonApiAppBbsV1UserRegisterEmailReply
	AuthServiceRegisterEmailExecute(r ApiAuthServiceRegisterEmailRequest) (*CommonApiAppBbsV1UserRegisterEmailReply, *http.Response, error)

	/*
	AuthServiceRegisterPhone Method for AuthServiceRegisterPhone

	使用手机号发起账号注册

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceRegisterPhoneRequest
	*/
	AuthServiceRegisterPhone(ctx context.Context) ApiAuthServiceRegisterPhoneRequest

	// AuthServiceRegisterPhoneExecute executes the request
	//  @return CommonApiAppBbsV1UserRegisterPhoneReply
	AuthServiceRegisterPhoneExecute(r ApiAuthServiceRegisterPhoneRequest) (*CommonApiAppBbsV1UserRegisterPhoneReply, *http.Response, error)

	/*
	AuthServiceVerifyEmailRegister Method for AuthServiceVerifyEmailRegister

	校验邮箱注册验证码

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceVerifyEmailRegisterRequest
	*/
	AuthServiceVerifyEmailRegister(ctx context.Context) ApiAuthServiceVerifyEmailRegisterRequest

	// AuthServiceVerifyEmailRegisterExecute executes the request
	//  @return map[string]interface{}
	AuthServiceVerifyEmailRegisterExecute(r ApiAuthServiceVerifyEmailRegisterRequest) (map[string]interface{}, *http.Response, error)

	/*
	AuthServiceVerifyPhoneRegister Method for AuthServiceVerifyPhoneRegister

	校验手机号注册验证码

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAuthServiceVerifyPhoneRegisterRequest
	*/
	AuthServiceVerifyPhoneRegister(ctx context.Context) ApiAuthServiceVerifyPhoneRegisterRequest

	// AuthServiceVerifyPhoneRegisterExecute executes the request
	//  @return map[string]interface{}
	AuthServiceVerifyPhoneRegisterExecute(r ApiAuthServiceVerifyPhoneRegisterRequest) (map[string]interface{}, *http.Response, error)
}

// AuthServiceAPIService AuthServiceAPI service
type AuthServiceAPIService service

type ApiAuthServiceLoginPasswordRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	commonApiAppBbsV1UserLoginPasswordRequest *CommonApiAppBbsV1UserLoginPasswordRequest
}

func (r ApiAuthServiceLoginPasswordRequest) CommonApiAppBbsV1UserLoginPasswordRequest(commonApiAppBbsV1UserLoginPasswordRequest CommonApiAppBbsV1UserLoginPasswordRequest) ApiAuthServiceLoginPasswordRequest {
	r.commonApiAppBbsV1UserLoginPasswordRequest = &commonApiAppBbsV1UserLoginPasswordRequest
	return r
}

func (r ApiAuthServiceLoginPasswordRequest) Execute() (*CommonApiAppBbsV1UserLoginPasswordReply, *http.Response, error) {
	return r.ApiService.AuthServiceLoginPasswordExecute(r)
}

/*
AuthServiceLoginPassword Method for AuthServiceLoginPassword

使用密码登录账号

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceLoginPasswordRequest
*/
func (a *AuthServiceAPIService) AuthServiceLoginPassword(ctx context.Context) ApiAuthServiceLoginPasswordRequest {
	return ApiAuthServiceLoginPasswordRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CommonApiAppBbsV1UserLoginPasswordReply
func (a *AuthServiceAPIService) AuthServiceLoginPasswordExecute(r ApiAuthServiceLoginPasswordRequest) (*CommonApiAppBbsV1UserLoginPasswordReply, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CommonApiAppBbsV1UserLoginPasswordReply
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceLoginPassword")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/login-password"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.commonApiAppBbsV1UserLoginPasswordRequest == nil {
		return localVarReturnValue, nil, reportError("commonApiAppBbsV1UserLoginPasswordRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.commonApiAppBbsV1UserLoginPasswordRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthServiceLogoutRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	body *map[string]interface{}
}

func (r ApiAuthServiceLogoutRequest) Body(body map[string]interface{}) ApiAuthServiceLogoutRequest {
	r.body = &body
	return r
}

func (r ApiAuthServiceLogoutRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.AuthServiceLogoutExecute(r)
}

/*
AuthServiceLogout Method for AuthServiceLogout

登出当前登录账号

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceLogoutRequest
*/
func (a *AuthServiceAPIService) AuthServiceLogout(ctx context.Context) ApiAuthServiceLogoutRequest {
	return ApiAuthServiceLogoutRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthServiceAPIService) AuthServiceLogoutExecute(r ApiAuthServiceLogoutRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceLogout")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/logout"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthServiceRegisterEmailRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	commonApiAppBbsV1UserRegisterEmailRequest *CommonApiAppBbsV1UserRegisterEmailRequest
}

func (r ApiAuthServiceRegisterEmailRequest) CommonApiAppBbsV1UserRegisterEmailRequest(commonApiAppBbsV1UserRegisterEmailRequest CommonApiAppBbsV1UserRegisterEmailRequest) ApiAuthServiceRegisterEmailRequest {
	r.commonApiAppBbsV1UserRegisterEmailRequest = &commonApiAppBbsV1UserRegisterEmailRequest
	return r
}

func (r ApiAuthServiceRegisterEmailRequest) Execute() (*CommonApiAppBbsV1UserRegisterEmailReply, *http.Response, error) {
	return r.ApiService.AuthServiceRegisterEmailExecute(r)
}

/*
AuthServiceRegisterEmail Method for AuthServiceRegisterEmail

使用邮箱发起账号注册

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceRegisterEmailRequest
*/
func (a *AuthServiceAPIService) AuthServiceRegisterEmail(ctx context.Context) ApiAuthServiceRegisterEmailRequest {
	return ApiAuthServiceRegisterEmailRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CommonApiAppBbsV1UserRegisterEmailReply
func (a *AuthServiceAPIService) AuthServiceRegisterEmailExecute(r ApiAuthServiceRegisterEmailRequest) (*CommonApiAppBbsV1UserRegisterEmailReply, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CommonApiAppBbsV1UserRegisterEmailReply
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceRegisterEmail")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/register-email"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.commonApiAppBbsV1UserRegisterEmailRequest == nil {
		return localVarReturnValue, nil, reportError("commonApiAppBbsV1UserRegisterEmailRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.commonApiAppBbsV1UserRegisterEmailRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthServiceRegisterPhoneRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	commonApiAppBbsV1UserRegisterPhoneRequest *CommonApiAppBbsV1UserRegisterPhoneRequest
}

func (r ApiAuthServiceRegisterPhoneRequest) CommonApiAppBbsV1UserRegisterPhoneRequest(commonApiAppBbsV1UserRegisterPhoneRequest CommonApiAppBbsV1UserRegisterPhoneRequest) ApiAuthServiceRegisterPhoneRequest {
	r.commonApiAppBbsV1UserRegisterPhoneRequest = &commonApiAppBbsV1UserRegisterPhoneRequest
	return r
}

func (r ApiAuthServiceRegisterPhoneRequest) Execute() (*CommonApiAppBbsV1UserRegisterPhoneReply, *http.Response, error) {
	return r.ApiService.AuthServiceRegisterPhoneExecute(r)
}

/*
AuthServiceRegisterPhone Method for AuthServiceRegisterPhone

使用手机号发起账号注册

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceRegisterPhoneRequest
*/
func (a *AuthServiceAPIService) AuthServiceRegisterPhone(ctx context.Context) ApiAuthServiceRegisterPhoneRequest {
	return ApiAuthServiceRegisterPhoneRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return CommonApiAppBbsV1UserRegisterPhoneReply
func (a *AuthServiceAPIService) AuthServiceRegisterPhoneExecute(r ApiAuthServiceRegisterPhoneRequest) (*CommonApiAppBbsV1UserRegisterPhoneReply, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *CommonApiAppBbsV1UserRegisterPhoneReply
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceRegisterPhone")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/register-phone"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.commonApiAppBbsV1UserRegisterPhoneRequest == nil {
		return localVarReturnValue, nil, reportError("commonApiAppBbsV1UserRegisterPhoneRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.commonApiAppBbsV1UserRegisterPhoneRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthServiceVerifyEmailRegisterRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	commonApiAppBbsV1UserVerifyEmailRegisterRequest *CommonApiAppBbsV1UserVerifyEmailRegisterRequest
}

func (r ApiAuthServiceVerifyEmailRegisterRequest) CommonApiAppBbsV1UserVerifyEmailRegisterRequest(commonApiAppBbsV1UserVerifyEmailRegisterRequest CommonApiAppBbsV1UserVerifyEmailRegisterRequest) ApiAuthServiceVerifyEmailRegisterRequest {
	r.commonApiAppBbsV1UserVerifyEmailRegisterRequest = &commonApiAppBbsV1UserVerifyEmailRegisterRequest
	return r
}

func (r ApiAuthServiceVerifyEmailRegisterRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.AuthServiceVerifyEmailRegisterExecute(r)
}

/*
AuthServiceVerifyEmailRegister Method for AuthServiceVerifyEmailRegister

校验邮箱注册验证码

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceVerifyEmailRegisterRequest
*/
func (a *AuthServiceAPIService) AuthServiceVerifyEmailRegister(ctx context.Context) ApiAuthServiceVerifyEmailRegisterRequest {
	return ApiAuthServiceVerifyEmailRegisterRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthServiceAPIService) AuthServiceVerifyEmailRegisterExecute(r ApiAuthServiceVerifyEmailRegisterRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceVerifyEmailRegister")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/verify-email-register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.commonApiAppBbsV1UserVerifyEmailRegisterRequest == nil {
		return localVarReturnValue, nil, reportError("commonApiAppBbsV1UserVerifyEmailRegisterRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.commonApiAppBbsV1UserVerifyEmailRegisterRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAuthServiceVerifyPhoneRegisterRequest struct {
	ctx context.Context
	ApiService AuthServiceAPI
	commonApiAppBbsV1UserVerifyPhoneRegisterRequest *CommonApiAppBbsV1UserVerifyPhoneRegisterRequest
}

func (r ApiAuthServiceVerifyPhoneRegisterRequest) CommonApiAppBbsV1UserVerifyPhoneRegisterRequest(commonApiAppBbsV1UserVerifyPhoneRegisterRequest CommonApiAppBbsV1UserVerifyPhoneRegisterRequest) ApiAuthServiceVerifyPhoneRegisterRequest {
	r.commonApiAppBbsV1UserVerifyPhoneRegisterRequest = &commonApiAppBbsV1UserVerifyPhoneRegisterRequest
	return r
}

func (r ApiAuthServiceVerifyPhoneRegisterRequest) Execute() (map[string]interface{}, *http.Response, error) {
	return r.ApiService.AuthServiceVerifyPhoneRegisterExecute(r)
}

/*
AuthServiceVerifyPhoneRegister Method for AuthServiceVerifyPhoneRegister

校验手机号注册验证码

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAuthServiceVerifyPhoneRegisterRequest
*/
func (a *AuthServiceAPIService) AuthServiceVerifyPhoneRegister(ctx context.Context) ApiAuthServiceVerifyPhoneRegisterRequest {
	return ApiAuthServiceVerifyPhoneRegisterRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return map[string]interface{}
func (a *AuthServiceAPIService) AuthServiceVerifyPhoneRegisterExecute(r ApiAuthServiceVerifyPhoneRegisterRequest) (map[string]interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  map[string]interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "AuthServiceAPIService.AuthServiceVerifyPhoneRegister")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/user/auth/verify-phone-register"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.commonApiAppBbsV1UserVerifyPhoneRegisterRequest == nil {
		return localVarReturnValue, nil, reportError("commonApiAppBbsV1UserVerifyPhoneRegisterRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.commonApiAppBbsV1UserVerifyPhoneRegisterRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
