/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UnfollowRelationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnfollowRelationRequest{}

// UnfollowRelationRequest struct for UnfollowRelationRequest
type UnfollowRelationRequest struct {
	// 目标账号 ID。
	TargetId string `json:"target_id"`
}

type _UnfollowRelationRequest UnfollowRelationRequest

// NewUnfollowRelationRequest instantiates a new UnfollowRelationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnfollowRelationRequest(targetId string) *UnfollowRelationRequest {
	this := UnfollowRelationRequest{}
	this.TargetId = targetId
	return &this
}

// NewUnfollowRelationRequestWithDefaults instantiates a new UnfollowRelationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnfollowRelationRequestWithDefaults() *UnfollowRelationRequest {
	this := UnfollowRelationRequest{}
	return &this
}

// GetTargetId returns the TargetId field value
func (o *UnfollowRelationRequest) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *UnfollowRelationRequest) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *UnfollowRelationRequest) SetTargetId(v string) {
	o.TargetId = v
}

func (o UnfollowRelationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnfollowRelationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target_id"] = o.TargetId
	return toSerialize, nil
}

func (o *UnfollowRelationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUnfollowRelationRequest := _UnfollowRelationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUnfollowRelationRequest)

	if err != nil {
		return err
	}

	*o = UnfollowRelationRequest(varUnfollowRelationRequest)

	return err
}

type NullableUnfollowRelationRequest struct {
	value *UnfollowRelationRequest
	isSet bool
}

func (v NullableUnfollowRelationRequest) Get() *UnfollowRelationRequest {
	return v.value
}

func (v *NullableUnfollowRelationRequest) Set(val *UnfollowRelationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUnfollowRelationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUnfollowRelationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnfollowRelationRequest(val *UnfollowRelationRequest) *NullableUnfollowRelationRequest {
	return &NullableUnfollowRelationRequest{value: val, isSet: true}
}

func (v NullableUnfollowRelationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnfollowRelationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


