/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the BeginEnableTotpResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeginEnableTotpResp{}

// BeginEnableTotpResp struct for BeginEnableTotpResp
type BeginEnableTotpResp struct {
	Url *string `json:"url,omitempty"`
	QrCode *string `json:"qr_code,omitempty"`
}

// NewBeginEnableTotpResp instantiates a new BeginEnableTotpResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeginEnableTotpResp() *BeginEnableTotpResp {
	this := BeginEnableTotpResp{}
	return &this
}

// NewBeginEnableTotpRespWithDefaults instantiates a new BeginEnableTotpResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeginEnableTotpRespWithDefaults() *BeginEnableTotpResp {
	this := BeginEnableTotpResp{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BeginEnableTotpResp) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeginEnableTotpResp) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BeginEnableTotpResp) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BeginEnableTotpResp) SetUrl(v string) {
	o.Url = &v
}

// GetQrCode returns the QrCode field value if set, zero value otherwise.
func (o *BeginEnableTotpResp) GetQrCode() string {
	if o == nil || IsNil(o.QrCode) {
		var ret string
		return ret
	}
	return *o.QrCode
}

// GetQrCodeOk returns a tuple with the QrCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeginEnableTotpResp) GetQrCodeOk() (*string, bool) {
	if o == nil || IsNil(o.QrCode) {
		return nil, false
	}
	return o.QrCode, true
}

// HasQrCode returns a boolean if a field has been set.
func (o *BeginEnableTotpResp) HasQrCode() bool {
	if o != nil && !IsNil(o.QrCode) {
		return true
	}

	return false
}

// SetQrCode gets a reference to the given string and assigns it to the QrCode field.
func (o *BeginEnableTotpResp) SetQrCode(v string) {
	o.QrCode = &v
}

func (o BeginEnableTotpResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeginEnableTotpResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.QrCode) {
		toSerialize["qr_code"] = o.QrCode
	}
	return toSerialize, nil
}

type NullableBeginEnableTotpResp struct {
	value *BeginEnableTotpResp
	isSet bool
}

func (v NullableBeginEnableTotpResp) Get() *BeginEnableTotpResp {
	return v.value
}

func (v *NullableBeginEnableTotpResp) Set(val *BeginEnableTotpResp) {
	v.value = val
	v.isSet = true
}

func (v NullableBeginEnableTotpResp) IsSet() bool {
	return v.isSet
}

func (v *NullableBeginEnableTotpResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeginEnableTotpResp(val *BeginEnableTotpResp) *NullableBeginEnableTotpResp {
	return &NullableBeginEnableTotpResp{value: val, isSet: true}
}

func (v NullableBeginEnableTotpResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeginEnableTotpResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


