/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the SendPhoneOtpResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendPhoneOtpResp{}

// SendPhoneOtpResp struct for SendPhoneOtpResp
type SendPhoneOtpResp struct {
	Code *string `json:"code,omitempty"`
}

// NewSendPhoneOtpResp instantiates a new SendPhoneOtpResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendPhoneOtpResp() *SendPhoneOtpResp {
	this := SendPhoneOtpResp{}
	return &this
}

// NewSendPhoneOtpRespWithDefaults instantiates a new SendPhoneOtpResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendPhoneOtpRespWithDefaults() *SendPhoneOtpResp {
	this := SendPhoneOtpResp{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *SendPhoneOtpResp) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendPhoneOtpResp) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *SendPhoneOtpResp) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *SendPhoneOtpResp) SetCode(v string) {
	o.Code = &v
}

func (o SendPhoneOtpResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendPhoneOtpResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableSendPhoneOtpResp struct {
	value *SendPhoneOtpResp
	isSet bool
}

func (v NullableSendPhoneOtpResp) Get() *SendPhoneOtpResp {
	return v.value
}

func (v *NullableSendPhoneOtpResp) Set(val *SendPhoneOtpResp) {
	v.value = val
	v.isSet = true
}

func (v NullableSendPhoneOtpResp) IsSet() bool {
	return v.isSet
}

func (v *NullableSendPhoneOtpResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendPhoneOtpResp(val *SendPhoneOtpResp) *NullableSendPhoneOtpResp {
	return &NullableSendPhoneOtpResp{value: val, isSet: true}
}

func (v NullableSendPhoneOtpResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendPhoneOtpResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


