/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListCommentThreadsReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListCommentThreadsReq{}

// ListCommentThreadsReq struct for ListCommentThreadsReq
type ListCommentThreadsReq struct {
	Page *PageReq `json:"page,omitempty"`
	ArticleId string `json:"article_id"`
	Order *string `json:"order,omitempty"`
	ReplyPreviewLimit *int32 `json:"reply_preview_limit,omitempty"`
}

type _ListCommentThreadsReq ListCommentThreadsReq

// NewListCommentThreadsReq instantiates a new ListCommentThreadsReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListCommentThreadsReq(articleId string) *ListCommentThreadsReq {
	this := ListCommentThreadsReq{}
	this.ArticleId = articleId
	return &this
}

// NewListCommentThreadsReqWithDefaults instantiates a new ListCommentThreadsReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListCommentThreadsReqWithDefaults() *ListCommentThreadsReq {
	this := ListCommentThreadsReq{}
	return &this
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *ListCommentThreadsReq) GetPage() PageReq {
	if o == nil || IsNil(o.Page) {
		var ret PageReq
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommentThreadsReq) GetPageOk() (*PageReq, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *ListCommentThreadsReq) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given PageReq and assigns it to the Page field.
func (o *ListCommentThreadsReq) SetPage(v PageReq) {
	o.Page = &v
}

// GetArticleId returns the ArticleId field value
func (o *ListCommentThreadsReq) GetArticleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleId
}

// GetArticleIdOk returns a tuple with the ArticleId field value
// and a boolean to check if the value has been set.
func (o *ListCommentThreadsReq) GetArticleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleId, true
}

// SetArticleId sets field value
func (o *ListCommentThreadsReq) SetArticleId(v string) {
	o.ArticleId = v
}

// GetOrder returns the Order field value if set, zero value otherwise.
func (o *ListCommentThreadsReq) GetOrder() string {
	if o == nil || IsNil(o.Order) {
		var ret string
		return ret
	}
	return *o.Order
}

// GetOrderOk returns a tuple with the Order field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommentThreadsReq) GetOrderOk() (*string, bool) {
	if o == nil || IsNil(o.Order) {
		return nil, false
	}
	return o.Order, true
}

// HasOrder returns a boolean if a field has been set.
func (o *ListCommentThreadsReq) HasOrder() bool {
	if o != nil && !IsNil(o.Order) {
		return true
	}

	return false
}

// SetOrder gets a reference to the given string and assigns it to the Order field.
func (o *ListCommentThreadsReq) SetOrder(v string) {
	o.Order = &v
}

// GetReplyPreviewLimit returns the ReplyPreviewLimit field value if set, zero value otherwise.
func (o *ListCommentThreadsReq) GetReplyPreviewLimit() int32 {
	if o == nil || IsNil(o.ReplyPreviewLimit) {
		var ret int32
		return ret
	}
	return *o.ReplyPreviewLimit
}

// GetReplyPreviewLimitOk returns a tuple with the ReplyPreviewLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListCommentThreadsReq) GetReplyPreviewLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ReplyPreviewLimit) {
		return nil, false
	}
	return o.ReplyPreviewLimit, true
}

// HasReplyPreviewLimit returns a boolean if a field has been set.
func (o *ListCommentThreadsReq) HasReplyPreviewLimit() bool {
	if o != nil && !IsNil(o.ReplyPreviewLimit) {
		return true
	}

	return false
}

// SetReplyPreviewLimit gets a reference to the given int32 and assigns it to the ReplyPreviewLimit field.
func (o *ListCommentThreadsReq) SetReplyPreviewLimit(v int32) {
	o.ReplyPreviewLimit = &v
}

func (o ListCommentThreadsReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListCommentThreadsReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	toSerialize["article_id"] = o.ArticleId
	if !IsNil(o.Order) {
		toSerialize["order"] = o.Order
	}
	if !IsNil(o.ReplyPreviewLimit) {
		toSerialize["reply_preview_limit"] = o.ReplyPreviewLimit
	}
	return toSerialize, nil
}

func (o *ListCommentThreadsReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListCommentThreadsReq := _ListCommentThreadsReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListCommentThreadsReq)

	if err != nil {
		return err
	}

	*o = ListCommentThreadsReq(varListCommentThreadsReq)

	return err
}

type NullableListCommentThreadsReq struct {
	value *ListCommentThreadsReq
	isSet bool
}

func (v NullableListCommentThreadsReq) Get() *ListCommentThreadsReq {
	return v.value
}

func (v *NullableListCommentThreadsReq) Set(val *ListCommentThreadsReq) {
	v.value = val
	v.isSet = true
}

func (v NullableListCommentThreadsReq) IsSet() bool {
	return v.isSet
}

func (v *NullableListCommentThreadsReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListCommentThreadsReq(val *ListCommentThreadsReq) *NullableListCommentThreadsReq {
	return &NullableListCommentThreadsReq{value: val, isSet: true}
}

func (v NullableListCommentThreadsReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListCommentThreadsReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


