/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FollowRelationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FollowRelationRequest{}

// FollowRelationRequest struct for FollowRelationRequest
type FollowRelationRequest struct {
	// 目标账号 ID。
	TargetId string `json:"target_id"`
}

type _FollowRelationRequest FollowRelationRequest

// NewFollowRelationRequest instantiates a new FollowRelationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFollowRelationRequest(targetId string) *FollowRelationRequest {
	this := FollowRelationRequest{}
	this.TargetId = targetId
	return &this
}

// NewFollowRelationRequestWithDefaults instantiates a new FollowRelationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFollowRelationRequestWithDefaults() *FollowRelationRequest {
	this := FollowRelationRequest{}
	return &this
}

// GetTargetId returns the TargetId field value
func (o *FollowRelationRequest) GetTargetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetId
}

// GetTargetIdOk returns a tuple with the TargetId field value
// and a boolean to check if the value has been set.
func (o *FollowRelationRequest) GetTargetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetId, true
}

// SetTargetId sets field value
func (o *FollowRelationRequest) SetTargetId(v string) {
	o.TargetId = v
}

func (o FollowRelationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FollowRelationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["target_id"] = o.TargetId
	return toSerialize, nil
}

func (o *FollowRelationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"target_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFollowRelationRequest := _FollowRelationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFollowRelationRequest)

	if err != nil {
		return err
	}

	*o = FollowRelationRequest(varFollowRelationRequest)

	return err
}

type NullableFollowRelationRequest struct {
	value *FollowRelationRequest
	isSet bool
}

func (v NullableFollowRelationRequest) Get() *FollowRelationRequest {
	return v.value
}

func (v *NullableFollowRelationRequest) Set(val *FollowRelationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFollowRelationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFollowRelationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFollowRelationRequest(val *FollowRelationRequest) *NullableFollowRelationRequest {
	return &NullableFollowRelationRequest{value: val, isSet: true}
}

func (v NullableFollowRelationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFollowRelationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


