/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the UpdateCurrentPrivacySettingReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCurrentPrivacySettingReply{}

// UpdateCurrentPrivacySettingReply struct for UpdateCurrentPrivacySettingReply
type UpdateCurrentPrivacySettingReply struct {
	PrivacySetting *PrivacySetting `json:"privacy_setting,omitempty"`
}

// NewUpdateCurrentPrivacySettingReply instantiates a new UpdateCurrentPrivacySettingReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCurrentPrivacySettingReply() *UpdateCurrentPrivacySettingReply {
	this := UpdateCurrentPrivacySettingReply{}
	return &this
}

// NewUpdateCurrentPrivacySettingReplyWithDefaults instantiates a new UpdateCurrentPrivacySettingReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCurrentPrivacySettingReplyWithDefaults() *UpdateCurrentPrivacySettingReply {
	this := UpdateCurrentPrivacySettingReply{}
	return &this
}

// GetPrivacySetting returns the PrivacySetting field value if set, zero value otherwise.
func (o *UpdateCurrentPrivacySettingReply) GetPrivacySetting() PrivacySetting {
	if o == nil || IsNil(o.PrivacySetting) {
		var ret PrivacySetting
		return ret
	}
	return *o.PrivacySetting
}

// GetPrivacySettingOk returns a tuple with the PrivacySetting field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateCurrentPrivacySettingReply) GetPrivacySettingOk() (*PrivacySetting, bool) {
	if o == nil || IsNil(o.PrivacySetting) {
		return nil, false
	}
	return o.PrivacySetting, true
}

// HasPrivacySetting returns a boolean if a field has been set.
func (o *UpdateCurrentPrivacySettingReply) HasPrivacySetting() bool {
	if o != nil && !IsNil(o.PrivacySetting) {
		return true
	}

	return false
}

// SetPrivacySetting gets a reference to the given PrivacySetting and assigns it to the PrivacySetting field.
func (o *UpdateCurrentPrivacySettingReply) SetPrivacySetting(v PrivacySetting) {
	o.PrivacySetting = &v
}

func (o UpdateCurrentPrivacySettingReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCurrentPrivacySettingReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PrivacySetting) {
		toSerialize["privacy_setting"] = o.PrivacySetting
	}
	return toSerialize, nil
}

type NullableUpdateCurrentPrivacySettingReply struct {
	value *UpdateCurrentPrivacySettingReply
	isSet bool
}

func (v NullableUpdateCurrentPrivacySettingReply) Get() *UpdateCurrentPrivacySettingReply {
	return v.value
}

func (v *NullableUpdateCurrentPrivacySettingReply) Set(val *UpdateCurrentPrivacySettingReply) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCurrentPrivacySettingReply) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCurrentPrivacySettingReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCurrentPrivacySettingReply(val *UpdateCurrentPrivacySettingReply) *NullableUpdateCurrentPrivacySettingReply {
	return &NullableUpdateCurrentPrivacySettingReply{value: val, isSet: true}
}

func (v NullableUpdateCurrentPrivacySettingReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCurrentPrivacySettingReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


