/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the Totp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Totp{}

// Totp TOTP 认证状态。
type Totp struct {
	// 账号 ID。
	UserId *string `json:"user_id,omitempty"`
	// 是否启用 TOTP。
	Enable *bool `json:"enable,omitempty"`
	// 启用时间。
	EnableTime *string `json:"enable_time,omitempty"`
}

// NewTotp instantiates a new Totp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTotp() *Totp {
	this := Totp{}
	return &this
}

// NewTotpWithDefaults instantiates a new Totp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTotpWithDefaults() *Totp {
	this := Totp{}
	return &this
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Totp) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Totp) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Totp) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Totp) SetUserId(v string) {
	o.UserId = &v
}

// GetEnable returns the Enable field value if set, zero value otherwise.
func (o *Totp) GetEnable() bool {
	if o == nil || IsNil(o.Enable) {
		var ret bool
		return ret
	}
	return *o.Enable
}

// GetEnableOk returns a tuple with the Enable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Totp) GetEnableOk() (*bool, bool) {
	if o == nil || IsNil(o.Enable) {
		return nil, false
	}
	return o.Enable, true
}

// HasEnable returns a boolean if a field has been set.
func (o *Totp) HasEnable() bool {
	if o != nil && !IsNil(o.Enable) {
		return true
	}

	return false
}

// SetEnable gets a reference to the given bool and assigns it to the Enable field.
func (o *Totp) SetEnable(v bool) {
	o.Enable = &v
}

// GetEnableTime returns the EnableTime field value if set, zero value otherwise.
func (o *Totp) GetEnableTime() string {
	if o == nil || IsNil(o.EnableTime) {
		var ret string
		return ret
	}
	return *o.EnableTime
}

// GetEnableTimeOk returns a tuple with the EnableTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Totp) GetEnableTimeOk() (*string, bool) {
	if o == nil || IsNil(o.EnableTime) {
		return nil, false
	}
	return o.EnableTime, true
}

// HasEnableTime returns a boolean if a field has been set.
func (o *Totp) HasEnableTime() bool {
	if o != nil && !IsNil(o.EnableTime) {
		return true
	}

	return false
}

// SetEnableTime gets a reference to the given string and assigns it to the EnableTime field.
func (o *Totp) SetEnableTime(v string) {
	o.EnableTime = &v
}

func (o Totp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Totp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.Enable) {
		toSerialize["enable"] = o.Enable
	}
	if !IsNil(o.EnableTime) {
		toSerialize["enable_time"] = o.EnableTime
	}
	return toSerialize, nil
}

type NullableTotp struct {
	value *Totp
	isSet bool
}

func (v NullableTotp) Get() *Totp {
	return v.value
}

func (v *NullableTotp) Set(val *Totp) {
	v.value = val
	v.isSet = true
}

func (v NullableTotp) IsSet() bool {
	return v.isSet
}

func (v *NullableTotp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTotp(val *Totp) *NullableTotp {
	return &NullableTotp{value: val, isSet: true}
}

func (v NullableTotp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTotp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


