/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the UpdateProfileAccountReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateProfileAccountReq{}

// UpdateProfileAccountReq struct for UpdateProfileAccountReq
type UpdateProfileAccountReq struct {
	AvatarAssetId *string `json:"avatar_asset_id,omitempty"`
	Nickname *string `json:"nickname,omitempty"`
	Url *string `json:"url,omitempty"`
	Introduction *string `json:"introduction,omitempty"`
	Mbti *string `json:"mbti,omitempty"`
}

// NewUpdateProfileAccountReq instantiates a new UpdateProfileAccountReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateProfileAccountReq() *UpdateProfileAccountReq {
	this := UpdateProfileAccountReq{}
	return &this
}

// NewUpdateProfileAccountReqWithDefaults instantiates a new UpdateProfileAccountReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateProfileAccountReqWithDefaults() *UpdateProfileAccountReq {
	this := UpdateProfileAccountReq{}
	return &this
}

// GetAvatarAssetId returns the AvatarAssetId field value if set, zero value otherwise.
func (o *UpdateProfileAccountReq) GetAvatarAssetId() string {
	if o == nil || IsNil(o.AvatarAssetId) {
		var ret string
		return ret
	}
	return *o.AvatarAssetId
}

// GetAvatarAssetIdOk returns a tuple with the AvatarAssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileAccountReq) GetAvatarAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarAssetId) {
		return nil, false
	}
	return o.AvatarAssetId, true
}

// HasAvatarAssetId returns a boolean if a field has been set.
func (o *UpdateProfileAccountReq) HasAvatarAssetId() bool {
	if o != nil && !IsNil(o.AvatarAssetId) {
		return true
	}

	return false
}

// SetAvatarAssetId gets a reference to the given string and assigns it to the AvatarAssetId field.
func (o *UpdateProfileAccountReq) SetAvatarAssetId(v string) {
	o.AvatarAssetId = &v
}

// GetNickname returns the Nickname field value if set, zero value otherwise.
func (o *UpdateProfileAccountReq) GetNickname() string {
	if o == nil || IsNil(o.Nickname) {
		var ret string
		return ret
	}
	return *o.Nickname
}

// GetNicknameOk returns a tuple with the Nickname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileAccountReq) GetNicknameOk() (*string, bool) {
	if o == nil || IsNil(o.Nickname) {
		return nil, false
	}
	return o.Nickname, true
}

// HasNickname returns a boolean if a field has been set.
func (o *UpdateProfileAccountReq) HasNickname() bool {
	if o != nil && !IsNil(o.Nickname) {
		return true
	}

	return false
}

// SetNickname gets a reference to the given string and assigns it to the Nickname field.
func (o *UpdateProfileAccountReq) SetNickname(v string) {
	o.Nickname = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *UpdateProfileAccountReq) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileAccountReq) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *UpdateProfileAccountReq) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *UpdateProfileAccountReq) SetUrl(v string) {
	o.Url = &v
}

// GetIntroduction returns the Introduction field value if set, zero value otherwise.
func (o *UpdateProfileAccountReq) GetIntroduction() string {
	if o == nil || IsNil(o.Introduction) {
		var ret string
		return ret
	}
	return *o.Introduction
}

// GetIntroductionOk returns a tuple with the Introduction field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileAccountReq) GetIntroductionOk() (*string, bool) {
	if o == nil || IsNil(o.Introduction) {
		return nil, false
	}
	return o.Introduction, true
}

// HasIntroduction returns a boolean if a field has been set.
func (o *UpdateProfileAccountReq) HasIntroduction() bool {
	if o != nil && !IsNil(o.Introduction) {
		return true
	}

	return false
}

// SetIntroduction gets a reference to the given string and assigns it to the Introduction field.
func (o *UpdateProfileAccountReq) SetIntroduction(v string) {
	o.Introduction = &v
}

// GetMbti returns the Mbti field value if set, zero value otherwise.
func (o *UpdateProfileAccountReq) GetMbti() string {
	if o == nil || IsNil(o.Mbti) {
		var ret string
		return ret
	}
	return *o.Mbti
}

// GetMbtiOk returns a tuple with the Mbti field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateProfileAccountReq) GetMbtiOk() (*string, bool) {
	if o == nil || IsNil(o.Mbti) {
		return nil, false
	}
	return o.Mbti, true
}

// HasMbti returns a boolean if a field has been set.
func (o *UpdateProfileAccountReq) HasMbti() bool {
	if o != nil && !IsNil(o.Mbti) {
		return true
	}

	return false
}

// SetMbti gets a reference to the given string and assigns it to the Mbti field.
func (o *UpdateProfileAccountReq) SetMbti(v string) {
	o.Mbti = &v
}

func (o UpdateProfileAccountReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateProfileAccountReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvatarAssetId) {
		toSerialize["avatar_asset_id"] = o.AvatarAssetId
	}
	if !IsNil(o.Nickname) {
		toSerialize["nickname"] = o.Nickname
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Introduction) {
		toSerialize["introduction"] = o.Introduction
	}
	if !IsNil(o.Mbti) {
		toSerialize["mbti"] = o.Mbti
	}
	return toSerialize, nil
}

type NullableUpdateProfileAccountReq struct {
	value *UpdateProfileAccountReq
	isSet bool
}

func (v NullableUpdateProfileAccountReq) Get() *UpdateProfileAccountReq {
	return v.value
}

func (v *NullableUpdateProfileAccountReq) Set(val *UpdateProfileAccountReq) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateProfileAccountReq) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateProfileAccountReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateProfileAccountReq(val *UpdateProfileAccountReq) *NullableUpdateProfileAccountReq {
	return &NullableUpdateProfileAccountReq{value: val, isSet: true}
}

func (v NullableUpdateProfileAccountReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateProfileAccountReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


