/*


No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the CommonApiAppBbsV1UserAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonApiAppBbsV1UserAccount{}

// CommonApiAppBbsV1UserAccount 当前账号完整资料
type CommonApiAppBbsV1UserAccount struct {
	Profile *CommonApiAppBbsV1UserAccountProfile `json:"profile,omitempty"`
	Contact *CommonApiAppBbsV1UserAccountContact `json:"contact,omitempty"`
}

// NewCommonApiAppBbsV1UserAccount instantiates a new CommonApiAppBbsV1UserAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonApiAppBbsV1UserAccount() *CommonApiAppBbsV1UserAccount {
	this := CommonApiAppBbsV1UserAccount{}
	return &this
}

// NewCommonApiAppBbsV1UserAccountWithDefaults instantiates a new CommonApiAppBbsV1UserAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonApiAppBbsV1UserAccountWithDefaults() *CommonApiAppBbsV1UserAccount {
	this := CommonApiAppBbsV1UserAccount{}
	return &this
}

// GetProfile returns the Profile field value if set, zero value otherwise.
func (o *CommonApiAppBbsV1UserAccount) GetProfile() CommonApiAppBbsV1UserAccountProfile {
	if o == nil || IsNil(o.Profile) {
		var ret CommonApiAppBbsV1UserAccountProfile
		return ret
	}
	return *o.Profile
}

// GetProfileOk returns a tuple with the Profile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonApiAppBbsV1UserAccount) GetProfileOk() (*CommonApiAppBbsV1UserAccountProfile, bool) {
	if o == nil || IsNil(o.Profile) {
		return nil, false
	}
	return o.Profile, true
}

// HasProfile returns a boolean if a field has been set.
func (o *CommonApiAppBbsV1UserAccount) HasProfile() bool {
	if o != nil && !IsNil(o.Profile) {
		return true
	}

	return false
}

// SetProfile gets a reference to the given CommonApiAppBbsV1UserAccountProfile and assigns it to the Profile field.
func (o *CommonApiAppBbsV1UserAccount) SetProfile(v CommonApiAppBbsV1UserAccountProfile) {
	o.Profile = &v
}

// GetContact returns the Contact field value if set, zero value otherwise.
func (o *CommonApiAppBbsV1UserAccount) GetContact() CommonApiAppBbsV1UserAccountContact {
	if o == nil || IsNil(o.Contact) {
		var ret CommonApiAppBbsV1UserAccountContact
		return ret
	}
	return *o.Contact
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonApiAppBbsV1UserAccount) GetContactOk() (*CommonApiAppBbsV1UserAccountContact, bool) {
	if o == nil || IsNil(o.Contact) {
		return nil, false
	}
	return o.Contact, true
}

// HasContact returns a boolean if a field has been set.
func (o *CommonApiAppBbsV1UserAccount) HasContact() bool {
	if o != nil && !IsNil(o.Contact) {
		return true
	}

	return false
}

// SetContact gets a reference to the given CommonApiAppBbsV1UserAccountContact and assigns it to the Contact field.
func (o *CommonApiAppBbsV1UserAccount) SetContact(v CommonApiAppBbsV1UserAccountContact) {
	o.Contact = &v
}

func (o CommonApiAppBbsV1UserAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonApiAppBbsV1UserAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Profile) {
		toSerialize["profile"] = o.Profile
	}
	if !IsNil(o.Contact) {
		toSerialize["contact"] = o.Contact
	}
	return toSerialize, nil
}

type NullableCommonApiAppBbsV1UserAccount struct {
	value *CommonApiAppBbsV1UserAccount
	isSet bool
}

func (v NullableCommonApiAppBbsV1UserAccount) Get() *CommonApiAppBbsV1UserAccount {
	return v.value
}

func (v *NullableCommonApiAppBbsV1UserAccount) Set(val *CommonApiAppBbsV1UserAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonApiAppBbsV1UserAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonApiAppBbsV1UserAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonApiAppBbsV1UserAccount(val *CommonApiAppBbsV1UserAccount) *NullableCommonApiAppBbsV1UserAccount {
	return &NullableCommonApiAppBbsV1UserAccount{value: val, isSet: true}
}

func (v NullableCommonApiAppBbsV1UserAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonApiAppBbsV1UserAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


