/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetArticleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetArticleRequest{}

// GetArticleRequest struct for GetArticleRequest
type GetArticleRequest struct {
	ArticleId string `json:"article_id"`
}

type _GetArticleRequest GetArticleRequest

// NewGetArticleRequest instantiates a new GetArticleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetArticleRequest(articleId string) *GetArticleRequest {
	this := GetArticleRequest{}
	this.ArticleId = articleId
	return &this
}

// NewGetArticleRequestWithDefaults instantiates a new GetArticleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetArticleRequestWithDefaults() *GetArticleRequest {
	this := GetArticleRequest{}
	return &this
}

// GetArticleId returns the ArticleId field value
func (o *GetArticleRequest) GetArticleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ArticleId
}

// GetArticleIdOk returns a tuple with the ArticleId field value
// and a boolean to check if the value has been set.
func (o *GetArticleRequest) GetArticleIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ArticleId, true
}

// SetArticleId sets field value
func (o *GetArticleRequest) SetArticleId(v string) {
	o.ArticleId = v
}

func (o GetArticleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetArticleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["article_id"] = o.ArticleId
	return toSerialize, nil
}

func (o *GetArticleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"article_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetArticleRequest := _GetArticleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetArticleRequest)

	if err != nil {
		return err
	}

	*o = GetArticleRequest(varGetArticleRequest)

	return err
}

type NullableGetArticleRequest struct {
	value *GetArticleRequest
	isSet bool
}

func (v NullableGetArticleRequest) Get() *GetArticleRequest {
	return v.value
}

func (v *NullableGetArticleRequest) Set(val *GetArticleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetArticleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetArticleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetArticleRequest(val *GetArticleRequest) *NullableGetArticleRequest {
	return &NullableGetArticleRequest{value: val, isSet: true}
}

func (v NullableGetArticleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetArticleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


