/*
Bass BBS API

Bass 社区 HTTP/JSON API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package bbs

import (
	"encoding/json"
)

// checks if the UpdateDomainResp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainResp{}

// UpdateDomainResp struct for UpdateDomainResp
type UpdateDomainResp struct {
	Domain *RespDomain `json:"domain,omitempty"`
}

// NewUpdateDomainResp instantiates a new UpdateDomainResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainResp() *UpdateDomainResp {
	this := UpdateDomainResp{}
	return &this
}

// NewUpdateDomainRespWithDefaults instantiates a new UpdateDomainResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainRespWithDefaults() *UpdateDomainResp {
	this := UpdateDomainResp{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *UpdateDomainResp) GetDomain() RespDomain {
	if o == nil || IsNil(o.Domain) {
		var ret RespDomain
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainResp) GetDomainOk() (*RespDomain, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *UpdateDomainResp) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given RespDomain and assigns it to the Domain field.
func (o *UpdateDomainResp) SetDomain(v RespDomain) {
	o.Domain = &v
}

func (o UpdateDomainResp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainResp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

type NullableUpdateDomainResp struct {
	value *UpdateDomainResp
	isSet bool
}

func (v NullableUpdateDomainResp) Get() *UpdateDomainResp {
	return v.value
}

func (v *NullableUpdateDomainResp) Set(val *UpdateDomainResp) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainResp) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainResp(val *UpdateDomainResp) *NullableUpdateDomainResp {
	return &NullableUpdateDomainResp{value: val, isSet: true}
}

func (v NullableUpdateDomainResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


