syntax = "proto3";

package common.api.app.signal.v1;

import "google/api/annotations.proto";
import "signal/v1/model.proto";
import "signal/v1/enum.proto";

option go_package = "common/api/gen/signal/v1;v1";

// Node 服务
service SignalNodeService {

  // 保存节点
  rpc Save (SaveSignalNode.Request) returns (SaveSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/save"
      body: "*"
    };
  }

  // 更新节点信息
  rpc Update (UpdateSignalNode.Request) returns (UpdateSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/update"
      body: "*"
    };
  }

  // 获取密钥
  rpc GetSecret (GetSecretSignalNode.Request) returns (GetSecretSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/secret"
      body: "*"
    };
  }

  // 更新密钥
  rpc UpdateSecret (UpdateSecretSignalNode.Request) returns (UpdateSecretSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/update-secret"
      body: "*"
    };
  }

  // 查询节点列表
  rpc List (ListSignalNode.Request) returns (ListSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/list"
      body: "*"
    };
  }

  // 客户端调度/协商
  rpc Negotiate (NegotiateSignalNode.Request) returns (NegotiateSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/negotiate"
      body: "*"
    };
  }

  // 注册节点
  rpc Register (RegisterSignalNode.Request) returns (RegisterSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/register"
      body: "*"
    };
  }

  // 注销节点
  rpc Unregister (UnregisterSignalNode.Request) returns (UnregisterSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/unregister"
      body: "*"
    };
  }

  // 获取 websocket ticket
  rpc Ticket (TicketSignalNode.Request) returns (TicketSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/ticket"
      body: "*"
    };
  }

  // 用户上线
  rpc Online (OnlineSignalNode.Request) returns (OnlineSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/online"
      body: "*"
    };
  }

  // 用户下线
  rpc Offline (OfflineSignalNode.Request) returns (OfflineSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/offline"
      body: "*"
    };
  }

  // 在线用户列表
  rpc OnlineList (OnlineListSignalNode.Request) returns (OnlineListSignalNode.Reply) {
    option (google.api.http) = {
      post: "/v1/signal-node/online-list"
      body:"*"
    };
  }

}



message SaveSignalNode {
  message Request {
    // 节点信息
    Node node = 1;
  }
  message Reply {
    // 节点信息
    Node node = 1;
  }
}

message UpdateSignalNode {
  message Request {
    // 节点信息
    Node node = 1;
  }
  message Reply {
    // 节点信息
    Node node = 1;
  }
}

message GetSecretSignalNode {
  message Request {
    // 节点 ID
    int64 id = 1;
  }
  message Reply {
    // 密钥
    string secret = 1;
  }
}

message UpdateSecretSignalNode {
  message Request {
    // 节点 ID
    int64 id = 1;
  }
  message Reply {
    // 密钥
    string secret = 1;
  }
}

message ListSignalNode {
  message Request {
    // 节点状态
    NodeStatus status = 1;
  }
  message Reply {
    // 节点列表
    repeated Node nodes = 1;
  }
}

message NegotiateSignalNode {
  message Request {}
  message Reply {
    // ticket
    string ticket = 1;
    // 节点列表
    repeated Node nodes = 2;
  }
}

message RegisterSignalNode {
  message Request {}
  message Reply {}
}

message UnregisterSignalNode {
  message Request {}
  message Reply {}
}

message TicketSignalNode {
  message Request {}
  message Reply {
    // ticket
    string ticket = 1;
  }
}

message OnlineSignalNode {
  message Request {
    // ticket
    string ticket = 1;
  }
  message Reply {
    // session Id
    string session_id = 1;
  }
}

message OfflineSignalNode {
  message Request {
    // session ID
    string session_id = 1;
  }
  message Reply {}
}

message OnlineListSignalNode {
  message Request {}
  message Reply {}
}
