config:
  jetstream:
    enabled: true
    fileStore:
      pvc:
        enabled: true
        size: 5Gi
    merge:
      max_mem: "1G"
      max_file: "10G"

  cluster:
    enabled: true
    merge:
      port: 6222
      name: "nats-cluster"

  monitor:
    enabled: true

statefulSet:
  replicas: 3

promExporter:
  enabled: true

service:
  enabled: true
  merge:
    spec:
      type: NodePort
      ports:
        - name: nats
          port: 4222
          nodePort: 30083
          protocol: TCP
        - name: metrics
          port: 7777
          nodePort: 30084
          protocol: TCP
        - name: monitor
          port: 8222
          nodePort: 30085
          protocol: TCP

container:
  merge:
    resources:
      requests:
        cpu: "500m"
        memory: 1Gi
      limits:
        cpu: "1"
        memory: 2Gi

# helm upgrade --install nats nats/nats -n bass-test --create-namespace -f ./nats.yaml
