auth:
  enablePostgresUser: true
  postgresPassword: "123456"
  username: "admin"
  password: "123456"
  database: "bass"

primary:
  persistence:
    enabled: true
    size: 10Gi

  service:
    type: NodePort
    nodePorts:
      postgresql: 30081

readReplicas:
  replicaCount: 0

architecture: standalone

service:
  type: ClusterIP

# helm upgrade --install postgres bitnami/postgresql -n bass-test --create-namespace -f ./postgres.yaml