architecture: standalone

auth:
  enabled: true
  password: "123456"

master:
  persistence:
    enabled: true
    size: 5Gi

  service:
    type: NodePort
    nodePorts:
      redis: 30082

replica:
  replicaCount: 0

sentinel:
  enabled: false

service:
  type: ClusterIP

# helm upgrade --install redis bitnami/redis -n bass-test --create-namespace -f ./redis/redis-postgres-nats.yaml