/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * 文章附言。
 */
@JsonPropertyOrder({
  ArticlePostscript.JSON_PROPERTY_ID,
  ArticlePostscript.JSON_PROPERTY_ARTICLE_ID,
  ArticlePostscript.JSON_PROPERTY_CONTENT,
  ArticlePostscript.JSON_PROPERTY_CONTENT_RENDER,
  ArticlePostscript.JSON_PROPERTY_RESTRICTION,
  ArticlePostscript.JSON_PROPERTY_CREATED_BY,
  ArticlePostscript.JSON_PROPERTY_UPDATED_BY,
  ArticlePostscript.JSON_PROPERTY_CREATED_AT,
  ArticlePostscript.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ArticlePostscript {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_ARTICLE_ID = "article_id";
  @javax.annotation.Nullable
  private String articleId;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private String content;

  public static final String JSON_PROPERTY_CONTENT_RENDER = "content_render";
  @javax.annotation.Nullable
  private String contentRender;

  /**
   * Gets or Sets restriction
   */
  public enum RestrictionEnum {
    CONTENT_RESTRICTION_UNSPECIFIED(String.valueOf("CONTENT_RESTRICTION_UNSPECIFIED")),
    
    CONTENT_RESTRICTION_NONE(String.valueOf("CONTENT_RESTRICTION_NONE")),
    
    CONTENT_RESTRICTION_HIDDEN(String.valueOf("CONTENT_RESTRICTION_HIDDEN")),
    
    CONTENT_RESTRICTION_LOCKED(String.valueOf("CONTENT_RESTRICTION_LOCKED"));

    private String value;

    RestrictionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RestrictionEnum fromValue(String value) {
      for (RestrictionEnum b : RestrictionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_RESTRICTION = "restriction";
  @javax.annotation.Nullable
  private RestrictionEnum restriction;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  @javax.annotation.Nullable
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  @javax.annotation.Nullable
  private String updatedBy;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private String updatedAt;

  public ArticlePostscript() { 
  }

  public ArticlePostscript id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public ArticlePostscript articleId(@javax.annotation.Nullable String articleId) {
    this.articleId = articleId;
    return this;
  }

  /**
   * Get articleId
   * @return articleId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTICLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getArticleId() {
    return articleId;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTICLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArticleId(@javax.annotation.Nullable String articleId) {
    this.articleId = articleId;
  }


  public ArticlePostscript content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public ArticlePostscript contentRender(@javax.annotation.Nullable String contentRender) {
    this.contentRender = contentRender;
    return this;
  }

  /**
   * Get contentRender
   * @return contentRender
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT_RENDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContentRender() {
    return contentRender;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_RENDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentRender(@javax.annotation.Nullable String contentRender) {
    this.contentRender = contentRender;
  }


  public ArticlePostscript restriction(@javax.annotation.Nullable RestrictionEnum restriction) {
    this.restriction = restriction;
    return this;
  }

  /**
   * Get restriction
   * @return restriction
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RESTRICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RestrictionEnum getRestriction() {
    return restriction;
  }


  @JsonProperty(value = JSON_PROPERTY_RESTRICTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRestriction(@javax.annotation.Nullable RestrictionEnum restriction) {
    this.restriction = restriction;
  }


  public ArticlePostscript createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public ArticlePostscript updatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Get updatedBy
   * @return updatedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public ArticlePostscript createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public ArticlePostscript updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this ArticlePostscript object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticlePostscript articlePostscript = (ArticlePostscript) o;
    return Objects.equals(this.id, articlePostscript.id) &&
        Objects.equals(this.articleId, articlePostscript.articleId) &&
        Objects.equals(this.content, articlePostscript.content) &&
        Objects.equals(this.contentRender, articlePostscript.contentRender) &&
        Objects.equals(this.restriction, articlePostscript.restriction) &&
        Objects.equals(this.createdBy, articlePostscript.createdBy) &&
        Objects.equals(this.updatedBy, articlePostscript.updatedBy) &&
        Objects.equals(this.createdAt, articlePostscript.createdAt) &&
        Objects.equals(this.updatedAt, articlePostscript.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, articleId, content, contentRender, restriction, createdBy, updatedBy, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticlePostscript {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentRender: ").append(toIndentedString(contentRender)).append("\n");
    sb.append("    restriction: ").append(toIndentedString(restriction)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `article_id` to the URL query string
    if (getArticleId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sarticle_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArticleId()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `content_render` to the URL query string
    if (getContentRender() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent_render%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentRender()))));
    }

    // add `restriction` to the URL query string
    if (getRestriction() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srestriction%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRestriction()))));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedBy()))));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedBy()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

