/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * BeginEnableTotpReply
 */
@JsonPropertyOrder({
  BeginEnableTotpReply.JSON_PROPERTY_URL,
  BeginEnableTotpReply.JSON_PROPERTY_QR_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class BeginEnableTotpReply {
  public static final String JSON_PROPERTY_URL = "url";
  @javax.annotation.Nullable
  private String url;

  public static final String JSON_PROPERTY_QR_CODE = "qr_code";
  @javax.annotation.Nullable
  private String qrCode;

  public BeginEnableTotpReply() { 
  }

  public BeginEnableTotpReply url(@javax.annotation.Nullable String url) {
    this.url = url;
    return this;
  }

  /**
   * TOTP 绑定 URL。
   * @return url
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUrl() {
    return url;
  }


  @JsonProperty(value = JSON_PROPERTY_URL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUrl(@javax.annotation.Nullable String url) {
    this.url = url;
  }


  public BeginEnableTotpReply qrCode(@javax.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
    return this;
  }

  /**
   * TOTP 二维码图片数据。
   * @return qrCode
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_QR_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getQrCode() {
    return qrCode;
  }


  @JsonProperty(value = JSON_PROPERTY_QR_CODE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCode(@javax.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
  }


  /**
   * Return true if this BeginEnableTotp_Reply object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BeginEnableTotpReply beginEnableTotpReply = (BeginEnableTotpReply) o;
    return Objects.equals(this.url, beginEnableTotpReply.url) &&
        Objects.equals(this.qrCode, beginEnableTotpReply.qrCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, qrCode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BeginEnableTotpReply {\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `url` to the URL query string
    if (getUrl() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%surl%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUrl()))));
    }

    // add `qr_code` to the URL query string
    if (getQrCode() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sqr_code%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQrCode()))));
    }

    return joiner.toString();
  }
}

