/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.bass.bbs.model.AccountProfile;
import com.bass.bbs.model.Article;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * Comment
 */
@JsonPropertyOrder({
  Comment.JSON_PROPERTY_ID,
  Comment.JSON_PROPERTY_ARTICLE_ID,
  Comment.JSON_PROPERTY_CONTENT,
  Comment.JSON_PROPERTY_CONTENT_RENDER,
  Comment.JSON_PROPERTY_LEVEL,
  Comment.JSON_PROPERTY_PARENT_ID,
  Comment.JSON_PROPERTY_REPLY_ID,
  Comment.JSON_PROPERTY_STATUS,
  Comment.JSON_PROPERTY_REPLY_COUNT,
  Comment.JSON_PROPERTY_LIKE_COUNT,
  Comment.JSON_PROPERTY_THANK_COUNT,
  Comment.JSON_PROPERTY_USER,
  Comment.JSON_PROPERTY_REPLY_USER,
  Comment.JSON_PROPERTY_ARTICLE,
  Comment.JSON_PROPERTY_CREATED_BY,
  Comment.JSON_PROPERTY_UPDATED_BY,
  Comment.JSON_PROPERTY_CREATED_AT,
  Comment.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class Comment {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_ARTICLE_ID = "article_id";
  @javax.annotation.Nullable
  private String articleId;

  public static final String JSON_PROPERTY_CONTENT = "content";
  @javax.annotation.Nullable
  private String content;

  public static final String JSON_PROPERTY_CONTENT_RENDER = "content_render";
  @javax.annotation.Nullable
  private String contentRender;

  public static final String JSON_PROPERTY_LEVEL = "level";
  @javax.annotation.Nullable
  private Integer level;

  public static final String JSON_PROPERTY_PARENT_ID = "parent_id";
  @javax.annotation.Nullable
  private String parentId;

  public static final String JSON_PROPERTY_REPLY_ID = "reply_id";
  @javax.annotation.Nullable
  private String replyId;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    COMMENT_STATUS_UNSPECIFIED(String.valueOf("COMMENT_STATUS_UNSPECIFIED")),
    
    COMMENT_STATUS_NORMAL(String.valueOf("COMMENT_STATUS_NORMAL")),
    
    COMMENT_STATUS_HIDDEN(String.valueOf("COMMENT_STATUS_HIDDEN"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_REPLY_COUNT = "reply_count";
  @javax.annotation.Nullable
  private Integer replyCount;

  public static final String JSON_PROPERTY_LIKE_COUNT = "like_count";
  @javax.annotation.Nullable
  private Integer likeCount;

  public static final String JSON_PROPERTY_THANK_COUNT = "thank_count";
  @javax.annotation.Nullable
  private Integer thankCount;

  public static final String JSON_PROPERTY_USER = "user";
  @javax.annotation.Nullable
  private AccountProfile user;

  public static final String JSON_PROPERTY_REPLY_USER = "reply_user";
  @javax.annotation.Nullable
  private AccountProfile replyUser;

  public static final String JSON_PROPERTY_ARTICLE = "article";
  @javax.annotation.Nullable
  private Article article;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  @javax.annotation.Nullable
  private String createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  @javax.annotation.Nullable
  private String updatedBy;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private String createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private String updatedAt;

  public Comment() { 
  }

  public Comment id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public Comment articleId(@javax.annotation.Nullable String articleId) {
    this.articleId = articleId;
    return this;
  }

  /**
   * Get articleId
   * @return articleId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTICLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getArticleId() {
    return articleId;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTICLE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArticleId(@javax.annotation.Nullable String articleId) {
    this.articleId = articleId;
  }


  public Comment content(@javax.annotation.Nullable String content) {
    this.content = content;
    return this;
  }

  /**
   * Get content
   * @return content
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContent() {
    return content;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContent(@javax.annotation.Nullable String content) {
    this.content = content;
  }


  public Comment contentRender(@javax.annotation.Nullable String contentRender) {
    this.contentRender = contentRender;
    return this;
  }

  /**
   * Get contentRender
   * @return contentRender
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT_RENDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContentRender() {
    return contentRender;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_RENDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentRender(@javax.annotation.Nullable String contentRender) {
    this.contentRender = contentRender;
  }


  public Comment level(@javax.annotation.Nullable Integer level) {
    this.level = level;
    return this;
  }

  /**
   * Get level
   * @return level
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLevel() {
    return level;
  }


  @JsonProperty(value = JSON_PROPERTY_LEVEL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLevel(@javax.annotation.Nullable Integer level) {
    this.level = level;
  }


  public Comment parentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
    return this;
  }

  /**
   * Get parentId
   * @return parentId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getParentId() {
    return parentId;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParentId(@javax.annotation.Nullable String parentId) {
    this.parentId = parentId;
  }


  public Comment replyId(@javax.annotation.Nullable String replyId) {
    this.replyId = replyId;
    return this;
  }

  /**
   * Get replyId
   * @return replyId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReplyId() {
    return replyId;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyId(@javax.annotation.Nullable String replyId) {
    this.replyId = replyId;
  }


  public Comment status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public Comment replyCount(@javax.annotation.Nullable Integer replyCount) {
    this.replyCount = replyCount;
    return this;
  }

  /**
   * Get replyCount
   * @return replyCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getReplyCount() {
    return replyCount;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyCount(@javax.annotation.Nullable Integer replyCount) {
    this.replyCount = replyCount;
  }


  public Comment likeCount(@javax.annotation.Nullable Integer likeCount) {
    this.likeCount = likeCount;
    return this;
  }

  /**
   * Get likeCount
   * @return likeCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LIKE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getLikeCount() {
    return likeCount;
  }


  @JsonProperty(value = JSON_PROPERTY_LIKE_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLikeCount(@javax.annotation.Nullable Integer likeCount) {
    this.likeCount = likeCount;
  }


  public Comment thankCount(@javax.annotation.Nullable Integer thankCount) {
    this.thankCount = thankCount;
    return this;
  }

  /**
   * Get thankCount
   * @return thankCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_THANK_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getThankCount() {
    return thankCount;
  }


  @JsonProperty(value = JSON_PROPERTY_THANK_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setThankCount(@javax.annotation.Nullable Integer thankCount) {
    this.thankCount = thankCount;
  }


  public Comment user(@javax.annotation.Nullable AccountProfile user) {
    this.user = user;
    return this;
  }

  /**
   * Get user
   * @return user
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AccountProfile getUser() {
    return user;
  }


  @JsonProperty(value = JSON_PROPERTY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUser(@javax.annotation.Nullable AccountProfile user) {
    this.user = user;
  }


  public Comment replyUser(@javax.annotation.Nullable AccountProfile replyUser) {
    this.replyUser = replyUser;
    return this;
  }

  /**
   * Get replyUser
   * @return replyUser
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REPLY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AccountProfile getReplyUser() {
    return replyUser;
  }


  @JsonProperty(value = JSON_PROPERTY_REPLY_USER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReplyUser(@javax.annotation.Nullable AccountProfile replyUser) {
    this.replyUser = replyUser;
  }


  public Comment article(@javax.annotation.Nullable Article article) {
    this.article = article;
    return this;
  }

  /**
   * Get article
   * @return article
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTICLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Article getArticle() {
    return article;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTICLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArticle(@javax.annotation.Nullable Article article) {
    this.article = article;
  }


  public Comment createdBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(@javax.annotation.Nullable String createdBy) {
    this.createdBy = createdBy;
  }


  public Comment updatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Get updatedBy
   * @return updatedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(@javax.annotation.Nullable String updatedBy) {
    this.updatedBy = updatedBy;
  }


  public Comment createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  public Comment updatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@javax.annotation.Nullable String updatedAt) {
    this.updatedAt = updatedAt;
  }


  /**
   * Return true if this Comment object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Comment comment = (Comment) o;
    return Objects.equals(this.id, comment.id) &&
        Objects.equals(this.articleId, comment.articleId) &&
        Objects.equals(this.content, comment.content) &&
        Objects.equals(this.contentRender, comment.contentRender) &&
        Objects.equals(this.level, comment.level) &&
        Objects.equals(this.parentId, comment.parentId) &&
        Objects.equals(this.replyId, comment.replyId) &&
        Objects.equals(this.status, comment.status) &&
        Objects.equals(this.replyCount, comment.replyCount) &&
        Objects.equals(this.likeCount, comment.likeCount) &&
        Objects.equals(this.thankCount, comment.thankCount) &&
        Objects.equals(this.user, comment.user) &&
        Objects.equals(this.replyUser, comment.replyUser) &&
        Objects.equals(this.article, comment.article) &&
        Objects.equals(this.createdBy, comment.createdBy) &&
        Objects.equals(this.updatedBy, comment.updatedBy) &&
        Objects.equals(this.createdAt, comment.createdAt) &&
        Objects.equals(this.updatedAt, comment.updatedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, articleId, content, contentRender, level, parentId, replyId, status, replyCount, likeCount, thankCount, user, replyUser, article, createdBy, updatedBy, createdAt, updatedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Comment {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    articleId: ").append(toIndentedString(articleId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    contentRender: ").append(toIndentedString(contentRender)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    replyId: ").append(toIndentedString(replyId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    replyCount: ").append(toIndentedString(replyCount)).append("\n");
    sb.append("    likeCount: ").append(toIndentedString(likeCount)).append("\n");
    sb.append("    thankCount: ").append(toIndentedString(thankCount)).append("\n");
    sb.append("    user: ").append(toIndentedString(user)).append("\n");
    sb.append("    replyUser: ").append(toIndentedString(replyUser)).append("\n");
    sb.append("    article: ").append(toIndentedString(article)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `article_id` to the URL query string
    if (getArticleId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sarticle_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getArticleId()))));
    }

    // add `content` to the URL query string
    if (getContent() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContent()))));
    }

    // add `content_render` to the URL query string
    if (getContentRender() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%scontent_render%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContentRender()))));
    }

    // add `level` to the URL query string
    if (getLevel() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slevel%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLevel()))));
    }

    // add `parent_id` to the URL query string
    if (getParentId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sparent_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getParentId()))));
    }

    // add `reply_id` to the URL query string
    if (getReplyId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreply_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReplyId()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `reply_count` to the URL query string
    if (getReplyCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreply_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReplyCount()))));
    }

    // add `like_count` to the URL query string
    if (getLikeCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%slike_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLikeCount()))));
    }

    // add `thank_count` to the URL query string
    if (getThankCount() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sthank_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getThankCount()))));
    }

    // add `user` to the URL query string
    if (getUser() != null) {
      joiner.add(getUser().toUrlQueryString(prefix + "user" + suffix));
    }

    // add `reply_user` to the URL query string
    if (getReplyUser() != null) {
      joiner.add(getReplyUser().toUrlQueryString(prefix + "reply_user" + suffix));
    }

    // add `article` to the URL query string
    if (getArticle() != null) {
      joiner.add(getArticle().toUrlQueryString(prefix + "article" + suffix));
    }

    // add `created_by` to the URL query string
    if (getCreatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedBy()))));
    }

    // add `updated_by` to the URL query string
    if (getUpdatedBy() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_by%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedBy()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

