/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.bass.bbs.model.RespAccount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * LoginResp
 */
@JsonPropertyOrder({
  LoginResp.JSON_PROPERTY_ACCESS_TOKEN,
  LoginResp.JSON_PROPERTY_REFRESH_TOKEN,
  LoginResp.JSON_PROPERTY_ACCESS_TOKEN_EXPIRES_AT,
  LoginResp.JSON_PROPERTY_REFRESH_TOKEN_EXPIRES_AT,
  LoginResp.JSON_PROPERTY_SESSION_EXPIRES_AT,
  LoginResp.JSON_PROPERTY_ACCOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class LoginResp {
  public static final String JSON_PROPERTY_ACCESS_TOKEN = "access_token";
  @javax.annotation.Nullable
  private String accessToken;

  public static final String JSON_PROPERTY_REFRESH_TOKEN = "refresh_token";
  @javax.annotation.Nullable
  private String refreshToken;

  public static final String JSON_PROPERTY_ACCESS_TOKEN_EXPIRES_AT = "access_token_expires_at";
  @javax.annotation.Nullable
  private OffsetDateTime accessTokenExpiresAt;

  public static final String JSON_PROPERTY_REFRESH_TOKEN_EXPIRES_AT = "refresh_token_expires_at";
  @javax.annotation.Nullable
  private OffsetDateTime refreshTokenExpiresAt;

  public static final String JSON_PROPERTY_SESSION_EXPIRES_AT = "session_expires_at";
  @javax.annotation.Nullable
  private OffsetDateTime sessionExpiresAt;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  @javax.annotation.Nullable
  private RespAccount account;

  public LoginResp() { 
  }

  public LoginResp accessToken(@javax.annotation.Nullable String accessToken) {
    this.accessToken = accessToken;
    return this;
  }

  /**
   * Get accessToken
   * @return accessToken
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAccessToken() {
    return accessToken;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessToken(@javax.annotation.Nullable String accessToken) {
    this.accessToken = accessToken;
  }


  public LoginResp refreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
    return this;
  }

  /**
   * Get refreshToken
   * @return refreshToken
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRefreshToken() {
    return refreshToken;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefreshToken(@javax.annotation.Nullable String refreshToken) {
    this.refreshToken = refreshToken;
  }


  public LoginResp accessTokenExpiresAt(@javax.annotation.Nullable OffsetDateTime accessTokenExpiresAt) {
    this.accessTokenExpiresAt = accessTokenExpiresAt;
    return this;
  }

  /**
   * Get accessTokenExpiresAt
   * @return accessTokenExpiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getAccessTokenExpiresAt() {
    return accessTokenExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCESS_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccessTokenExpiresAt(@javax.annotation.Nullable OffsetDateTime accessTokenExpiresAt) {
    this.accessTokenExpiresAt = accessTokenExpiresAt;
  }


  public LoginResp refreshTokenExpiresAt(@javax.annotation.Nullable OffsetDateTime refreshTokenExpiresAt) {
    this.refreshTokenExpiresAt = refreshTokenExpiresAt;
    return this;
  }

  /**
   * Get refreshTokenExpiresAt
   * @return refreshTokenExpiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getRefreshTokenExpiresAt() {
    return refreshTokenExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_REFRESH_TOKEN_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRefreshTokenExpiresAt(@javax.annotation.Nullable OffsetDateTime refreshTokenExpiresAt) {
    this.refreshTokenExpiresAt = refreshTokenExpiresAt;
  }


  public LoginResp sessionExpiresAt(@javax.annotation.Nullable OffsetDateTime sessionExpiresAt) {
    this.sessionExpiresAt = sessionExpiresAt;
    return this;
  }

  /**
   * Get sessionExpiresAt
   * @return sessionExpiresAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SESSION_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getSessionExpiresAt() {
    return sessionExpiresAt;
  }


  @JsonProperty(value = JSON_PROPERTY_SESSION_EXPIRES_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionExpiresAt(@javax.annotation.Nullable OffsetDateTime sessionExpiresAt) {
    this.sessionExpiresAt = sessionExpiresAt;
  }


  public LoginResp account(@javax.annotation.Nullable RespAccount account) {
    this.account = account;
    return this;
  }

  /**
   * Get account
   * @return account
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RespAccount getAccount() {
    return account;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(@javax.annotation.Nullable RespAccount account) {
    this.account = account;
  }


  /**
   * Return true if this Login_Resp object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginResp loginResp = (LoginResp) o;
    return Objects.equals(this.accessToken, loginResp.accessToken) &&
        Objects.equals(this.refreshToken, loginResp.refreshToken) &&
        Objects.equals(this.accessTokenExpiresAt, loginResp.accessTokenExpiresAt) &&
        Objects.equals(this.refreshTokenExpiresAt, loginResp.refreshTokenExpiresAt) &&
        Objects.equals(this.sessionExpiresAt, loginResp.sessionExpiresAt) &&
        Objects.equals(this.account, loginResp.account);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessToken, refreshToken, accessTokenExpiresAt, refreshTokenExpiresAt, sessionExpiresAt, account);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginResp {\n");
    sb.append("    accessToken: ").append(toIndentedString(accessToken)).append("\n");
    sb.append("    refreshToken: ").append(toIndentedString(refreshToken)).append("\n");
    sb.append("    accessTokenExpiresAt: ").append(toIndentedString(accessTokenExpiresAt)).append("\n");
    sb.append("    refreshTokenExpiresAt: ").append(toIndentedString(refreshTokenExpiresAt)).append("\n");
    sb.append("    sessionExpiresAt: ").append(toIndentedString(sessionExpiresAt)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `access_token` to the URL query string
    if (getAccessToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccess_token%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccessToken()))));
    }

    // add `refresh_token` to the URL query string
    if (getRefreshToken() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srefresh_token%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefreshToken()))));
    }

    // add `access_token_expires_at` to the URL query string
    if (getAccessTokenExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%saccess_token_expires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAccessTokenExpiresAt()))));
    }

    // add `refresh_token_expires_at` to the URL query string
    if (getRefreshTokenExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%srefresh_token_expires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRefreshTokenExpiresAt()))));
    }

    // add `session_expires_at` to the URL query string
    if (getSessionExpiresAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssession_expires_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSessionExpiresAt()))));
    }

    // add `account` to the URL query string
    if (getAccount() != null) {
      joiner.add(getAccount().toUrlQueryString(prefix + "account" + suffix));
    }

    return joiner.toString();
  }
}

