/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.bass.bbs.model.RespAccountBasic;
import com.bass.bbs.model.RespAccountContact;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * RespAccount
 */
@JsonPropertyOrder({
  RespAccount.JSON_PROPERTY_BASIC,
  RespAccount.JSON_PROPERTY_CONTACT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class RespAccount {
  public static final String JSON_PROPERTY_BASIC = "basic";
  @javax.annotation.Nullable
  private RespAccountBasic basic;

  public static final String JSON_PROPERTY_CONTACT = "contact";
  @javax.annotation.Nullable
  private RespAccountContact contact;

  public RespAccount() { 
  }

  public RespAccount basic(@javax.annotation.Nullable RespAccountBasic basic) {
    this.basic = basic;
    return this;
  }

  /**
   * Get basic
   * @return basic
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BASIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RespAccountBasic getBasic() {
    return basic;
  }


  @JsonProperty(value = JSON_PROPERTY_BASIC, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBasic(@javax.annotation.Nullable RespAccountBasic basic) {
    this.basic = basic;
  }


  public RespAccount contact(@javax.annotation.Nullable RespAccountContact contact) {
    this.contact = contact;
    return this;
  }

  /**
   * Get contact
   * @return contact
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RespAccountContact getContact() {
    return contact;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTACT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContact(@javax.annotation.Nullable RespAccountContact contact) {
    this.contact = contact;
  }


  /**
   * Return true if this Resp_Account object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RespAccount respAccount = (RespAccount) o;
    return Objects.equals(this.basic, respAccount.basic) &&
        Objects.equals(this.contact, respAccount.contact);
  }

  @Override
  public int hashCode() {
    return Objects.hash(basic, contact);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RespAccount {\n");
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `basic` to the URL query string
    if (getBasic() != null) {
      joiner.add(getBasic().toUrlQueryString(prefix + "basic" + suffix));
    }

    // add `contact` to the URL query string
    if (getContact() != null) {
      joiner.add(getContact().toUrlQueryString(prefix + "contact" + suffix));
    }

    return joiner.toString();
  }
}

