syntax = "proto3";

package common.api.app.game_idle_bff.v1;

import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "common/proto/gen/game_idle_bff/v1;v1";

// AuthService 提供摸鱼放置前台认证入口。
service AuthService {
  // 注册账号。
  rpc Register(RegisterAccount.Req) returns (RegisterAccount.Resp) {
    option (google.api.http) = {
      post: "/v1/game-idle/auth/register"
      body: "*"
    };
  }

  // 登录账号。
  rpc Login(LoginAccount.Req) returns (LoginAccount.Resp) {
    option (google.api.http) = {
      post: "/v1/game-idle/auth/login"
      body: "*"
    };
  }
}

message RegisterAccount {
  message Req {
    string email = 1; // 邮箱
    string password = 2; // 账号密码
    option (gnostic.openapi.v3.schema) = {
      required: "email"
      required: "password"
    };
  }

  message Resp {}
}

message LoginAccount {
  message Req {
    string email = 1; // 邮箱
    string password = 2; // 账号密码
    option (gnostic.openapi.v3.schema) = {
      required: "email"
      required: "password"
    };
  }

  message Resp {
    string access_token = 1; // access token
    string refresh_token = 2; // refresh token
    google.protobuf.Timestamp access_token_expires_at = 3; // access token 过期时间
    google.protobuf.Timestamp refresh_token_expires_at = 4; // refresh token 过期时间
    google.protobuf.Timestamp session_expires_at = 5; // session 过期时间
    int64 user_id = 6; // 当前账号 ID
    string name = 7; // 账号名
    string nickname = 8; // 昵称
  }
}
