version: '3.9'

name: bass-application

networks:
  bass:
    driver: bridge
    external: true

services:
  treble:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/treble:latest
    container_name: treble
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "2324:2324"
    networks:
      - bass

  gateway:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/gateway:latest
    container_name: gateway
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - bass

  infra:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/infra:latest
    container_name: infra
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8001:8000"
      - "9001:9000"
    networks:
      - bass

  user:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/user:latest
    container_name: user
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8002:8000"
      - "9002:9000"
    networks:
      - bass

  content:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/content:latest
    container_name: content
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8003:8000"
      - "9003:9000"
    networks:
      - bass

  notify:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/notify:latest
    container_name: notify
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8004:8000"
      - "9004:9000"
    networks:
      - bass

  im:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/im:latest
    container_name: im
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8005:8000"
      - "9005:9000"
    networks:
      - bass

  signal:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/signal:latest
    container_name: signal
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8006:8000"
      - "9006:9000"
    networks:
      - bass

  connector:
    image: registry.cn-hangzhou.aliyuncs.com/docker-cooooing/connector:latest
    container_name: connector
    restart: on-failure:3
    env_file:
      - .env
    ports:
      - "8007:8000"
      - "9007:9000"
    networks:
      - bass
