syntax = "proto3";
package kratos.api.bootstrap;

option go_package = "signal/internal/conf/bootstrap;bootstrap";

import "google/protobuf/duration.proto";

message Bootstrap {
  string name = 1;
  string version = 2;
  string mode = 3;

  Registry registry = 4;
  Config config = 5;
  Log log = 6;
}

message Registry {
  message Etcd {
    repeated string endpoints = 1;
    string username = 2;
    string password = 3;
    google.protobuf.Duration timeout = 4;
    google.protobuf.Duration auto_sync_interval = 5;
    google.protobuf.Duration dial_keep_alive_time = 6;
    google.protobuf.Duration dial_keep_alive_timeout = 7;
    bool permit_without_leader = 8;
  }
  Etcd etcd = 1;
}

message Config {
  string etcd = 1;
}

message Log {
  bool enable = 1;
  string level = 2; // debug, info, warn, error, fatal, panic
  string file = 3;
}