/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.bass.bbs.model.ArticleListItem;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.bass.bbs.ApiClient;
/**
 * ArticleViewHistoryItem
 */
@JsonPropertyOrder({
  ArticleViewHistoryItem.JSON_PROPERTY_ARTICLE,
  ArticleViewHistoryItem.JSON_PROPERTY_VIEWED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.22.0")
public class ArticleViewHistoryItem {
  public static final String JSON_PROPERTY_ARTICLE = "article";
  @javax.annotation.Nullable
  private ArticleListItem article;

  public static final String JSON_PROPERTY_VIEWED_AT = "viewed_at";
  @javax.annotation.Nullable
  private OffsetDateTime viewedAt;

  public ArticleViewHistoryItem() { 
  }

  public ArticleViewHistoryItem article(@javax.annotation.Nullable ArticleListItem article) {
    this.article = article;
    return this;
  }

  /**
   * Get article
   * @return article
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARTICLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ArticleListItem getArticle() {
    return article;
  }


  @JsonProperty(value = JSON_PROPERTY_ARTICLE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArticle(@javax.annotation.Nullable ArticleListItem article) {
    this.article = article;
  }


  public ArticleViewHistoryItem viewedAt(@javax.annotation.Nullable OffsetDateTime viewedAt) {
    this.viewedAt = viewedAt;
    return this;
  }

  /**
   * Get viewedAt
   * @return viewedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VIEWED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getViewedAt() {
    return viewedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_VIEWED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setViewedAt(@javax.annotation.Nullable OffsetDateTime viewedAt) {
    this.viewedAt = viewedAt;
  }


  /**
   * Return true if this ArticleViewHistoryItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArticleViewHistoryItem articleViewHistoryItem = (ArticleViewHistoryItem) o;
    return Objects.equals(this.article, articleViewHistoryItem.article) &&
        Objects.equals(this.viewedAt, articleViewHistoryItem.viewedAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(article, viewedAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArticleViewHistoryItem {\n");
    sb.append("    article: ").append(toIndentedString(article)).append("\n");
    sb.append("    viewedAt: ").append(toIndentedString(viewedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `article` to the URL query string
    if (getArticle() != null) {
      joiner.add(getArticle().toUrlQueryString(prefix + "article" + suffix));
    }

    // add `viewed_at` to the URL query string
    if (getViewedAt() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sviewed_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getViewedAt()))));
    }

    return joiner.toString();
  }
}

