package constant

const (
	LogFieldErr            = "error"
	LogFieldKind           = "kind"
	LogFieldTraceID        = "trace_id"
	LogFieldSpanID         = "span_id"
	LogFieldRequestID      = "request_id"
	LogFieldUserID         = "user_id"
	LogFieldClientIP       = "client_ip"
	LogFieldOperation      = "operation"
	LogFieldTransport      = "transport"
	LogFieldTarget         = "target"
	LogFieldDirection      = "direction"
	LogFieldSubject        = "subject"
	LogFieldQueue          = "queue"
	LogFieldStatus         = "status"
	LogFieldStatusCode     = "status_code"
	LogFieldLatencyMS      = "latency_ms"
	LogFieldSQL            = "sql"
	LogFieldArgsCount      = "args_count"
	LogFieldTxID           = "tx_id"
	LogFieldEventID        = "event_id"
	LogFieldEventType      = "event_type"
	LogFieldService        = "service"
	LogFieldServiceName    = "service.name"
	LogFieldServiceVersion = "service.version"
	LogFieldSource         = "source"
	LogFieldCount          = "count"
	LogFieldLastError      = "last_error"
	LogFieldAddress        = "address"
	LogFieldDatacenter     = "datacenter"
	LogFieldDriver         = "driver"
	LogFieldDB             = "db"
	LogFieldPath           = "path"
	LogFieldFile           = "file"
	LogFieldLine           = "line"
	LogFieldUnexpected     = "unexpected"
	LogFieldTaskID         = "task_id"
	LogFieldTaskName       = "task_name"
	LogFieldTaskVersion    = "task_version"
	LogFieldExecutionID    = "execution_id"
	LogFieldReason         = "reason"

	LogFieldPassword      = "password"
	LogFieldToken         = "token"
	LogFieldSecret        = "secret"
	LogFieldAuthorization = "authorization"
	LogFieldCookie        = "cookie"

	LogKindServer   = "server"
	LogKindClient   = "client"
	LogKindSQL      = "sql"
	LogKindMessage  = "message"
	LogKindSystem   = "system"
	LogKindConsul   = "consul"
	LogKindRedis    = "redis"
	LogKindDatabase = "database"
	LogKindAsynq    = "asynq"
	LogKindLark     = "lark"
)
