syntax = "proto3";

package common.api.app.user.v1;

import "common/common.proto";
import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

service AccountService {
  rpc Get(GetAccount.Req) returns (GetAccount.Resp) {} // 查询单个账号。
  rpc List(ListAccounts.Req) returns (ListAccounts.Resp) {} // 查询账号列表。
  rpc Map(MapAccounts.Req) returns (MapAccounts.Resp) {} // 查询账号映射。
  rpc UpdateProfile(UpdateProfileAccount.Req) returns (UpdateProfileAccount.Resp) {} // 更新账号展示资料。
  rpc Avatar(AvatarAccount.Req) returns (.common.api.app.common.ImageResp) {} // 生成默认账号头像。
}

message GetAccount {
  message Req {
    int64 user_id = 1;
  }
  message Resp {
    message Account {
      AccountBasic basic = 1;
      AccountContact contact = 2;
    }

    message AccountBasic {
      int64 id = 1;
      string name = 2;
      optional string nickname = 3;
      optional string url = 4;
      optional string avatar_url = 5;
      optional string introduction = 6;
      MBTI mbti = 7;
      AccountStatus status = 8;
      optional int32 follow_count = 10;
      optional int32 follower_count = 11;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }

    message AccountContact {
      int64 user_id = 1;
      optional string email = 2;
      optional string phone = 3;
    }
    Account account = 1;
  }
}

message ListAccounts {
  message Req {
    message AccountQuery {
      repeated int64 user_ids = 1;
    }
    AccountQuery query = 1;
  }
  message Resp {
    message Account {
      AccountBasic basic = 1;
      AccountContact contact = 2;
    }

    message AccountBasic {
      int64 id = 1;
      string name = 2;
      optional string nickname = 3;
      optional string url = 4;
      optional string avatar_url = 5;
      optional string introduction = 6;
      MBTI mbti = 7;
      AccountStatus status = 8;
      optional int32 follow_count = 10;
      optional int32 follower_count = 11;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }

    message AccountContact {
      int64 user_id = 1;
      optional string email = 2;
      optional string phone = 3;
    }
    repeated Account rows = 1;
  }
}

message MapAccounts {
  message Req {
    message AccountQuery {
      repeated int64 user_ids = 1;
    }
    AccountQuery query = 1;
  }
  message Resp {
    message Account {
      AccountBasic basic = 1;
      AccountContact contact = 2;
    }

    message AccountBasic {
      int64 id = 1;
      string name = 2;
      optional string nickname = 3;
      optional string url = 4;
      optional string avatar_url = 5;
      optional string introduction = 6;
      MBTI mbti = 7;
      AccountStatus status = 8;
      optional int32 follow_count = 10;
      optional int32 follower_count = 11;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }

    message AccountContact {
      int64 user_id = 1;
      optional string email = 2;
      optional string phone = 3;
    }
    map<int64, Account> accounts = 1;
  }
}

message UpdateProfileAccount {
  message Req {
    int64 user_id = 1;
    optional string avatar_url = 2;
    optional string nickname = 3;
    optional string url = 4;
    optional string introduction = 5;
    optional MBTI mbti = 6;
  }
  message Resp {
    message AccountBasic {
      int64 id = 1;
      string name = 2;
      optional string nickname = 3;
      optional string url = 4;
      optional string avatar_url = 5;
      optional string introduction = 6;
      MBTI mbti = 7;
      AccountStatus status = 8;
      optional int32 follow_count = 10;
      optional int32 follower_count = 11;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }
    AccountBasic account = 1;
  }
}

message AvatarAccount {
  message Req {
    string name = 1;
  }
}
