syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum/account.proto";
import "user/v1/enum/auth.proto";
import "user/v1/enum/relation.proto";

option go_package = "common/proto/gen/user/v1;v1";

service AuthService {
  rpc StartEmailRegistration(StartEmailRegistration.Req) returns (StartEmailRegistration.Resp) {} // 使用邮箱发起账号注册，成功后返回验证码令牌。
  rpc VerifyEmailRegistration(VerifyEmailRegistration.Req) returns (VerifyEmailRegistration.Resp) {} // 校验邮箱注册验证码并创建账号。
  rpc StartPhoneRegistration(StartPhoneRegistration.Req) returns (StartPhoneRegistration.Resp) {} // 使用手机号发起账号注册，成功后返回验证码令牌。
  rpc VerifyPhoneRegistration(VerifyPhoneRegistration.Req) returns (VerifyPhoneRegistration.Resp) {} // 校验手机号注册验证码并创建账号。
  rpc LoginByPassword(LoginByPassword.Req) returns (LoginByPassword.Resp) {} // 使用账号名、邮箱或手机号加密码登录。
  rpc Logout(Logout.Req) returns (Logout.Resp) {} // 登出账号并清理令牌。
  rpc ParseToken(ParseToken.Req) returns (ParseToken.Resp) {} // 解析登录令牌。
}

message StartEmailRegistration {
  message Req {
    string email = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Resp {
    string code_token = 1;
    string code = 2;
  }
}

message VerifyEmailRegistration {
  message Req {
    string code = 1;
    string code_token = 2;
  }
  message Resp {}
}

message StartPhoneRegistration {
  message Req {
    string phone = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Resp {
    string code_token = 1;
    string code = 2;
  }
}

message VerifyPhoneRegistration {
  message Req {
    string code = 1;
    string code_token = 2;
  }
  message Resp {}
}

message LoginByPassword {
  message Req {
    string account = 1;
    string password = 2;
    string ip = 3;
    string country = 4;
    string country_code = 5;
    string province = 6;
    string city = 7;
    string isp = 8;
    string user_agent = 9;
    string device_id = 10;
    string platform = 11;
    string request_id = 12;
  }
  message Resp {
    message Account {
      AccountBasic basic = 1;
      AccountContact contact = 2;
    }

    message AccountBasic {
      int64 id = 1;
      string name = 2;
      optional string nickname = 3;
      optional string url = 4;
      optional string avatar_url = 5;
      optional string introduction = 6;
      MBTI mbti = 7;
      AccountStatus status = 8;
      optional int32 follow_count = 10;
      optional int32 follower_count = 11;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }

    message AccountContact {
      int64 user_id = 1;
      optional string email = 2;
      optional string phone = 3;
    }
    string token = 1;
    Account account = 2;
  }
}

message Logout {
  message Req {
    string token = 1;
  }
  message Resp {}
}

message ParseToken {
  message Req {
    string token = 1;
  }
  message Resp {
    message TokenUser {
      int64 id = 1;
      string name = 2;
      string nickname = 3;
      common.enums.Language language = 4;
      string timezone = 5;
    }
    TokenUser user = 1;
  }
}
