syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

service LocationService {
  rpc Get(GetLocation.Req) returns (GetLocation.Resp) {} // 获取账号地理资料。
  rpc Upsert(UpsertLocation.Req) returns (UpsertLocation.Resp) {} // 更新账号地理资料；缺省扩展表使用 upsert 创建。
}

message GetLocation {
  message Req {
    int64 user_id = 1;
  }
  message Resp {
    message Location {
      int64 user_id = 1;
      optional string country = 2;
      optional string province = 3;
      optional string city = 4;
    }
    Location location = 1;
  }
}

message UpsertLocation {
  message Req {
    int64 user_id = 1;
    optional string country = 2;
    optional string province = 3;
    optional string city = 4;
  }
  message Resp {
    message Location {
      int64 user_id = 1;
      optional string country = 2;
      optional string province = 3;
      optional string city = 4;
    }
    Location location = 1;
  }
}
