syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

message AccountBasic {
  int64 id = 1;
  string name = 2;
  optional string nickname = 3;
  optional string url = 4;
  optional string avatar_url = 5;
  optional string introduction = 6;
  MBTI mbti = 7;
  AccountStatus status = 8;
  optional int32 follow_count = 10;
  optional int32 follower_count = 11;
  google.protobuf.Timestamp created_at = 1000;
  google.protobuf.Timestamp updated_at = 1001;
}

message AccountContact {
  int64 user_id = 1;
  optional string email = 2;
  optional string phone = 3;
}

message Account {
  AccountBasic basic = 1;
  AccountContact contact = 2;
}

message Preferences {
  int64 user_id = 1;
  optional string timezone = 3;
  optional string theme = 4;
  optional string mobile_theme = 5;
  common.enums.Language language = 8;
}

message PrivacySetting {
  int64 user_id = 1;
  optional bool public_points = 2;
  optional bool public_followers = 3;
  optional bool public_articles = 4;
  optional bool public_comments = 5;
  optional bool public_online_status = 6;
  optional bool public_location = 7;
}

message Location {
  int64 user_id = 1;
  optional string country = 2;
  optional string province = 3;
  optional string city = 4;
}

message Totp {
  int64 user_id = 1;
  bool enable = 2;
  google.protobuf.Timestamp enable_time = 3;
}

message CheckinRecord {
  int64 id = 1;
  int64 user_id = 2;
  google.protobuf.Timestamp date = 3;
  optional int32 online_minutes = 4;
  optional int32 activity = 5;
  bool checked = 6;
}

message CheckinStat {
  int64 user_id = 1;
  optional int32 total_online_minutes = 2;
  optional int32 current_streak = 3;
  optional int32 longest_streak = 4;
}

message LoginLog {
  int64 id = 1;
  optional int64 user_id = 2;
  LoginMethod login_method = 4;
  LoginStatus status = 5;
  optional string ip = 7;
  optional string country = 8;
  optional string country_code = 9;
  optional string province = 10;
  optional string city = 11;
  optional string isp = 12;
  optional string user_agent = 13;
  optional string device_id = 14;
  google.protobuf.Timestamp created_at = 1000;
}

message Relation {
  int64 id = 1;
  RelationType type = 2;
  int64 actor_id = 3;
  int64 target_id = 4;
  google.protobuf.Timestamp created_at = 1000;
  google.protobuf.Timestamp updated_at = 1001;
}

message RelationStatus {
  int64 target_id = 1;
  bool following = 2;
  bool followed_by = 3;
  bool blocking = 4;
  bool blocked_by = 5;
}
