syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

service PreferencesService {
  rpc Get(GetPreferences.Request) returns (GetPreferences.Response) {} // 获取账号偏好设置，缺省时返回默认设置。
  rpc Update(UpdatePreferences.Request) returns (UpdatePreferences.Response) {} // 更新账号偏好设置；缺省扩展表使用 upsert 创建。
}

message GetPreferences {
  message Request {
    int64 user_id = 1;
  }
  message Response {

    message Preferences {
      int64 user_id = 1;
      optional string timezone = 3;
      optional string theme = 4;
      optional string mobile_theme = 5;
      common.enums.Language language = 8;
    }
    Preferences preferences = 1;
  }
}

message UpdatePreferences {
  message Request {
    int64 user_id = 1;
    optional string timezone = 2;
    optional string theme = 3;
    optional string mobile_theme = 4;
    optional common.enums.Language language = 7;
  }
  message Response {

    message Preferences {
      int64 user_id = 1;
      optional string timezone = 3;
      optional string theme = 4;
      optional string mobile_theme = 5;
      common.enums.Language language = 8;
    }
    Preferences preferences = 1;
  }
}
