syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

service PrivacySettingService {
  rpc Get(GetPrivacySetting.Req) returns (GetPrivacySetting.Resp) {} // 获取账号隐私设置，缺省时返回默认设置。
  rpc Update(UpdatePrivacySetting.Req) returns (UpdatePrivacySetting.Resp) {} // 更新账号隐私设置；缺省扩展表使用 upsert 创建。
}

message GetPrivacySetting {
  message Req {
    int64 user_id = 1;
  }
  message Resp {
    message PrivacySetting {
      int64 user_id = 1;
      optional bool public_points = 2;
      optional bool public_followers = 3;
      optional bool public_articles = 4;
      optional bool public_comments = 5;
      optional bool public_online_status = 6;
      optional bool public_location = 7;
    }
    PrivacySetting privacy_setting = 1;
  }
}

message UpdatePrivacySetting {
  message Req {
    int64 user_id = 1;
    optional bool public_points = 2;
    optional bool public_followers = 3;
    optional bool public_articles = 4;
    optional bool public_comments = 5;
    optional bool public_online_status = 6;
    optional bool public_location = 7;
  }
  message Resp {
    message PrivacySetting {
      int64 user_id = 1;
      optional bool public_points = 2;
      optional bool public_followers = 3;
      optional bool public_articles = 4;
      optional bool public_comments = 5;
      optional bool public_online_status = 6;
      optional bool public_location = 7;
    }
    PrivacySetting privacy_setting = 1;
  }
}
