syntax = "proto3";

package common.api.app.user.v1;

import "common/common.proto";
import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum.proto";

option go_package = "common/proto/gen/user/v1;v1";

service RelationService {
  rpc Follow(FollowRelation.Request) returns (FollowRelation.Response) {} // 账号关注目标账号，并同步维护双方关注统计。
  rpc Unfollow(UnfollowRelation.Request) returns (UnfollowRelation.Response) {} // 账号取消关注目标账号，并同步维护双方关注统计。
  rpc Block(BlockRelation.Request) returns (BlockRelation.Response) {} // 账号拉黑目标账号，并同步维护双方拉黑统计。
  rpc Unblock(UnblockRelation.Request) returns (UnblockRelation.Response) {} // 账号取消拉黑目标账号，并同步维护双方拉黑统计。
  rpc ListFollowing(ListFollowingRelations.Request) returns (ListFollowingRelations.Response) {} // 查询账号关注的账号列表。
  rpc ListFollowers(ListFollowersRelations.Request) returns (ListFollowersRelations.Response) {} // 查询账号的粉丝关系列表。
  rpc ListBlocked(ListBlockedRelations.Request) returns (ListBlockedRelations.Response) {} // 查询账号拉黑的账号列表。
  rpc MapStatus(MapRelationStatuses.Request) returns (MapRelationStatuses.Response) {} // 查询账号与多个目标账号之间的关系状态映射。
}

message FollowRelation {
  message Request {
    int64 actor_id = 1;
    int64 target_id = 2;
  }
  message Response {}
}

message UnfollowRelation {
  message Request {
    int64 actor_id = 1;
    int64 target_id = 2;
  }
  message Response {}
}

message BlockRelation {
  message Request {
    int64 actor_id = 1;
    int64 target_id = 2;
  }
  message Response {}
}

message UnblockRelation {
  message Request {
    int64 actor_id = 1;
    int64 target_id = 2;
  }
  message Response {}
}

message ListFollowingRelations {
  message Request {
    .common.api.app.common.PageRequest page = 1;
    int64 user_id = 2;
  }
  message Response {

    message Relation {
      int64 id = 1;
      RelationType type = 2;
      int64 actor_id = 3;
      int64 target_id = 4;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }
    .common.api.app.common.PageResponse page = 1;
    repeated Relation rows = 2;
  }
}

message ListFollowersRelations {
  message Request {
    .common.api.app.common.PageRequest page = 1;
    int64 user_id = 2;
  }
  message Response {

    message Relation {
      int64 id = 1;
      RelationType type = 2;
      int64 actor_id = 3;
      int64 target_id = 4;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }
    .common.api.app.common.PageResponse page = 1;
    repeated Relation rows = 2;
  }
}

message ListBlockedRelations {
  message Request {
    .common.api.app.common.PageRequest page = 1;
    int64 user_id = 2;
  }
  message Response {

    message Relation {
      int64 id = 1;
      RelationType type = 2;
      int64 actor_id = 3;
      int64 target_id = 4;
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
    }
    .common.api.app.common.PageResponse page = 1;
    repeated Relation rows = 2;
  }
}

message MapRelationStatuses {
  message Request {
    int64 actor_id = 1;
    repeated int64 target_ids = 2;
  }
  message Response {

    message RelationStatus {
      int64 target_id = 1;
      bool following = 2;
      bool followed_by = 3;
      bool blocking = 4;
      bool blocked_by = 5;
    }
    map<int64, RelationStatus> statuses = 1;
  }
}
