syntax = "proto3";

package common.api.app.user.v1;

import "common/enums/language.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/enum/account.proto";
import "user/v1/enum/auth.proto";
import "user/v1/enum/relation.proto";

option go_package = "common/proto/gen/user/v1;v1";

service TotpService {
  rpc Validate(ValidateTotp.Req) returns (ValidateTotp.Resp) {} // 校验账号的 TOTP 验证码。
  rpc BeginEnable(BeginEnableTotp.Req) returns (BeginEnableTotp.Resp) {} // 开始启用 TOTP，生成临时密钥和二维码图片。
  rpc ConfirmEnable(ConfirmEnableTotp.Req) returns (ConfirmEnableTotp.Resp) {} // 确认 TOTP 验证码并正式启用 TOTP。
  rpc Disable(DisableTotp.Req) returns (DisableTotp.Resp) {} // 校验 TOTP 验证码并关闭 TOTP。
  rpc Get(GetTotp.Req) returns (GetTotp.Resp) {} // 获取账号 TOTP 状态。
}

message ValidateTotp {
  message Req {
    int64 user_id = 1;
    string code = 2;
  }
  message Resp {
    bool verified = 1;
  }
}

message BeginEnableTotp {
  message Req {
    int64 user_id = 1;
    string account_name = 2;
  }
  message Resp {
    string url = 1;
    bytes qr_code = 2;
  }
}

message ConfirmEnableTotp {
  message Req {
    int64 user_id = 1;
    string code = 2;
  }
  message Resp {}
}

message DisableTotp {
  message Req {
    int64 user_id = 1;
    string code = 2;
  }
  message Resp {}
}

message GetTotp {
  message Req {
    int64 user_id = 1;
  }
  message Resp {
    message Totp {
      int64 user_id = 1;
      bool enable = 2;
      google.protobuf.Timestamp enable_time = 3;
    }
    Totp totp = 1;
  }
}
