apiVersion: v1
kind: Secret
metadata:
  name: woodpecker-forge-secret
  namespace: cicd
type: Opaque
stringData:
  # GitHub example. Create an OAuth App and set callback URL to:
  # http://127.0.0.1:31980/authorize
  WOODPECKER_GITHUB: "true"
  WOODPECKER_GITHUB_CLIENT: "replace-with-oauth-client-id"
  WOODPECKER_GITHUB_SECRET: "replace-with-oauth-client-secret"


  # Optional: use this if you expose Woodpecker through a tunnel/domain.
  # WOODPECKER_HOST: "https://ci.example.com"
