syntax = "proto3";

package common.api.app.im.v1;

import "common/common.proto";
import "google/protobuf/timestamp.proto";
import "im/v1/enum/chat_group.proto";
import "im/v1/enum/message.proto";
import "user/v1/enum/account_status.proto";
import "user/v1/enum/mbti.proto";

option go_package = "common/proto/gen/im/v1;v1";

// IMChatMessageService 提供消息能力
service IMChatMessageService {
  // 发送消息
  rpc Send(SendChatMessage.Req) returns (SendChatMessage.Resp) {}
  // 撤回消息
  rpc Revoke(RevokeChatMessage.Req) returns (RevokeChatMessage.Resp) {}
  // 查询消息列表
  rpc List(ListChatMessages.Req) returns (ListChatMessages.Resp) {}
}

message SendChatMessage {
  message Req {
    int64 receiver_id = 1; // 接收者 ID
    ReceiverType receiver_type = 2; // 接收者类型
    int64 user_id = 3; // 用户 ID
    MessageType type = 5; // 消息类型
    string content = 6; // 内容
  }
  message Resp {}
}

message RevokeChatMessage {
  message Req {
    int64 id = 1; // 消息 ID
    int64 user_id = 2; // 用户 ID
  }
  message Resp {}
}

message ListChatMessages {
  message Req {
    message ChatMessageQueryParams {
      repeated int64 ids = 2; // 消息 ID 列表
      int64 session_id = 3; // 会话 ID
      int64 sender_id = 4; // 发送者 ID
    }
    .common.api.app.common.PageReq page = 1; // 分页参数
    ChatMessageQueryParams query = 2; // 查询参数
  }
  message Resp {
    message AccountBasic {
      int64 id = 1; // 账号 ID
      string name = 2; // 账号名
      optional string nickname = 3; // 昵称
      optional string url = 4; // 个人主页 URL
      optional string avatar_url = 5; // 头像 URL
      optional string introduction = 6; // 个人简介
      .common.api.app.user.v1.MBTI mbti = 7; // MBTI 类型
      .common.api.app.user.v1.AccountStatus status = 8; // 账号状态
      optional int32 follow_count = 10; // 关注数量
      optional int32 follower_count = 11; // 粉丝数量
      google.protobuf.Timestamp created_at = 1000; // 创建时间
      google.protobuf.Timestamp updated_at = 1001; // 更新时间
    }
    message ChatGroup {
      google.protobuf.Timestamp created_at = 1000; // 创建时间
      google.protobuf.Timestamp updated_at = 1001; // 更新时间
      int64 id = 1; // 群组 ID
      string name = 2; // 群名称
      optional int64 avatar_asset_id = 3; // 群头像资源 ID
      optional string introduction = 4; // 群简介
      ChatGroupStatus status = 5; // 群组状态
      AccountBasic owner = 6; // 群主信息
      uint32 member_count = 7; // 成员数量
      ChatMessage last_message = 9; // 最后一条消息
    }
    message ChatMessage {
      google.protobuf.Timestamp created_at = 1000; // 创建时间
      google.protobuf.Timestamp updated_at = 1001; // 更新时间
      optional int64 created_by = 1002; // 创建人
      optional int64 updated_by = 1003; // 更新人
      int64 id = 1; // 消息 ID
      AccountBasic sender = 2; // 发送者
      int64 receiver_user_id = 3; // 接收用户 ID
      AccountBasic receiver_user = 4; // 接收用户
      int64 receiver_group_id = 5; // 接收群组 ID
      ChatGroup receiver_group = 6; // 接收群组
      MessageType type = 7; // 消息类型
      string content = 8; // 内容
      MessageStatus status = 9; // 消息状态
    }
    .common.api.app.common.PageResp page = 1; // 分页信息
    repeated ChatMessage rows = 2; // 消息列表
  }
}
