syntax = "proto3";

package common.api.app.im.v1;

import "google/protobuf/timestamp.proto";
import "im/v1/enum.proto";
import "user/v1/model.proto";

option go_package = "common/proto/gen/im/v1;v1";

// 群组
message ChatGroup {
  google.protobuf.Timestamp created_at = 1000; // 创建时间
  google.protobuf.Timestamp updated_at = 1001; // 更新时间
  int64 id = 1; // 主键
  string name = 2; // 群名称
  optional string avatar = 3; // 群头像
  optional string introduction = 4; // 群简介
  ChatGroupStatus status = 5; // 群状态
  user.v1.AccountBasic owner = 6; // 群主信息
  uint32 member_count = 7; // 群成员数
  ChatMessage last_message = 9; // 最后一条消息
}

message ChatGroupMember {
  google.protobuf.Timestamp created_at = 1000; // 创建时间
  google.protobuf.Timestamp updated_at = 1001; // 创建时间
  int64 id = 1; // 主键
  int64 group_id = 2; // 群组
  user.v1.AccountBasic member = 3; // 成员
  optional string nickname = 4; // 群内昵称
  ChatGroupMemberRole role = 5; // 角色
  google.protobuf.Timestamp mute_end_at = 6; // 禁言结束时间
}

message ChatSession {
  google.protobuf.Timestamp created_at = 1000; // 创建时间
  google.protobuf.Timestamp updated_at = 1001; // 创建时间
  int64 id = 1; // 主键
  int64 relation_id = 2; // 私聊
  int64 group_id = 3; // 群组
  bool is_muted = 4; // 是否免打扰
  bool is_pinned = 5; // 是否置顶
  int64 last_read_message_id = 6; // 已读最后一条消息 ID
  uint32 unread_count = 7; // 未读数
}

// 消息
message ChatMessage {
  google.protobuf.Timestamp created_at = 1000; // 创建时间
  google.protobuf.Timestamp updated_at = 1001; // 更新时间
  optional int64 created_by = 1002; // 创建人
  optional int64 updated_by = 1003; // 更新人
  int64 id = 1; // 主键
  user.v1.AccountBasic sender = 2; // 发送者
  int64 receiver_user_id = 3; // 接收用户 ID
  user.v1.AccountBasic receiver_user = 4; // 接收用户
  int64 receiver_group_id = 5; // 接收群组 ID
  ChatGroup receiver_group = 6; // 接收群组
  MessageType type = 7; // 消息类型
  string content = 8; // 内容
  MessageStatus status = 9; // 状态
}

message ChatSessionQueryParams {
  repeated int64 ids = 2; // 主键
}

message ChatMessageQueryParams {
  repeated int64 ids = 2; // 主键
  int64 session_id = 3; // 会话id
  int64 sender_id = 4; // 发送者 ID
}

message ChatGroupQueryParams {
  repeated int64 ids = 2; // 主键
  repeated string uuids = 3; // UUID 列表
  optional int32 notification_type = 5; // 通知类型
  repeated int64 sender_ids = 6; // 发送者ID
  optional ChatGroupStatus status = 8; // 状态
}
