syntax = "proto3";

package common.api.app.platform.v1;

option go_package = "common/proto/gen/platform/v1;v1";

// IP 解析服务。
service PlatformIpResolutionService {
  // 解析 IP 地理信息。
  rpc ResolveIp(ResolveIp.Request) returns (ResolveIp.Response) {}
}

message ResolveIp {
  message Request {
    // IP 地址。
    string ip = 1;
  }
  message Response {
    // 国家。
    string country = 1;
    // 省份。
    string province = 2;
    // 城市。
    string city = 3;
    // 运营商。
    string isp = 4;
    // 国家代码。
    string country_code = 5;
  }
}

