syntax = "proto3";

package common.api.app.platform.v1;

import "common/common.proto";
import "platform/v1/oss_model.proto";

option go_package = "common/proto/gen/platform/v1;v1";

// OSS 服务。
service PlatformOssService {
  // 获取上传凭证。
  rpc GetUploadToken(GetUploadTokenOss.Request) returns (GetUploadTokenOss.Reply) {}
  // 审核对象。
  rpc Audit(AuditOss.Request) returns (AuditOss.Reply) {}
  // 查询对象列表。
  rpc List(ListOss.Request) returns (ListOss.Reply) {}
  // 七牛上传回调。
  rpc QiniuUploadCallback(QiniuUploadCallbackOss.Request) returns (QiniuUploadCallbackOss.Reply) {}
  // 七牛增量审核回调。
  rpc QiniuIncrementAuditCallback(QiniuIncrementAuditCallbackOss.Request) returns (QiniuIncrementAuditCallbackOss.Reply) {}
}

message GetUploadTokenOss {
  message Request {
    int64 user_id = 1;
    string user_name = 2;
    int32 num = 3;
  }
  message Reply {
    repeated UploadToken upload_token = 1;
  }
}

message AuditOss {
  message Request {
    int64 user_id = 1;
    string user_name = 2;
    string key = 3;
    bool status = 4;
    optional string reason = 5;
  }
  message Reply {}
}

message ListOss {
  message Request {
    common.PageRequest page = 1;
    OssQueryParams query = 2;
  }
  message Reply {
    common.PageReply page = 1;
    repeated Oss rows = 2;
  }
}

message QiniuUploadCallbackOss {
  message Request {
    string key = 1;
    string hash = 2;
    int64 size = 3;
    string bucket = 4;
    string name = 5;
    string mime_type = 6;
    int64 upload_by = 7;
    string upload_by_name = 8;
  }
  message Reply {}
}

message QiniuIncrementAuditCallbackOss {
  message Request {
    string id = 1;
    string pipeline = 2;
    int32 code = 3;
    string desc = 4;
    string reqid = 5;
    string inputBucket = 6;
    string inputKey = 7;
    repeated Item items = 8;
  }
  message Reply {}
}

