syntax = "proto3";

package common.api.app.platform.v1;

import "common/common.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";
import "platform/v1/enum/object_storage.proto";

option go_package = "common/proto/gen/platform/v1;v1";

// PlatformOssService 提供平台对象存储能力
service PlatformOssService {
  // 获取上传凭证
  rpc GetUploadToken(GetUploadTokenOss.Req) returns (GetUploadTokenOss.Resp) {}
  // 直接上传对象
  rpc Upload(UploadOss.Req) returns (UploadOss.Resp) {}
  // 流式上传对象
  rpc StreamUpload(stream StreamUploadOss.Req) returns (StreamUploadOss.Resp) {}
  // 直接下载对象
  rpc Download(DownloadOss.Req) returns (DownloadOss.Resp) {}
  // 流式下载对象
  rpc StreamDownload(StreamDownloadOss.Req) returns (stream StreamDownloadOss.Resp) {}
  // 审核对象
  rpc Audit(AuditOss.Req) returns (AuditOss.Resp) {}
  // 查询对象列表
  rpc List(ListOss.Req) returns (ListOss.Resp) {}
  // 批量解析资源访问地址
  rpc ResolveAssets(ResolveAssetsOss.Req) returns (ResolveAssetsOss.Resp) {}
  // 校验资源是否可绑定
  rpc ValidateAsset(ValidateAssetOss.Req) returns (ValidateAssetOss.Resp) {}
  // 七牛上传回调
  rpc QiniuUploadCallback(QiniuUploadCallbackOss.Req) returns (QiniuUploadCallbackOss.Resp) {}
  // 七牛增量审核回调
  rpc QiniuIncrementAuditCallback(QiniuIncrementAuditCallbackOss.Req) returns (QiniuIncrementAuditCallbackOss.Resp) {}
}

message GetUploadTokenOss {
  message Req {
    int64 user_id = 1;
    int32 num = 3;
  }
  message Resp {
    message UploadToken {
      string key = 1;
      string token = 2;
    }
    repeated UploadToken upload_token = 1;
  }
}

message UploadOss {
  message Req {
    int64 user_id = 1;
    string key = 3;
    string file_name = 4;
    string mime_type = 5;
    bytes content = 6;
  }
  message Resp {
    int64 asset_id = 1;
    ObjectStorageProvider provider = 2;
    string bucket = 3;
    string key = 4;
    string mime_type = 5;
    int64 size = 6;
    string hash = 7;
    ObjectStorageStatus status = 9;
  }
}

message StreamUploadOss {
  message Req {
    message Meta {
      int64 user_id = 1;
      string key = 3;
      string file_name = 4;
      string mime_type = 5;
      int64 size = 6;
    }
    oneof payload {
      Meta meta = 1;
      bytes chunk = 2;
    }
  }
  message Resp {
    int64 asset_id = 1;
    ObjectStorageProvider provider = 2;
    string bucket = 3;
    string key = 4;
    string mime_type = 5;
    int64 size = 6;
    string hash = 7;
    ObjectStorageStatus status = 9;
  }
}

message DownloadOss {
  message Req {
    string key = 1;
  }
  message Resp {
    string key = 1;
    string mime_type = 2;
    int64 size = 3;
    bytes content = 4;
  }
}

message StreamDownloadOss {
  message Req {
    string key = 1;
  }
  message Resp {
    string key = 1;
    string mime_type = 2;
    int64 size = 3;
    bytes chunk = 4;
  }
}

message AuditOss {
  message Req {
    int64 user_id = 1;
    string key = 3;
    bool status = 4;
    optional string reason = 5;
  }
  message Resp {}
}

message ListOss {
  message Req {
    message OssQueryParams {
      optional ObjectStorageProvider provider = 1;
      optional string bucket = 2;
      optional string key = 3;
      optional string mime_type = 4;
      optional bool blocked = 5;
      common.Int64Range size = 7;
      optional ObjectStorageStatus status = 8;
    }
    .common.api.app.common.PageReq page = 1;
    OssQueryParams query = 2;
  }
  message Resp {
    message Oss {
      google.protobuf.Timestamp created_at = 1000;
      google.protobuf.Timestamp updated_at = 1001;
      int64 asset_id = 1;
      ObjectStorageProvider provider = 2;
      string bucket = 3;
      string key = 4;
      string mime_type = 5;
      int64 size = 6;
      string hash = 7;
      optional string audit_callback_reply = 8;
      bool blocked = 9;
      optional string blocked_reason = 10;
      google.protobuf.Timestamp blocked_at = 11;
      optional int64 blocked_by = 12;
      ObjectStorageStatus status = 14;
      string url = 15;
    }
    .common.api.app.common.PageResp page = 1;
    repeated Oss rows = 2;
  }
}

message ResolveAssetsOss {
  message Req {
    repeated int64 asset_ids = 1;
  }
  message Resp {
    message Asset {
      int64 asset_id = 1;
      string url = 2;
      string mime_type = 3;
      int64 size = 4;
      ObjectStorageStatus status = 5;
    }
    map<int64, Asset> assets = 1;
  }
}

message ValidateAssetOss {
  message Req {
    int64 asset_id = 1;
    int64 user_id = 3;
  }
  message Resp {}
}

message QiniuUploadCallbackOss {
  message Req {
    string key = 1;
    string hash = 2;
    int64 size = 3;
    string bucket = 4;
    string name = 5;
    string mime_type = 6;
    int64 upload_by = 7;
  }
  message Resp {}
}

message QiniuIncrementAuditCallbackOss {
  message Req {
    message Item {
      string cmd = 1;
      int32 code = 2;
      string desc = 3;
      ItemResultWrapper result = 4;
      int32 returnOld = 5;
    }

    message ItemResultWrapper {
      bool disable = 1;
      ItemResult result = 2;
    }

    message ItemResult {
      int32 code = 1;
      string message = 2;
      google.protobuf.Struct scenes = 3;
      string suggestion = 4;
    }
    string id = 1;
    string pipeline = 2;
    int32 code = 3;
    string desc = 4;
    string reqid = 5;
    string inputBucket = 6;
    string inputKey = 7;
    repeated Item items = 8;
  }
  message Resp {}
}
