syntax = "proto3";

package common.api.app.user.v1;

import "common/common.proto";
import "user/v1/enum.proto";
import "user/v1/model.proto";

option go_package = "common/api/gen/user/v1;v1";

service AccountService {
  // 查询单个账号。
  rpc Get(GetAccount.Request) returns (GetAccount.Reply) {}

  // 查询账号列表。
  rpc List(ListAccounts.Request) returns (ListAccounts.Reply) {}

  // 查询账号映射。
  rpc Map(MapAccounts.Request) returns (MapAccounts.Reply) {}

  // 更新账号展示资料。
  rpc UpdateProfile(UpdateProfileAccount.Request) returns (UpdateProfileAccount.Reply) {}

  // 生成默认账号头像。
  rpc Avatar(AvatarAccount.Request) returns (.common.api.app.common.ImageReply) {}
}

message AccountQuery {
  repeated int64 user_ids = 1;
}

message GetAccount {
  message Request {
    int64 user_id = 1;
  }
  message Reply {
    Account account = 1;
  }
}

message ListAccounts {
  message Request {
    AccountQuery query = 1;
  }
  message Reply {
    repeated Account rows = 1;
  }
}

message MapAccounts {
  message Request {
    AccountQuery query = 1;
  }
  message Reply {
    map<int64, Account> accounts = 1;
  }
}

message UpdateProfileAccount {
  message Request {
    int64 user_id = 1;
    optional string avatar_url = 2;
    optional string nickname = 3;
    optional string url = 4;
    optional string introduction = 5;
    optional MBTI mbti = 6;
  }
  message Reply {
    AccountBasic account = 1;
  }
}

message AvatarAccount {
  message Request {
    string name = 1;
  }
}
