syntax = "proto3";

package common.api.app.user.v1;

import "user/v1/enum.proto";
import "user/v1/model.proto";

option go_package = "common/api/gen/user/v1;v1";

service AccountService {
  // 查询单个账号。
  rpc Get(GetAccount.Request) returns (GetAccount.Reply) {}

  // 查询账号列表。
  rpc List(ListAccounts.Request) returns (ListAccounts.Reply) {}

  // 查询账号映射。
  rpc Map(MapAccounts.Request) returns (MapAccounts.Reply) {}

  // 检查邮箱是否已被账号占用。
  rpc ExistsEmail(ExistsEmail.Request) returns (ExistsEmail.Reply) {}

  // 检查手机号是否已被账号占用。
  rpc ExistsPhone(ExistsPhone.Request) returns (ExistsPhone.Reply) {}

  // 检查账号名是否已被占用。
  rpc ExistsName(ExistsName.Request) returns (ExistsName.Reply) {}

  // 更新账号展示资料。
  rpc UpdateProfile(UpdateProfileAccount.Request) returns (UpdateProfileAccount.Reply) {}
}

message AccountQuery {
  repeated int64 user_ids = 1;
}

message GetAccount {
  message Request {
    int64 user_id = 1;
  }
  message Reply {
    Account account = 1;
  }
}

message ListAccounts {
  message Request {
    AccountQuery query = 1;
  }
  message Reply {
    repeated Account rows = 1;
  }
}

message MapAccounts {
  message Request {
    AccountQuery query = 1;
  }
  message Reply {
    map<int64, Account> accounts = 1;
  }
}

message ExistsEmail {
  message Request {
    string email = 1;
  }
  message Reply {
    bool exists = 1;
  }
}

message ExistsPhone {
  message Request {
    string phone = 1;
  }
  message Reply {
    bool exists = 1;
  }
}

message ExistsName {
  message Request {
    string name = 1;
  }
  message Reply {
    bool exists = 1;
  }
}

message UpdateProfileAccount {
  message Request {
    int64 user_id = 1;
    optional string avatar_url = 2;
    optional string nickname = 3;
    optional string url = 4;
    optional string introduction = 5;
    optional MBTI mbti = 6;
  }
  message Reply {
    AccountBasic account = 1;
  }
}
