syntax = "proto3";

package common.api.app.user.v1;

import "user/v1/model.proto";

option go_package = "common/api/gen/user/v1;v1";

service AuthService {
  // 使用邮箱发起账号注册，成功后返回验证码令牌。
  rpc RegisterEmail(RegisterEmail.Request) returns (RegisterEmail.Reply) {}

  // 校验邮箱注册验证码并创建账号。
  rpc VerifyEmailRegister(VerifyEmailRegister.Request) returns (VerifyEmailRegister.Reply) {}

  // 使用手机号发起账号注册，成功后返回验证码令牌。
  rpc RegisterPhone(RegisterPhone.Request) returns (RegisterPhone.Reply) {}

  // 校验手机号注册验证码并创建账号。
  rpc VerifyPhoneRegister(VerifyPhoneRegister.Request) returns (VerifyPhoneRegister.Reply) {}

  // 使用账号名、邮箱或手机号加密码登录。
  rpc LoginPassword(LoginPassword.Request) returns (LoginPassword.Reply) {}

  // 登出当前登录账号并清理当前令牌。
  rpc Logout(Logout.Request) returns (Logout.Reply) {}
}

message RegisterEmail {
  message Request {
    string email = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyEmailRegister {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message RegisterPhone {
  message Request {
    string phone = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyPhoneRegister {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message LoginPassword {
  message Request {
    string account = 1;
    string password = 2;
  }
  message Reply {
    string token = 1;
    Account account = 2;
  }
}

message Logout {
  message Request {}
  message Reply {}
}
