syntax = "proto3";

package common.api.app.user.v1;


option go_package = "common/api/gen/user/v1;v1";

// TwoFactorAuth 服务
service UserTwoFactorAuthService {
  // 验证
  rpc Validate(ValidateTwoFactorAuth.Request) returns (ValidateTwoFactorAuth.Reply) {}

  // 开启 2FA 验证
  rpc Enable(EnableTwoFactorAuth.Request) returns (EnableTwoFactorAuth.Reply) {}

  // 关闭 2FA 验证
  rpc Disable(DisableTwoFactorAuth.Request) returns (DisableTwoFactorAuth.Reply) {}

  // 确认 2FA 绑定
  rpc Confirm(ConfirmTwoFactorAuth.Request) returns (ConfirmTwoFactorAuth.Reply) {}

}

message ValidateTwoFactorAuth {
  message Request {
    // 2FA 验证码
    string code = 1;
  }
  message Reply {
    // 验证结果
    bool verified = 1;
  }
}

message EnableTwoFactorAuth {
  message Request {}
  message Reply {
    // 图片数据
    bytes data = 1;
    // 图片类型
    string content_type = 2;
  }
}

message DisableTwoFactorAuth {
  message Request {
    // 2FA 验证码
    string code = 1;
  }
  message Reply {}
}

message ConfirmTwoFactorAuth {
  message Request {
    // 2FA 验证码
    string code = 1;
  }
  message Reply {}
}
