syntax = "proto3";

package common.api.app.user.v1;

import "validate/validate.proto";

option go_package = "common/api/gen/user/v1;v1";

// TwoFactorAuthentication 服务
service UserTwoFactorAuthenticationService {

  // 验证
  rpc Validate(UserTwoFactorAuthenticationValidateRequest) returns (UserTwoFactorAuthenticationValidateReply);

  // 开启 2FA 验证
  rpc Enable(UserTwoFactorAuthenticationEnableRequest) returns (UserTwoFactorAuthenticationEnableReply);

  // 关闭 2FA 验证
  rpc Disable(UserTwoFactorAuthenticationDisableRequest) returns (UserTwoFactorAuthenticationDisableReply);

  // 确认 2FA 绑定
  rpc Confirm(UserTwoFactorAuthenticationConfirmRequest) returns (UserTwoFactorAuthenticationConfirmReply);
}

// 实体定义

// 查询参数定义

message UserTwoFactorAuthenticationValidateRequest {
  // 2FA 验证码
  string code = 1 [(validate.rules).string = {min_len: 6, max_len: 6}];
}
message UserTwoFactorAuthenticationValidateReply {
  // 验证结果
  bool verified = 1;
}

message UserTwoFactorAuthenticationEnableRequest {}
message UserTwoFactorAuthenticationEnableReply {
  // 图片数据
  bytes data = 1;
  // 图片类型
  string content_type = 2;
}

message UserTwoFactorAuthenticationDisableRequest {
  // 2FA 验证码
  string code = 1 [(validate.rules).string = {min_len: 6, max_len: 6}];
}
message UserTwoFactorAuthenticationDisableReply {}

message UserTwoFactorAuthenticationConfirmRequest {
  // 2FA 验证码
  string code = 1 [(validate.rules).string = {min_len: 6, max_len: 6}];
}
message UserTwoFactorAuthenticationConfirmReply {}
