syntax = "proto3";

package common.api.app.user.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";

option go_package = "common/api/gen/user/v1;v1";

// TwoFactorAuthentication 服务
service UserTwoFactorAuthenticationService {
  // 验证
  rpc Validate(ValidateTwoFactorAuthentication.Request) returns (ValidateTwoFactorAuthentication.Reply) {
    option (google.api.http) = {
      post: "/v1/two-factor-authentication/validate"
      body: "*"
    };
  }

  // 开启 2FA 验证
  rpc Enable(EnableTwoFactorAuthentication.Request) returns (EnableTwoFactorAuthentication.Reply) {
    option (google.api.http) = {
      post: "/v1/two-factor-authentication/enable"
      body: "*"
    };
  }

  // 关闭 2FA 验证
  rpc Disable(DisableTwoFactorAuthentication.Request) returns (DisableTwoFactorAuthentication.Reply) {
    option (google.api.http) = {
      post: "/v1/two-factor-authentication/disable"
      body: "*"
    };
  }

  // 确认 2FA 绑定
  rpc Confirm(ConfirmTwoFactorAuthentication.Request) returns (ConfirmTwoFactorAuthentication.Reply) {
    option (google.api.http) = {
      post: "/v1/two-factor-authentication/confirm"
      body: "*"
    };
  }
}

message ValidateTwoFactorAuthentication {
  message Request {
    // 2FA 验证码
    string code = 1 [(validate.rules).string = {
      min_len: 6
      max_len: 6
    }];
  }
  message Reply {
    // 验证结果
    bool verified = 1;
  }
}

message EnableTwoFactorAuthentication {
  message Request {}
  message Reply {
    // 图片数据
    bytes data = 1;
    // 图片类型
    string content_type = 2;
  }
}

message DisableTwoFactorAuthentication {
  message Request {
    // 2FA 验证码
    string code = 1 [(validate.rules).string = {
      min_len: 6
      max_len: 6
    }];
  }
  message Reply {}
}

message ConfirmTwoFactorAuthentication {
  message Request {
    // 2FA 验证码
    string code = 1 [(validate.rules).string = {
      min_len: 6
      max_len: 6
    }];
  }
  message Reply {}
}
