syntax = "proto3";

package common.api.app.user.v1;

import "google/api/annotations.proto";
import "common/v1/common.proto";
import "user/v1/model.proto";

option go_package = "common/api/gen/user/v1;v1";

// User 服务
service UserUserService {

  // 更新用户设置
  rpc UpdateSetting (UpdateSettingUser.Request) returns (UpdateSettingUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/update-setting"
      body: "*"
    };
  }

  // 获取当前用户信息
  rpc GetCurrentUser (GetCurrentUserUser.Request) returns (GetCurrentUserUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/current"
      body:"*"
    };
  }

  // 查询单个用户
  rpc GetOne (GetOneUser.Request) returns (GetOneUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/get-one"
      body:"*"
    };
  }

  // 查询用户列表（返回数组）
  rpc GetList (GetListUser.Request) returns (GetListUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/list"
      body: "*"
    };
  }

  // 查询用户列表（返回map）
  rpc GetMap(GetMapUser.Request) returns (GetMapUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/map"
      body: "*"
    };
  }

  // 分页查询用户
  rpc Page(PageUser.Request) returns (PageUser.Reply) {
    option (google.api.http) = {
      post: "/v1/user/page"
      body: "*"
    };
  }

  // 获取用户默认头像
  rpc Avatar(AvatarUser.Request) returns (common.v1.ImageReply){
    option (google.api.http) = {
      get: "/v1/user/avatar"
    };
  };

}

message UpdateSettingUser {
  message Request {
    // 用户头像 URL
    optional string avatar_url = 10;
    // 昵称
    optional string nickname = 7;
    // 语言偏好
    optional string language = 1;
    // 时区
    optional string timezone = 2;
    // 桌面主题
    optional string theme = 3;
    // 移动端主题
    optional string mobile_theme = 4;
    // 启用 web 通知
    optional bool enable_web_notify = 5;
    // 启用邮件订阅
    optional bool enable_email_subscribe = 6;
  }
  message Reply {
    // 更新后的用户信息
    User user = 1;
  }
}

message GetCurrentUserUser {
  message Request {}
  message Reply {
    // 当前用户信息
    User user = 1;
  }
}

message GetOneUser {
  message Request {
    // 用户 ID
    optional int64 user_id = 1;
    // 用户名
    optional string name = 2;
  }
  message Reply {
    // 用户信息
    User user = 1;
  }
}

message GetListUser {
  message Request {
    // 查询条件
    UserQueryParams query = 2;
  }
  message Reply {
    // 用户列表
    repeated User users = 1;
  }
}

message GetMapUser {
  message Request {
    // 查询条件
    UserQueryParams query = 2;
  }
  message Reply {
    // 用户 map，key 为用户 ID
    map<int64, User> users = 1;
  }
}

message PageUser {
  message Request {
    // 分页参数
    common.v1.PageRequest page = 1;
    // 查询条件
    UserQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.v1.PageReply page = 1;
    // 用户列表
    repeated User rows = 2;
  }
}

message AvatarUser {
  message Request {
    // 用户名
    string name = 1;
  }
}