syntax = "proto3";

package common.api.app.user.v1;

import "google/api/annotations.proto";
import "common/v1/common.proto";
import "user/v1/model.proto";

option go_package = "common/api/gen/user/v1;v1";

// UserRelation 服务
service UserUserRelationService {

  // 关注用户
  rpc Follow(FollowUserRelation.Request) returns (FollowUserRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user-relation/follow"
      body: "*"
    };
  }

  // 屏蔽用户
  rpc Block(BlockUserRelation.Request) returns (BlockUserRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user-relation/block"
      body: "*"
    };
  }

  // 查询用户关系
  rpc Page(PageUserRelation.Request) returns (PageUserRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user-relation/page"
      body: "*"
    };
  }

}

message FollowUserRelation {
  message Request {
    // 是否关注
    bool follow = 1;
    // 被关注用户 ID
    int64 follow_user_id = 2;
  }
  message Reply {}
}

message BlockUserRelation {
  message Request {
    // 是否屏蔽
    bool block = 1;
    // 被屏蔽用户 ID
    int64 block_user_id = 2;
  }
  message Reply {}
}

message PageUserRelation {
  message Request {
    // 分页参数
    common.v1.PageRequest page = 1;
    // 查询条件
    UserRelationQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.v1.PageReply page = 1;
    // 用户关系列表
    repeated UserRelation rows = 2;
  }
}