syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/enum.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// Article 服务
service ContentArticleService {
  // 创建文章
  rpc Create(CreateArticle.Request) returns (CreateArticle.Reply) {}

  // 更新草稿
  rpc UpdateDraft(UpdateDraftArticle.Request) returns (UpdateDraftArticle.Reply) {}

  // 发布文章（从草稿发布）
  rpc Publish(PublishArticle.Request) returns (PublishArticle.Reply) {}

  // 添加附言
  rpc AddPostscript(AddPostscriptArticle.Request) returns (AddPostscriptArticle.Reply) {}

  // 修改文章（管理员使用）
  rpc Update(UpdateArticle.Request) returns (UpdateArticle.Reply) {}

  // 删除文章（仅草稿）
  rpc Delete(DeleteArticle.Request) returns (DeleteArticle.Reply) {}

  // 查询文章列表
  rpc List(ListArticles.Request) returns (ListArticles.Reply) {}

  // 查询单篇文章
  rpc Get(GetArticle.Request) returns (GetArticle.Reply) {}

  // 点赞文章
  rpc Like(LikeArticle.Request) returns (LikeArticle.Reply) {}

  // 感谢文章
  rpc Thank(ThankArticle.Request) returns (ThankArticle.Reply) {}

  // 收藏文章
  rpc Collect(CollectArticle.Request) returns (CollectArticle.Reply) {}

  // 关注文章
  rpc Watch(WatchArticle.Request) returns (WatchArticle.Reply) {}

  // 打赏文章
  rpc Reward(RewardArticle.Request) returns (RewardArticle.Reply) {}

  // 采纳评论
  rpc AcceptAnswer(AcceptAnswerArticle.Request) returns (AcceptAnswerArticle.Reply) {}
}

message CreateArticle {
  message Request {
    // 文章信息
    ArticleSave article = 1;
    // 用户ID
    int64 user_id = 2;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message UpdateDraftArticle {
  message Request {
    // 文章信息
    ArticleSave article = 1;
    // 用户ID
    int64 user_id = 2;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message PublishArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 用户ID
    int64 user_id = 2;
  }
  message Reply {}
}

message AddPostscriptArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 附言内容
    string content = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {
    // 附言信息
    ArticlePostscript article_postscript = 1;
  }
}

message UpdateArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 文章状态
    ArticleStatus status = 2;
    // 是否允许评论
    bool commentable = 3;
    // 是否匿名
    bool anonymous = 4;
    // 用户ID
    int64 user_id = 5;
    // 是否在列表展示
    optional bool listable = 6;
  }
  message Reply {}
}

message DeleteArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 用户ID
    int64 user_id = 2;
  }
  message Reply {}
}

message ListArticles {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询参数
    ArticleQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 2;
    // 文章列表
    repeated Article rows = 1;
  }
}

message GetArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message RewardArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 用户ID
    int64 user_id = 2;
  }
  message Reply {}
}

message ThankArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否感谢
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message LikeArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否点赞
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message CollectArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否收藏
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message WatchArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否关注
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message AcceptAnswerArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 评论ID
    int64 comment_id = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}
