syntax = "proto3";

package common.api.app.content.v1;

import "google/api/annotations.proto";
import "validate/validate.proto";
import "common/common.proto";
import "content/v1/model.proto";
import "content/v1/enum.proto";

option go_package = "common/api/gen/content/v1;v1";

// Article 服务
service ContentArticleService {

  // 新增文章
  rpc AddArticle (AddArticle.Request) returns (AddArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/add"
      body: "*"
    };
  }

  // 更新草稿
  rpc UpdateDraft (UpdateDraftArticle.Request) returns (UpdateDraftArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/update-draft"
      body: "*"
    };
  }

  // 发布文章（从草稿发布）
  rpc Publish (PublishArticle.Request) returns (PublishArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/publish"
      body: "*"
    };
  }

  // 添加附言
  rpc AddPostscript (AddPostscriptArticle.Request) returns (AddPostscriptArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/add-postscript"
      body: "*"
    };
  }

  // 修改文章（管理员使用）
  rpc UpdateArticle (UpdateArticleArticle.Request) returns (UpdateArticleArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/update"
      body: "*"
    };
  }

  // 删除文章（仅草稿）
  rpc Delete (DeleteArticle.Request) returns (DeleteArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/delete"
      body: "*"
    };
  }

  // 查询文章
  rpc Page (PageArticle.Request) returns (PageArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/page"
      body: "*"
    };
  }

  // 查询单篇文章
  rpc GetOne (GetOneArticle.Request) returns (GetOneArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/get-one"
      body: "*"
    };
  }

  // 点赞文章
  rpc Like (LikeArticle.Request) returns (LikeArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/like"
      body: "*"
    };
  }

  // 感谢文章
  rpc Thank (ThankArticle.Request) returns (ThankArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/thank"
      body: "*"
    };
  }

  // 收藏文章
  rpc Collect (CollectArticle.Request) returns (CollectArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/collect"
      body: "*"
    };
  }

  // 关注文章
  rpc Watch (WatchArticle.Request) returns (WatchArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/watch"
      body: "*"
    };
  }

  // 打赏文章
  rpc Reward (RewardArticle.Request) returns (RewardArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/reward"
      body: "*"
    };
  }

  // 采纳评论
  rpc AcceptAnswer (AcceptAnswerArticle.Request) returns (AcceptAnswerArticle.Reply) {
    option (google.api.http) = {
      post: "/v1/article/accept-answer"
      body: "*"
    };
  }

}

message AddArticle {
  message Request {
    // 文章信息
    ArticleSave article = 1;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message UpdateDraftArticle {
  message Request {
    // 文章信息
    ArticleSave article = 1;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message PublishArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
  }
  message Reply {}
}

message AddPostscriptArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 附言内容
    string content = 2 [(validate.rules).string = {min_len: 1}];
  }
  message Reply {
    // 附言信息
    ArticlePostscript article_postscript = 1;
  }
}

message UpdateArticleArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 文章状态
    ArticleStatus status = 2;
    // 是否允许评论
    bool commentable = 3;
    // 是否匿名
    bool anonymous = 4;
  }
  message Reply {}
}

message DeleteArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
  }
  message Reply {}
}

message PageArticle {
  message Request {
    // 分页参数
    common.PageRequest page = 1;
    // 查询参数
    ArticleQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 2;
    // 文章列表
    repeated Article rows = 1;
  }
}

message GetOneArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
  }
  message Reply {
    // 文章信息
    Article article = 1;
  }
}

message RewardArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
  }
  message Reply {}
}

message ThankArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否感谢
    bool active = 2;
  }
  message Reply {}
}

message LikeArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否点赞
    bool active = 2;
  }
  message Reply {}
}

message CollectArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否收藏
    bool active = 2;
  }
  message Reply {}
}

message WatchArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 是否关注
    bool active = 2;
  }
  message Reply {}
}

message AcceptAnswerArticle {
  message Request {
    // 文章ID
    int64 article_id = 1;
    // 评论ID
    int64 comment_id = 2;
  }
  message Reply {}
}