syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/enum.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// 评论服务
service ContentCommentService {
  // 创建评论
  rpc Create(CreateComment.Request) returns (CreateComment.Reply) {}

  // 查询评论列表
  rpc List(ListComments.Request) returns (ListComments.Reply) {}

  // 点赞评论
  rpc Like(LikeComment.Request) returns (LikeComment.Reply) {}

  // 感谢评论
  rpc Thank(ThankComment.Request) returns (ThankComment.Reply) {}

  // 修改评论状态
  rpc UpdateStatus(UpdateStatusComment.Request) returns (UpdateStatusComment.Reply) {}
}

message CreateComment {
  message Request {
    // 文章ID
    int64 article_id = 2;
    // 评论内容
    string content = 4;
    // 回复评论ID
    int64 reply_id = 6;
    // 用户ID
    int64 user_id = 7;
  }
  message Reply {
    // 评论信息
    Comment comment = 1;
  }
}

message ListComments {
  message Request {
    // 分页参数
    optional common.PageRequest page = 1;
    // 查询参数
    CommentQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 评论列表
    repeated Comment rows = 2;
  }
}

message LikeComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 是否点赞
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message ThankComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 是否感谢
    bool active = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}

message UpdateStatusComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 状态
    CommentStatus status = 2;
    // 用户ID
    int64 user_id = 3;
  }
  message Reply {}
}
