syntax = "proto3";

package common.api.app.content.v1;

import "google/api/annotations.proto";
import "common/common.proto";
import "content/v1/model.proto";
import "content/v1/enum.proto";

option go_package = "common/api/gen/content/v1;v1";

// 评论服务
service ContentCommentService {

  // 新增评论
  rpc AddComment (AddComment.Request) returns (AddComment.Reply) {
    option (google.api.http) = {
      post: "/v1/comment/add"
      body: "*"
    };
  }

  // 查询评论列表
  rpc Page (PageComment.Request) returns (PageComment.Reply) {
    option (google.api.http) = {
      post: "/v1/comment/page"
      body: "*"
    };
  }

  // 点赞评论
  rpc Like (LikeComment.Request) returns (LikeComment.Reply) {
    option (google.api.http) = {
      post: "/v1/comment/like"
      body: "*"
    };
  }

  // 感谢评论
  rpc Thank (ThankComment.Request) returns (ThankComment.Reply) {
    option (google.api.http) = {
      post: "/v1/comment/thank"
      body: "*"
    };
  }

  // 修改评论状态
  rpc UpdateStatus (UpdateStatusComment.Request) returns (UpdateStatusComment.Reply) {
    option (google.api.http) = {
      post: "/v1/comment/update-status"
      body: "*"
    };
  }

}

message AddComment {
  message Request {
    // 文章ID
    int64 article_id = 2;
    // 评论内容
    string content = 4;
    // 回复评论ID
    int64 reply_id = 6;
  }
  message Reply {
    // 评论信息
    Comment comment = 1;
  }
}

message PageComment {
  message Request {
    // 分页参数
    optional common.PageRequest page = 1;
    // 查询参数
    CommentQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 评论列表
    repeated Comment rows = 2;
  }
}

message LikeComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 是否点赞
    bool active = 2;
  }
  message Reply {}
}

message ThankComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 是否感谢
    bool active = 2;
  }
  message Reply {}
}

message UpdateStatusComment {
  message Request {
    // 评论ID
    int64 id = 1;
    // 状态
    CommentStatus status = 2;
  }
  message Reply {}
}