syntax = "proto3";

package common.api.app.content.v1;

import "google/api/annotations.proto";
import "common/v1/common.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// 领域服务
service ContentDomainService {

  // 新增领域
  rpc Adds (AddsDomain.Request) returns (AddsDomain.Reply) {
    option (google.api.http) = {
      post: "/v1/domain/adds"
      body: "*"
    };
  }

  // 修改领域信息
  rpc Update (UpdateDomain.Request) returns (UpdateDomain.Reply) {
    option (google.api.http) = {
      post: "/v1/domain/update"
      body: "*"
    };
  }

  // 分页查询领域
  rpc Page (PageDomain.Request) returns (PageDomain.Reply) {
    option (google.api.http) = {
      post: "/v1/domain/page"
      body: "*"
    };
  }
}

message AddsDomain {
  message Request {
    // 领域信息列表
    repeated DomainSave domains = 1;
  }
  message Reply {
    // 领域信息列表
    repeated Domain rows = 1;
  }
}

message UpdateDomain {
  message Request {
    // 领域信息
    DomainSave domain = 1;
  }
  message Reply {
    // 领域信息
    Domain data = 1;
  }
}

message PageDomain {
  message Request {
    // 分页参数
    optional common.v1.PageRequest page = 1;
    // 查询参数
    DomainQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    optional common.v1.PageReply page = 1;
    // 领域列表
    repeated Domain rows = 2;
  }
}