syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// 领域服务
service ContentDomainService {
  // 新增领域
  rpc Adds(AddsDomain.Request) returns (AddsDomain.Reply) {}

  // 修改领域信息
  rpc Update(UpdateDomain.Request) returns (UpdateDomain.Reply) {}

  // 分页查询领域
  rpc Page(PageDomain.Request) returns (PageDomain.Reply) {}
}

message AddsDomain {
  message Request {
    // 领域信息列表
    repeated DomainSave domains = 1;
  }
  message Reply {
    // 领域信息列表
    repeated Domain rows = 1;
  }
}

message UpdateDomain {
  message Request {
    // 领域信息
    DomainSave domain = 1;
  }
  message Reply {
    // 领域信息
    Domain data = 1;
  }
}

message PageDomain {
  message Request {
    // 分页参数
    optional common.PageRequest page = 1;
    // 查询参数
    DomainQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    optional common.PageReply page = 1;
    // 领域列表
    repeated Domain rows = 2;
  }
}
