syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/enum.proto";
import "google/protobuf/timestamp.proto";
import "user/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// =====================
// 实体定义
// =====================

message Article {
  // 创建时间
  google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  google.protobuf.Timestamp updated_at = 1001;
  // 创建人
  optional int64 created_by = 1002;
  // 更新人
  optional int64 updated_by = 1003;
  // 创建人名称
  optional string created_by_name = 1004;
  // 更新人名称
  optional string updated_by_name = 1005;

  // 唯一Id
  int64 id = 1;
  // 标题
  string title = 3;
  // 正文内容
  string content = 4;
  // 正文内容渲染
  string content_render = 22;

  // 是否有附言
  bool has_postscript = 5;
  // 是否有打赏区
  bool has_reward = 33;
  // 打赏区内容（可为空）
  optional string reward_content = 6;
  // 打赏内容渲染（可为空）
  optional string reward_content_render = 23;
  // 打赏积分
  optional int32 reward_points = 7;

  // 状态
  ArticleStatus status = 8;
  // 类型
  ArticleType type = 9;
  // 创作声明
  optional string statement = 10;
  // 是否允许评论
  bool commentable = 11;
  // 是否匿名
  bool anonymous = 30;
  // 是否在列表展示
  bool listable = 31;

  // 浏览数
  int32 view_count = 32;
  // 感谢数
  int32 thank_count = 12;
  // 点赞数
  int32 like_count = 13;
  // 收藏数
  int32 collect_count = 14;
  // 关注数
  int32 watch_count = 15;
  // 回复数
  int32 reply_count = 16;

  // 悬赏积分
  optional int32 bounty_points = 17;
  // 采纳评论Id（可为空）
  optional int64 accepted_answer_id = 18;

  // 总投票数
  int32 vote_total = 19;
  // 抽奖参与人数
  int32 lottery_participant_count = 20;
  // 抽奖获奖人数
  int32 lottery_winner_count = 21;

  // 作者信息
  user.v1.AccountBasic author_user = 24;
  // 最后回复用户
  user.v1.AccountBasic last_reply_user = 25;
  // 最后回复时间
  google.protobuf.Timestamp last_reply_at = 26;

  // 文章封面图
  optional string cover_image_url = 27;

  // 附言
  repeated ArticlePostscript postscripts = 99;
  // 标签
  repeated Tag tags = 100;
}

message ArticlePostscript {
  // 创建时间
  google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  google.protobuf.Timestamp updated_at = 1001;
  // 创建人
  optional int64 created_by = 1002;
  // 更新人
  optional int64 updated_by = 1003;

  // 主键Id
  int64 id = 1;
  // 所属文章Id
  int64 article_id = 2;
  // 附言内容
  string content = 3;
  // 附言内容渲染
  string content_render = 4;
}

message ArticleEventPublish {
  int64 article_id = 1;
  int64 user_id = 2;
  string title = 3;
  string content = 4;
  string reward_content = 5;
  int32 reward_points = 6;
  ArticleStatus status = 7;
  ArticleType type = 8;
  int32 bounty_points = 9;
}

message Tag {
  // 创建时间
  optional google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  optional google.protobuf.Timestamp updated_at = 1001;
  // 创建人
  optional int64 created_by = 1002;
  // 更新人
  optional int64 updated_by = 1003;
  // 主键
  int64 id = 1;
  // 标签名称
  string name = 3;
  // 描述
  optional string description = 4;
  // 所属领域Id
  optional int64 domain_id = 5;
  // 标签状态：1-正常，2-禁用
  optional TagStatus status = 6;
  // 文章数
  int32 article_count = 7;
}

message Domain {
  // 创建时间
  google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  google.protobuf.Timestamp updated_at = 1001;
  // 创建人
  optional int64 created_by = 1002;
  // 更新人
  optional int64 updated_by = 1003;

  // 主键
  int64 id = 3;
  // 领域名称
  string name = 4;
  // 描述
  optional string description = 5;
  // 状态 1-正常，2-禁用
  DomainStatus status = 6;
  // 链接
  optional string url = 7;
  // 图标
  optional string icon = 8;
  // 标签数量
  int32 tagCount = 9;
  // 是否导航
  bool isNav = 10;
  // 标签列表
  repeated Tag tags = 100;
}

message Comment {
  // 创建时间
  google.protobuf.Timestamp created_at = 1000;
  // 更新时间
  google.protobuf.Timestamp updated_at = 1001;
  // 创建人
  optional int64 created_by = 1002;
  // 更新人
  optional int64 updated_by = 1003;
  // 创建人名称
  optional string created_by_name = 1004;
  // 更新人名称
  optional string updated_by_name = 1005;

  // 评论Id
  int64 id = 1;
  // 文章Id
  int64 article_id = 2;
  // 评论内容
  string content = 4;
  // 评论内容渲染
  string content_render = 12;
  // 评论层级
  int32 level = 5;
  // 父级评论Id
  optional int64 parent_id = 6;
  // 回复评论Id
  optional int64 reply_id = 7;
  // 状态 1-正常 2-隐藏
  CommentStatus status = 8;
  // 感谢数量
  int32 thank_count = 13;
  // 点赞数量
  int32 like_count = 10;
  // 收藏数量
  int32 collect_count = 11;
  // 子评论数量
  int32 reply_count = 9;

  // 用户信息
  user.v1.AccountBasic user = 15;
  // 回复评论的用户信息
  user.v1.AccountBasic reply_user = 16;

  // 文章信息
  Article article = 100;
}

// =====================
// 查询参数定义
// =====================

message ArticleQueryParams {
  // 标签
  optional int64 tagId = 2;
  // 领域
  optional int64 domainId = 3;
  // 状态
  optional ArticleStatus status = 4;
  // 类型
  optional ArticleType type = 5;
  // 排序
  optional ArticleOrder order = 8;
  // 查询关键词
  optional string keyword = 9;
  // 作者Id
  optional int64 authorId = 10;
}

message CommentQueryParams {
  // 评论Id
  optional int64 comment_id = 2;
  // 文章Id
  optional int64 article_id = 3;
  // 父级评论Id
  optional int64 parent_id = 4;
  // 回复评论Id
  optional int64 reply_id = 5;
  // 排序 1-最新 2-最热
  optional CommentStatus order = 6;
  // 用户Id
  optional int64 user_id = 7;
  // 层级
  optional int32 level = 8;

  // 是否返回文章信息
  bool with_article = 100;
}

message TagQueryParams {
  // 标签Id列表
  repeated int64 ids = 1;
  // 用户Id
  optional int64 user_id = 2;
  // 标签名称
  optional string name = 3;
  // 标签名称列表
  repeated string names = 4;
  // 标签描述
  optional string description = 5;
  // 标签状态
  optional TagStatus status = 6;
  // 领域Id
  optional int64 domain_id = 7;
  // 文章数量范围
  common.Int32Range article_count = 8;
}

message DomainQueryParams {
  // 主键
  repeated int64 ids = 2;
  // 领域名称
  optional string name = 3;
  // 描述
  optional string description = 4;
  // 状态 1-正常，2-禁用
  optional DomainStatus status = 5;
  // 链接
  optional string url = 6;
  // 图标
  optional string icon = 7;
  // 是否导航
  optional bool isNav = 8;
  // 标签数量范围
  common.Int32Range tagCount = 9;
}

// =====================
// 保存参数定义
// =====================

message ArticleSave {
  // 文章id
  optional int64 id = 8;
  // 标题
  string title = 1;
  // 内容
  string content = 2;
  // 打赏内容
  optional string reward_content = 3;
  // 打赏积分
  optional int32 reward_points = 4;
  // 状态
  ArticleStatus status = 5;
  // 类型
  ArticleType type = 6;
  // 悬赏积分
  optional int32 bounty_points = 7;

  // 创作声明
  optional string statement = 10;
  // 是否允许评论
  optional bool commentable = 11;
  // 是否匿名
  optional bool anonymous = 12;
  // 是否在列表展示
  optional bool listable = 13;

  // 标签id
  repeated TagSave tags = 100;
}

message TagSave {
  // 主键
  optional int64 id = 1;
  // 领域Id
  optional int64 domain_id = 2;
  // 状态：1-正常，2-禁用
  optional TagStatus status = 3;
  // 标签名称
  string name = 4;
  // 标签描述
  optional string description = 5;
}

message DomainSave {
  // 主键
  int64 id = 1;
  // 领域名称
  string name = 2;
  // 描述
  optional string description = 3;
  // 状态 1-正常，2-禁用
  optional DomainStatus status = 4;
  // 链接
  optional string url = 5;
  // 图标
  optional string icon = 6;
  // 是否导航
  bool isNav = 7;
}
