syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// 标签服务
service ContentTagService {
  // 批量创建标签
  rpc BatchCreate(BatchCreateTags.Request) returns (BatchCreateTags.Reply) {}

  // 更新标签
  rpc Update(UpdateTag.Request) returns (UpdateTag.Reply) {}

  // 查询标签列表
  rpc List(ListTags.Request) returns (ListTags.Reply) {}
}

message BatchCreateTags {
  message Request {
    // 标签信息列表
    repeated TagSave tags = 1;
  }
  message Reply {
    // 标签信息列表
    repeated Tag tags = 1;
  }
}

message UpdateTag {
  message Request {
    // 标签信息
    TagSave tag = 1;
  }
  message Reply {
    // 标签信息
    Tag tag = 1;
  }
}

message ListTags {
  message Request {
    // 分页参数
    optional common.PageRequest page = 1;
    // 查询参数
    TagQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 标签列表
    repeated Tag rows = 2;
  }
}
