syntax = "proto3";

package common.api.app.content.v1;

import "google/api/annotations.proto";
import "common/common.proto";
import "content/v1/model.proto";

option go_package = "common/api/gen/content/v1;v1";

// 标签服务
service ContentTagService {

  // 批量添加标签
  rpc Adds (AddsTag.Request) returns (AddsTag.Reply) {
    option (google.api.http) = {
      post: "/v1/tag/adds"
      body: "*"
    };
  }

  // 更新标签
  rpc Update (UpdateTag.Request) returns (UpdateTag.Reply) {
    option (google.api.http) = {
      post: "/v1/tag/update"
      body: "*"
    };
  }

  // 分页获取标签
  rpc Page (PageTag.Request) returns (PageTag.Reply) {
    option (google.api.http) = {
      post: "/v1/tag/page"
      body: "*"
    };
  }
}

message AddsTag {
  message Request {
    // 标签信息列表
    repeated TagSave tags = 1;
  }
  message Reply {
    // 标签信息列表
    repeated Tag tags = 1;
  }
}

message UpdateTag {
  message Request {
    // 标签信息
    TagSave tag = 1;
  }
  message Reply {
    // 标签信息
    Tag tag = 1;
  }
}

message PageTag {
  message Request {
    // 分页参数
    optional common.PageRequest page = 1;
    // 查询参数
    TagQueryParams query = 2;
  }
  message Reply {
    // 分页信息
    common.PageReply page = 1;
    // 标签列表
    repeated Tag rows = 2;
  }
}