server:
  name: scheduler
  version: 1.0.0
  mode: ${SERVICE_MODE:dev}
http:
  network: tcp
  host: ${HTTP_HOST:0.0.0.0}
  port: ${HTTP_PORT:8203}
  timeout: 5s
grpc:
  network: tcp
  host: ${GRPC_HOST:0.0.0.0}
  port: ${GRPC_PORT:9203}
  timeout: 5s
consul:
  address: ${CONSUL_HOST:127.0.0.1}:${CONSUL_PORT:8500}
  datacenter: dc1
  token: ${CONSUL_ACL_APP_TOKEN:token}
  dial_timeout: 5s
database:
  driver: postgres
  source: postgresql://${POSTGRES_USER:admin}:${POSTGRES_PASSWORD:123456}@${POSTGRES_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:bass}?sslmode=disable
  merge: true
  debug: false
  slow_sql_threshold: 1s
  sample_rate: 1
redis:
  addr: ${REDIS_HOST:127.0.0.1}:${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:"123456"}
  dial_timeout: 5s
  db: 0
  read_timeout: 5s
  write_timeout: 5s
  pool_size: 150
  min_idle_conns: 30
  pool_timeout: 2s
  conn_max_idle_time: 600s
  conn_max_life_time: 1800s
nats:
  host: ${NATS_HOST:127.0.0.1}
  port: ${NATS_PORT:4222}
  user: ${NATS_USER:admin}
  password: ${NATS_PASSWORD:"123456"}
  name: nats-scheduler
  timeout: 5s
  max_reconnects: 10
  reconnect_wait: 2s
  ping_interval: 30s
  flusher_timeout: 5s
  enable_jet_stream: true
  stream_name: ""
  jet_stream_domain: ""
trace:
  enable_otel: false
  endpoint: ${OTEL_ENDPOINT:127.0.0.1:4317}
  insecure: true
  sampler: 1
observability:
  enable_metrics: true
scheduler:
  default_execution_timeout: 30s # 30s
  stream_name: SCHEDULER
  scheduled_task_consumer_durable: scheduler-scheduled-task-executor
  delayed_task_consumer_durable: scheduler-delayed-task-executor
  scheduled_task_schedule_subject_prefix: scheduler.schedule.scheduled_task
  delayed_task_schedule_subject_prefix: scheduler.schedule.delayed_task_execution
  scheduled_task_execute_subject: scheduler.execute.scheduled_task
  delayed_task_execute_subject: scheduler.execute.delayed_task
  ack_wait: 60s # 1min
  fetch_batch: 16
  fetch_wait: 2s # 2s
  scheduled_task_concurrency: 8
  delayed_task_concurrency: 16
  reconcile_interval: 60s # 1min
