syntax = "proto3";

package common.api.app.content.v1;

import "common/common.proto";
import "content/v1/enum.proto";
import "content/v1/model.proto";

option go_package = "common/proto/gen/content/v1;v1";

// 标签服务
service ContentTagService {
  rpc BatchCreate(BatchCreateTags.Request) returns (BatchCreateTags.Reply) {} // 批量创建标签

  rpc Update(UpdateTag.Request) returns (UpdateTag.Reply) {} // 更新标签

  rpc List(ListTags.Request) returns (ListTags.Reply) {} // 查询标签列表
  rpc Page(PageTags.Request) returns (PageTags.Reply) {} // 分页查询标签
}

message BatchCreateTags {
  message Request {
    repeated Tag tags = 1; // 标签信息列表
    int64 user_id = 2; // 用户 ID

    message Tag {
      optional int64 domain_id = 1; // 领域 ID
      optional TagStatus status = 2; // 启停状态
      string name = 3; // 标签名称
      optional string description = 4; // 标签描述
    }
  }

  message Reply {
    repeated Tag rows = 1; // 标签信息列表
  }
}

message UpdateTag {
  message Request {
    int64 tag_id = 1; // 标签 ID
    Tag tag = 2; // 标签信息
    int64 user_id = 3; // 用户 ID

    message Tag {
      optional int64 domain_id = 1; // 领域 ID
      optional TagStatus status = 2; // 启停状态
      string name = 3; // 标签名称
      optional string description = 4; // 标签描述
    }
  }

  message Reply {
    Tag tag = 1; // 标签信息
  }
}

message ListTags {
  message Request {
    TagQueryParams query = 1; // 查询参数
  }

  message Reply {
    repeated Tag rows = 1; // 标签列表
  }
}

message PageTags {
  message Request {
    TagQueryParams query = 1; // 查询参数
    optional common.PageRequest page = 2; // 分页参数
  }

  message Reply {
    repeated Tag rows = 1; // 标签列表
    common.PageReply page = 2; // 分页信息
  }
}

message TagQueryParams {
  repeated int64 ids = 1; // 标签 ID 列表
  optional string name = 2; // 标签名称
  repeated string names = 3; // 标签名称列表
  optional string description = 4; // 标签描述
  optional TagStatus status = 5; // 标签状态
  optional int64 domain_id = 6; // 领域 ID
}
