/*
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.api;

import com.bass.bbs.ApiException;
import com.bass.bbs.model.GetCurrentLocationReply;
import com.bass.bbs.model.UpsertCurrentLocationReply;
import com.bass.bbs.model.UpsertCurrentLocationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for LocationService
 */
@Disabled
public class LocationServiceTest {

    private final LocationService api = new LocationService();

    
    /**
     * 
     *
     * 获取当前账号的地理资料。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCurrentTest() throws ApiException {
        Object body = null;
        
        LocationService.APIgetCurrentRequest request = LocationService.APIgetCurrentRequest.newBuilder()
          .body(body)
          .build();
        GetCurrentLocationReply response = 
        api.getCurrent(request);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 更新当前账号的地理资料。
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void upsertCurrentTest() throws ApiException {
        UpsertCurrentLocationRequest upsertCurrentLocationRequest = null;
        
        LocationService.APIupsertCurrentRequest request = LocationService.APIupsertCurrentRequest.newBuilder()
          .upsertCurrentLocationRequest(upsertCurrentLocationRequest)
          .build();
        UpsertCurrentLocationReply response = 
        api.upsertCurrent(request);

        // TODO: test validations
    }
    
}
