/*
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.bass.bbs.api;

import com.bass.bbs.ApiException;
import com.bass.bbs.model.AddPostscriptReply;
import com.bass.bbs.model.AddPostscriptRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for PostscriptServiceApi
 */
@Disabled
public class PostscriptServiceApiTest {

    private final PostscriptServiceApi api = new PostscriptServiceApi();

    
    /**
     * 
     *
     * 添加文章附言
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postscriptServiceAddTest() throws ApiException {
        AddPostscriptRequest addPostscriptRequest = null;
        
        PostscriptServiceApi.APIpostscriptServiceAddRequest request = PostscriptServiceApi.APIpostscriptServiceAddRequest.newBuilder()
          .addPostscriptRequest(addPostscriptRequest)
          .build();
        AddPostscriptReply response = 
        api.postscriptServiceAdd(request);

        // TODO: test validations
    }
    
}
