/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ArchiveArticleReq
 */
export interface ArchiveArticleReq {
    /**
     * 
     * @type {string}
     * @memberof ArchiveArticleReq
     */
    articleId: string;
    /**
     * 
     * @type {string}
     * @memberof ArchiveArticleReq
     */
    reason?: string;
}

/**
 * Check if a given object implements the ArchiveArticleReq interface.
 */
export function instanceOfArchiveArticleReq(value: object): value is ArchiveArticleReq {
    if (!('articleId' in value) || value['articleId'] === undefined) return false;
    return true;
}

export function ArchiveArticleReqFromJSON(json: any): ArchiveArticleReq {
    return ArchiveArticleReqFromJSONTyped(json, false);
}

export function ArchiveArticleReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveArticleReq {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function ArchiveArticleReqToJSON(json: any): ArchiveArticleReq {
    return ArchiveArticleReqToJSONTyped(json, false);
}

export function ArchiveArticleReqToJSONTyped(value?: ArchiveArticleReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article_id': value['articleId'],
        'reason': value['reason'],
    };
}

