/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleListItem } from './ArticleListItem';
import {
    ArticleListItemFromJSON,
    ArticleListItemFromJSONTyped,
    ArticleListItemToJSON,
    ArticleListItemToJSONTyped,
} from './ArticleListItem';

/**
 * 
 * @export
 * @interface ArticleViewHistoryItem
 */
export interface ArticleViewHistoryItem {
    /**
     * 
     * @type {ArticleListItem}
     * @memberof ArticleViewHistoryItem
     */
    article?: ArticleListItem;
    /**
     * 
     * @type {Date}
     * @memberof ArticleViewHistoryItem
     */
    viewedAt?: Date;
}

/**
 * Check if a given object implements the ArticleViewHistoryItem interface.
 */
export function instanceOfArticleViewHistoryItem(value: object): value is ArticleViewHistoryItem {
    return true;
}

export function ArticleViewHistoryItemFromJSON(json: any): ArticleViewHistoryItem {
    return ArticleViewHistoryItemFromJSONTyped(json, false);
}

export function ArticleViewHistoryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleViewHistoryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'article': json['article'] == null ? undefined : ArticleListItemFromJSON(json['article']),
        'viewedAt': json['viewed_at'] == null ? undefined : (new Date(json['viewed_at'])),
    };
}

export function ArticleViewHistoryItemToJSON(json: any): ArticleViewHistoryItem {
    return ArticleViewHistoryItemToJSONTyped(json, false);
}

export function ArticleViewHistoryItemToJSONTyped(value?: ArticleViewHistoryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ArticleListItemToJSON(value['article']),
        'viewed_at': value['viewedAt'] == null ? value['viewedAt'] : value['viewedAt'].toISOString(),
    };
}

