/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckRegistrationAvailabilityResp
 */
export interface CheckRegistrationAvailabilityResp {
    /**
     * 
     * @type {boolean}
     * @memberof CheckRegistrationAvailabilityResp
     */
    nameAvailable?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CheckRegistrationAvailabilityResp
     */
    emailCanRegister?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CheckRegistrationAvailabilityResp
     */
    phoneCanRegister?: boolean;
}

/**
 * Check if a given object implements the CheckRegistrationAvailabilityResp interface.
 */
export function instanceOfCheckRegistrationAvailabilityResp(value: object): value is CheckRegistrationAvailabilityResp {
    return true;
}

export function CheckRegistrationAvailabilityRespFromJSON(json: any): CheckRegistrationAvailabilityResp {
    return CheckRegistrationAvailabilityRespFromJSONTyped(json, false);
}

export function CheckRegistrationAvailabilityRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckRegistrationAvailabilityResp {
    if (json == null) {
        return json;
    }
    return {
        
        'nameAvailable': json['name_available'] == null ? undefined : json['name_available'],
        'emailCanRegister': json['email_can_register'] == null ? undefined : json['email_can_register'],
        'phoneCanRegister': json['phone_can_register'] == null ? undefined : json['phone_can_register'],
    };
}

export function CheckRegistrationAvailabilityRespToJSON(json: any): CheckRegistrationAvailabilityResp {
    return CheckRegistrationAvailabilityRespToJSONTyped(json, false);
}

export function CheckRegistrationAvailabilityRespToJSONTyped(value?: CheckRegistrationAvailabilityResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name_available': value['nameAvailable'],
        'email_can_register': value['emailCanRegister'],
        'phone_can_register': value['phoneCanRegister'],
    };
}

