/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCommentReq
 */
export interface CreateCommentReq {
    /**
     * 
     * @type {string}
     * @memberof CreateCommentReq
     */
    articleId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentReq
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCommentReq
     */
    replyId?: string;
}

/**
 * Check if a given object implements the CreateCommentReq interface.
 */
export function instanceOfCreateCommentReq(value: object): value is CreateCommentReq {
    if (!('articleId' in value) || value['articleId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function CreateCommentReqFromJSON(json: any): CreateCommentReq {
    return CreateCommentReqFromJSONTyped(json, false);
}

export function CreateCommentReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommentReq {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'],
        'content': json['content'],
        'replyId': json['reply_id'] == null ? undefined : json['reply_id'],
    };
}

export function CreateCommentReqToJSON(json: any): CreateCommentReq {
    return CreateCommentReqToJSONTyped(json, false);
}

export function CreateCommentReqToJSONTyped(value?: CreateCommentReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article_id': value['articleId'],
        'content': value['content'],
        'reply_id': value['replyId'],
    };
}

