/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateDraftArticleReq {
    #[serde(rename = "article")]
    pub article: models::ReqArticle,
}

impl CreateDraftArticleReq {
    pub fn new(article: models::ReqArticle) -> CreateDraftArticleReq {
        CreateDraftArticleReq {
            article,
        }
    }
}

