/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetStatusRelationResp {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::RespRelationStatus>,
}

impl GetStatusRelationResp {
    pub fn new() -> GetStatusRelationResp {
        GetStatusRelationResp {
            status: None,
        }
    }
}

