/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Article } from './Article';
import {
    ArticleFromJSON,
    ArticleFromJSONTyped,
    ArticleToJSON,
    ArticleToJSONTyped,
} from './Article';

/**
 * 
 * @export
 * @interface GetArticleReply
 */
export interface GetArticleReply {
    /**
     * 
     * @type {Article}
     * @memberof GetArticleReply
     */
    article?: Article;
}

/**
 * Check if a given object implements the GetArticleReply interface.
 */
export function instanceOfGetArticleReply(value: object): value is GetArticleReply {
    return true;
}

export function GetArticleReplyFromJSON(json: any): GetArticleReply {
    return GetArticleReplyFromJSONTyped(json, false);
}

export function GetArticleReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArticleReply {
    if (json == null) {
        return json;
    }
    return {
        
        'article': json['article'] == null ? undefined : ArticleFromJSON(json['article']),
    };
}

export function GetArticleReplyToJSON(json: any): GetArticleReply {
    return GetArticleReplyToJSONTyped(json, false);
}

export function GetArticleReplyToJSONTyped(value?: GetArticleReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article': ArticleToJSON(value['article']),
    };
}

