/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RespPrivacySetting } from './RespPrivacySetting';
import {
    RespPrivacySettingFromJSON,
    RespPrivacySettingFromJSONTyped,
    RespPrivacySettingToJSON,
    RespPrivacySettingToJSONTyped,
} from './RespPrivacySetting';

/**
 * 
 * @export
 * @interface GetCurrentPrivacySettingResp
 */
export interface GetCurrentPrivacySettingResp {
    /**
     * 
     * @type {RespPrivacySetting}
     * @memberof GetCurrentPrivacySettingResp
     */
    privacySetting?: RespPrivacySetting;
}

/**
 * Check if a given object implements the GetCurrentPrivacySettingResp interface.
 */
export function instanceOfGetCurrentPrivacySettingResp(value: object): value is GetCurrentPrivacySettingResp {
    return true;
}

export function GetCurrentPrivacySettingRespFromJSON(json: any): GetCurrentPrivacySettingResp {
    return GetCurrentPrivacySettingRespFromJSONTyped(json, false);
}

export function GetCurrentPrivacySettingRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentPrivacySettingResp {
    if (json == null) {
        return json;
    }
    return {
        
        'privacySetting': json['privacy_setting'] == null ? undefined : RespPrivacySettingFromJSON(json['privacy_setting']),
    };
}

export function GetCurrentPrivacySettingRespToJSON(json: any): GetCurrentPrivacySettingResp {
    return GetCurrentPrivacySettingRespToJSONTyped(json, false);
}

export function GetCurrentPrivacySettingRespToJSONTyped(value?: GetCurrentPrivacySettingResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'privacy_setting': RespPrivacySettingToJSON(value['privacySetting']),
    };
}

