/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface GetCurrentLocationReply
 */
export interface GetCurrentLocationReply {
    /**
     * 当前账号地理资料。
     * @type {Location}
     * @memberof GetCurrentLocationReply
     */
    location?: Location;
}

/**
 * Check if a given object implements the GetCurrentLocationReply interface.
 */
export function instanceOfGetCurrentLocationReply(value: object): value is GetCurrentLocationReply {
    return true;
}

export function GetCurrentLocationReplyFromJSON(json: any): GetCurrentLocationReply {
    return GetCurrentLocationReplyFromJSONTyped(json, false);
}

export function GetCurrentLocationReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCurrentLocationReply {
    if (json == null) {
        return json;
    }
    return {
        
        'location': json['location'] == null ? undefined : LocationFromJSON(json['location']),
    };
}

export function GetCurrentLocationReplyToJSON(json: any): GetCurrentLocationReply {
    return GetCurrentLocationReplyToJSONTyped(json, false);
}

export function GetCurrentLocationReplyToJSONTyped(value?: GetCurrentLocationReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'location': LocationToJSON(value['location']),
    };
}

