/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetStatusRelationRequest
 */
export interface GetStatusRelationRequest {
    /**
     * 
     * @type {string}
     * @memberof GetStatusRelationRequest
     */
    targetId?: string;
}

/**
 * Check if a given object implements the GetStatusRelationRequest interface.
 */
export function instanceOfGetStatusRelationRequest(value: object): value is GetStatusRelationRequest {
    return true;
}

export function GetStatusRelationRequestFromJSON(json: any): GetStatusRelationRequest {
    return GetStatusRelationRequestFromJSONTyped(json, false);
}

export function GetStatusRelationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetStatusRelationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'targetId': json['target_id'] == null ? undefined : json['target_id'],
    };
}

export function GetStatusRelationRequestToJSON(json: any): GetStatusRelationRequest {
    return GetStatusRelationRequestToJSONTyped(json, false);
}

export function GetStatusRelationRequestToJSONTyped(value?: GetStatusRelationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_id': value['targetId'],
    };
}

