/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LikeArticleRequest
 */
export interface LikeArticleRequest {
    /**
     * 
     * @type {string}
     * @memberof LikeArticleRequest
     */
    articleId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof LikeArticleRequest
     */
    active?: boolean;
}

/**
 * Check if a given object implements the LikeArticleRequest interface.
 */
export function instanceOfLikeArticleRequest(value: object): value is LikeArticleRequest {
    return true;
}

export function LikeArticleRequestFromJSON(json: any): LikeArticleRequest {
    return LikeArticleRequestFromJSONTyped(json, false);
}

export function LikeArticleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeArticleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'articleId': json['article_id'] == null ? undefined : json['article_id'],
        'active': json['active'] == null ? undefined : json['active'],
    };
}

export function LikeArticleRequestToJSON(json: any): LikeArticleRequest {
    return LikeArticleRequestToJSONTyped(json, false);
}

export function LikeArticleRequestToJSONTyped(value?: LikeArticleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'article_id': value['articleId'],
        'active': value['active'],
    };
}

