/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListFollowingRelationsResp {
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<models::PageResp>,
    #[serde(rename = "rows", skip_serializing_if = "Option::is_none")]
    pub rows: Option<Vec<models::RespRelation>>,
}

impl ListFollowingRelationsResp {
    pub fn new() -> ListFollowingRelationsResp {
        ListFollowingRelationsResp {
            page: None,
            rows: None,
        }
    }
}

