/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageRequest } from './PageRequest';
import {
    PageRequestFromJSON,
    PageRequestFromJSONTyped,
    PageRequestToJSON,
    PageRequestToJSONTyped,
} from './PageRequest';
import type { DomainQuery } from './DomainQuery';
import {
    DomainQueryFromJSON,
    DomainQueryFromJSONTyped,
    DomainQueryToJSON,
    DomainQueryToJSONTyped,
} from './DomainQuery';

/**
 * 
 * @export
 * @interface ListDomainsRequest
 */
export interface ListDomainsRequest {
    /**
     * 
     * @type {PageRequest}
     * @memberof ListDomainsRequest
     */
    page?: PageRequest;
    /**
     * 
     * @type {DomainQuery}
     * @memberof ListDomainsRequest
     */
    query?: DomainQuery;
}

/**
 * Check if a given object implements the ListDomainsRequest interface.
 */
export function instanceOfListDomainsRequest(value: object): value is ListDomainsRequest {
    return true;
}

export function ListDomainsRequestFromJSON(json: any): ListDomainsRequest {
    return ListDomainsRequestFromJSONTyped(json, false);
}

export function ListDomainsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListDomainsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : PageRequestFromJSON(json['page']),
        'query': json['query'] == null ? undefined : DomainQueryFromJSON(json['query']),
    };
}

export function ListDomainsRequestToJSON(json: any): ListDomainsRequest {
    return ListDomainsRequestToJSONTyped(json, false);
}

export function ListDomainsRequestToJSONTyped(value?: ListDomainsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': PageRequestToJSON(value['page']),
        'query': DomainQueryToJSON(value['query']),
    };
}

