/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Relation } from './Relation';
import {
    RelationFromJSON,
    RelationFromJSONTyped,
    RelationToJSON,
    RelationToJSONTyped,
} from './Relation';
import type { PageReply } from './PageReply';
import {
    PageReplyFromJSON,
    PageReplyFromJSONTyped,
    PageReplyToJSON,
    PageReplyToJSONTyped,
} from './PageReply';

/**
 * 
 * @export
 * @interface ListBlockedRelationsReply
 */
export interface ListBlockedRelationsReply {
    /**
     * 分页结果。
     * @type {PageReply}
     * @memberof ListBlockedRelationsReply
     */
    page?: PageReply;
    /**
     * 账号关系列表。
     * @type {Array<Relation>}
     * @memberof ListBlockedRelationsReply
     */
    rows?: Array<Relation>;
}

/**
 * Check if a given object implements the ListBlockedRelationsReply interface.
 */
export function instanceOfListBlockedRelationsReply(value: object): value is ListBlockedRelationsReply {
    return true;
}

export function ListBlockedRelationsReplyFromJSON(json: any): ListBlockedRelationsReply {
    return ListBlockedRelationsReplyFromJSONTyped(json, false);
}

export function ListBlockedRelationsReplyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListBlockedRelationsReply {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : PageReplyFromJSON(json['page']),
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(RelationFromJSON)),
    };
}

export function ListBlockedRelationsReplyToJSON(json: any): ListBlockedRelationsReply {
    return ListBlockedRelationsReplyToJSONTyped(json, false);
}

export function ListBlockedRelationsReplyToJSONTyped(value?: ListBlockedRelationsReply | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': PageReplyToJSON(value['page']),
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(RelationToJSON)),
    };
}

