/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReqArticleQuery } from './ReqArticleQuery';
import {
    ReqArticleQueryFromJSON,
    ReqArticleQueryFromJSONTyped,
    ReqArticleQueryToJSON,
    ReqArticleQueryToJSONTyped,
} from './ReqArticleQuery';
import type { PageReq } from './PageReq';
import {
    PageReqFromJSON,
    PageReqFromJSONTyped,
    PageReqToJSON,
    PageReqToJSONTyped,
} from './PageReq';

/**
 * 
 * @export
 * @interface ListArticlesReq
 */
export interface ListArticlesReq {
    /**
     * 
     * @type {PageReq}
     * @memberof ListArticlesReq
     */
    page?: PageReq;
    /**
     * 
     * @type {ReqArticleQuery}
     * @memberof ListArticlesReq
     */
    query?: ReqArticleQuery;
}

/**
 * Check if a given object implements the ListArticlesReq interface.
 */
export function instanceOfListArticlesReq(value: object): value is ListArticlesReq {
    return true;
}

export function ListArticlesReqFromJSON(json: any): ListArticlesReq {
    return ListArticlesReqFromJSONTyped(json, false);
}

export function ListArticlesReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListArticlesReq {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : PageReqFromJSON(json['page']),
        'query': json['query'] == null ? undefined : ReqArticleQueryFromJSON(json['query']),
    };
}

export function ListArticlesReqToJSON(json: any): ListArticlesReq {
    return ListArticlesReqToJSONTyped(json, false);
}

export function ListArticlesReqToJSONTyped(value?: ListArticlesReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': PageReqToJSON(value['page']),
        'query': ReqArticleQueryToJSON(value['query']),
    };
}

