/*
 * 
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LoginAccountResp {
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
    #[serde(rename = "refresh_token", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<String>,
    #[serde(rename = "access_token_expires_at", skip_serializing_if = "Option::is_none")]
    pub access_token_expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "refresh_token_expires_at", skip_serializing_if = "Option::is_none")]
    pub refresh_token_expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "session_expires_at", skip_serializing_if = "Option::is_none")]
    pub session_expires_at: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nickname", skip_serializing_if = "Option::is_none")]
    pub nickname: Option<String>,
}

impl LoginAccountResp {
    pub fn new() -> LoginAccountResp {
        LoginAccountResp {
            access_token: None,
            refresh_token: None,
            access_token_expires_at: None,
            refresh_token_expires_at: None,
            session_expires_at: None,
            user_id: None,
            name: None,
            nickname: None,
        }
    }
}

