/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticleViewHistoryItem } from './ArticleViewHistoryItem';
import {
    ArticleViewHistoryItemFromJSON,
    ArticleViewHistoryItemFromJSONTyped,
    ArticleViewHistoryItemToJSON,
    ArticleViewHistoryItemToJSONTyped,
} from './ArticleViewHistoryItem';
import type { PageResp } from './PageResp';
import {
    PageRespFromJSON,
    PageRespFromJSONTyped,
    PageRespToJSON,
    PageRespToJSONTyped,
} from './PageResp';

/**
 * 
 * @export
 * @interface PageArticleViewHistoryResp
 */
export interface PageArticleViewHistoryResp {
    /**
     * 
     * @type {Array<ArticleViewHistoryItem>}
     * @memberof PageArticleViewHistoryResp
     */
    rows?: Array<ArticleViewHistoryItem>;
    /**
     * 
     * @type {PageResp}
     * @memberof PageArticleViewHistoryResp
     */
    page?: PageResp;
}

/**
 * Check if a given object implements the PageArticleViewHistoryResp interface.
 */
export function instanceOfPageArticleViewHistoryResp(value: object): value is PageArticleViewHistoryResp {
    return true;
}

export function PageArticleViewHistoryRespFromJSON(json: any): PageArticleViewHistoryResp {
    return PageArticleViewHistoryRespFromJSONTyped(json, false);
}

export function PageArticleViewHistoryRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageArticleViewHistoryResp {
    if (json == null) {
        return json;
    }
    return {
        
        'rows': json['rows'] == null ? undefined : ((json['rows'] as Array<any>).map(ArticleViewHistoryItemFromJSON)),
        'page': json['page'] == null ? undefined : PageRespFromJSON(json['page']),
    };
}

export function PageArticleViewHistoryRespToJSON(json: any): PageArticleViewHistoryResp {
    return PageArticleViewHistoryRespToJSONTyped(json, false);
}

export function PageArticleViewHistoryRespToJSONTyped(value?: PageArticleViewHistoryResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rows': value['rows'] == null ? undefined : ((value['rows'] as Array<any>).map(ArticleViewHistoryItemToJSON)),
        'page': PageRespToJSON(value['page']),
    };
}

