/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileLocation
 */
export interface ProfileLocation {
    /**
     * 
     * @type {string}
     * @memberof ProfileLocation
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileLocation
     */
    province?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileLocation
     */
    city?: string;
}

/**
 * Check if a given object implements the ProfileLocation interface.
 */
export function instanceOfProfileLocation(value: object): value is ProfileLocation {
    return true;
}

export function ProfileLocationFromJSON(json: any): ProfileLocation {
    return ProfileLocationFromJSONTyped(json, false);
}

export function ProfileLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'country': json['country'] == null ? undefined : json['country'],
        'province': json['province'] == null ? undefined : json['province'],
        'city': json['city'] == null ? undefined : json['city'],
    };
}

export function ProfileLocationToJSON(json: any): ProfileLocation {
    return ProfileLocationToJSONTyped(json, false);
}

export function ProfileLocationToJSONTyped(value?: ProfileLocation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'country': value['country'],
        'province': value['province'],
        'city': value['city'],
    };
}

