/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterAccountReq
 */
export interface RegisterAccountReq {
    /**
     * 
     * @type {string}
     * @memberof RegisterAccountReq
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterAccountReq
     */
    password: string;
}

/**
 * Check if a given object implements the RegisterAccountReq interface.
 */
export function instanceOfRegisterAccountReq(value: object): value is RegisterAccountReq {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function RegisterAccountReqFromJSON(json: any): RegisterAccountReq {
    return RegisterAccountReqFromJSONTyped(json, false);
}

export function RegisterAccountReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterAccountReq {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function RegisterAccountReqToJSON(json: any): RegisterAccountReq {
    return RegisterAccountReqToJSONTyped(json, false);
}

export function RegisterAccountReqToJSONTyped(value?: RegisterAccountReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

