/*
 * Bass BBS API
 *
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RespCommentThread {
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<models::RespCommentListItem>,
    #[serde(rename = "preview_replies", skip_serializing_if = "Option::is_none")]
    pub preview_replies: Option<Vec<models::RespCommentListItem>>,
    #[serde(rename = "reply_count", skip_serializing_if = "Option::is_none")]
    pub reply_count: Option<i32>,
    #[serde(rename = "has_more_replies", skip_serializing_if = "Option::is_none")]
    pub has_more_replies: Option<bool>,
}

impl RespCommentThread {
    pub fn new() -> RespCommentThread {
        RespCommentThread {
            root: None,
            preview_replies: None,
            reply_count: None,
            has_more_replies: None,
        }
    }
}

