/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RespRecord
 */
export interface RespRecord {
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    transactionNo?: string;
    /**
     * 
     * @type {RespRecordRecordTypeEnum}
     * @memberof RespRecord
     */
    recordType?: RespRecordRecordTypeEnum;
    /**
     * 
     * @type {RespRecordDirectionEnum}
     * @memberof RespRecord
     */
    direction?: RespRecordDirectionEnum;
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    balanceBefore?: string;
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    balanceAfter?: string;
    /**
     * 
     * @type {string}
     * @memberof RespRecord
     */
    remark?: string;
    /**
     * 
     * @type {Date}
     * @memberof RespRecord
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const RespRecordRecordTypeEnum = {
    ECONOMY_RECORD_TYPE_UNSPECIFIED: 'ECONOMY_RECORD_TYPE_UNSPECIFIED',
    ECONOMY_RECORD_TYPE_SIGN_IN_REWARD: 'ECONOMY_RECORD_TYPE_SIGN_IN_REWARD',
    ECONOMY_RECORD_TYPE_ARTICLE_THANK_REWARD: 'ECONOMY_RECORD_TYPE_ARTICLE_THANK_REWARD',
    ECONOMY_RECORD_TYPE_COMMENT_THANK_REWARD: 'ECONOMY_RECORD_TYPE_COMMENT_THANK_REWARD',
    ECONOMY_RECORD_TYPE_ARTICLE_REWARD_OUT: 'ECONOMY_RECORD_TYPE_ARTICLE_REWARD_OUT',
    ECONOMY_RECORD_TYPE_ARTICLE_REWARD_IN: 'ECONOMY_RECORD_TYPE_ARTICLE_REWARD_IN',
    ECONOMY_RECORD_TYPE_ADMIN_ADD: 'ECONOMY_RECORD_TYPE_ADMIN_ADD',
    ECONOMY_RECORD_TYPE_ADMIN_DEDUCT: 'ECONOMY_RECORD_TYPE_ADMIN_DEDUCT'
} as const;
export type RespRecordRecordTypeEnum = typeof RespRecordRecordTypeEnum[keyof typeof RespRecordRecordTypeEnum];

/**
 * @export
 */
export const RespRecordDirectionEnum = {
    ECONOMY_RECORD_DIRECTION_UNSPECIFIED: 'ECONOMY_RECORD_DIRECTION_UNSPECIFIED',
    ECONOMY_RECORD_DIRECTION_INCOME: 'ECONOMY_RECORD_DIRECTION_INCOME',
    ECONOMY_RECORD_DIRECTION_EXPENSE: 'ECONOMY_RECORD_DIRECTION_EXPENSE'
} as const;
export type RespRecordDirectionEnum = typeof RespRecordDirectionEnum[keyof typeof RespRecordDirectionEnum];


/**
 * Check if a given object implements the RespRecord interface.
 */
export function instanceOfRespRecord(value: object): value is RespRecord {
    return true;
}

export function RespRecordFromJSON(json: any): RespRecord {
    return RespRecordFromJSONTyped(json, false);
}

export function RespRecordFromJSONTyped(json: any, ignoreDiscriminator: boolean): RespRecord {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'transactionNo': json['transaction_no'] == null ? undefined : json['transaction_no'],
        'recordType': json['record_type'] == null ? undefined : json['record_type'],
        'direction': json['direction'] == null ? undefined : json['direction'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'balanceBefore': json['balance_before'] == null ? undefined : json['balance_before'],
        'balanceAfter': json['balance_after'] == null ? undefined : json['balance_after'],
        'remark': json['remark'] == null ? undefined : json['remark'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function RespRecordToJSON(json: any): RespRecord {
    return RespRecordToJSONTyped(json, false);
}

export function RespRecordToJSONTyped(value?: RespRecord | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'transaction_no': value['transactionNo'],
        'record_type': value['recordType'],
        'direction': value['direction'],
        'amount': value['amount'],
        'balance_before': value['balanceBefore'],
        'balance_after': value['balanceAfter'],
        'remark': value['remark'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
    };
}

