/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StartEmailRegistrationRequest
 */
export interface StartEmailRegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof StartEmailRegistrationRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof StartEmailRegistrationRequest
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof StartEmailRegistrationRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof StartEmailRegistrationRequest
     */
    nickname?: string;
}

/**
 * Check if a given object implements the StartEmailRegistrationRequest interface.
 */
export function instanceOfStartEmailRegistrationRequest(value: object): value is StartEmailRegistrationRequest {
    return true;
}

export function StartEmailRegistrationRequestFromJSON(json: any): StartEmailRegistrationRequest {
    return StartEmailRegistrationRequestFromJSONTyped(json, false);
}

export function StartEmailRegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartEmailRegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'name': json['name'] == null ? undefined : json['name'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
    };
}

export function StartEmailRegistrationRequestToJSON(json: any): StartEmailRegistrationRequest {
    return StartEmailRegistrationRequestToJSONTyped(json, false);
}

export function StartEmailRegistrationRequestToJSONTyped(value?: StartEmailRegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
        'name': value['name'],
        'nickname': value['nickname'],
    };
}

