/* tslint:disable */
/* eslint-disable */
/**
 * Bass BBS API
 * Bass 社区 HTTP/JSON API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ThankCommentResp
 */
export interface ThankCommentResp {
    /**
     * 
     * @type {boolean}
     * @memberof ThankCommentResp
     */
    thanked?: boolean;
}

/**
 * Check if a given object implements the ThankCommentResp interface.
 */
export function instanceOfThankCommentResp(value: object): value is ThankCommentResp {
    return true;
}

export function ThankCommentRespFromJSON(json: any): ThankCommentResp {
    return ThankCommentRespFromJSONTyped(json, false);
}

export function ThankCommentRespFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThankCommentResp {
    if (json == null) {
        return json;
    }
    return {
        
        'thanked': json['thanked'] == null ? undefined : json['thanked'],
    };
}

export function ThankCommentRespToJSON(json: any): ThankCommentResp {
    return ThankCommentRespToJSONTyped(json, false);
}

export function ThankCommentRespToJSONTyped(value?: ThankCommentResp | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'thanked': value['thanked'],
    };
}

