// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: signal/v1/model.proto

package v1

import (
	_ "common/api/user/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// node 节点
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_signal_v1_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_signal_v1_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_signal_v1_model_proto_rawDescGZIP(), []int{0}
}

// Websocket 消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=common.api.signal.v1.MessageType" json:"type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_signal_v1_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_signal_v1_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_signal_v1_model_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *Message) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_signal_v1_model_proto protoreflect.FileDescriptor

const file_signal_v1_model_proto_rawDesc = "" +
	"\n" +
	"\x15signal/v1/model.proto\x12\x14common.api.signal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12user/v1/user.proto\x1a\x18signal/v1/constant.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x06\n" +
	"\x04Node\"s\n" +
	"\aMessage\x125\n" +
	"\x04type\x18\x01 \x01(\x0e2!.common.api.signal.v1.MessageTypeR\x04type\x121\n" +
	"\apayload\x18\x02 \x01(\v2\x17.google.protobuf.StructR\apayloadB\x19Z\x17common/api/signal/v1;v1b\x06proto3"

var (
	file_signal_v1_model_proto_rawDescOnce sync.Once
	file_signal_v1_model_proto_rawDescData []byte
)

func file_signal_v1_model_proto_rawDescGZIP() []byte {
	file_signal_v1_model_proto_rawDescOnce.Do(func() {
		file_signal_v1_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_signal_v1_model_proto_rawDesc), len(file_signal_v1_model_proto_rawDesc)))
	})
	return file_signal_v1_model_proto_rawDescData
}

var file_signal_v1_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_signal_v1_model_proto_goTypes = []any{
	(*Node)(nil),            // 0: common.api.signal.v1.Node
	(*Message)(nil),         // 1: common.api.signal.v1.Message
	(MessageType)(0),        // 2: common.api.signal.v1.MessageType
	(*structpb.Struct)(nil), // 3: google.protobuf.Struct
}
var file_signal_v1_model_proto_depIdxs = []int32{
	2, // 0: common.api.signal.v1.Message.type:type_name -> common.api.signal.v1.MessageType
	3, // 1: common.api.signal.v1.Message.payload:type_name -> google.protobuf.Struct
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_signal_v1_model_proto_init() }
func file_signal_v1_model_proto_init() {
	if File_signal_v1_model_proto != nil {
		return
	}
	file_signal_v1_constant_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_signal_v1_model_proto_rawDesc), len(file_signal_v1_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_signal_v1_model_proto_goTypes,
		DependencyIndexes: file_signal_v1_model_proto_depIdxs,
		MessageInfos:      file_signal_v1_model_proto_msgTypes,
	}.Build()
	File_signal_v1_model_proto = out.File
	file_signal_v1_model_proto_goTypes = nil
	file_signal_v1_model_proto_depIdxs = nil
}
