syntax = "proto3";

package common.api.app.common;

import "google/protobuf/duration.proto";

option go_package = "common/api/gen/common;common";

message Bootstrap {
  message Server {
    string name = 1;
    string version = 2;
    string mode = 3;
  }
  Server server = 1;
  message Config {
    Consul consul = 1;
    message Consul {
      string address = 1;
      string token = 2;
      string path = 3;
      google.protobuf.Duration timeout = 4;
    }
  }
  Config config = 2;
  message Log {
    string level = 1; // debug, info, warn, error, fatal, panic
    string file = 2;
  }
  Log log = 3;
}

message HTTP {
  string network = 1;
  string host = 2;
  int32 port = 3;
  google.protobuf.Duration timeout = 4;
}

message GRPC {
  string network = 1;
  string host = 2;
  int32 port = 3;
  google.protobuf.Duration timeout = 4;
}

message Database {
  string driver = 1;
  string source = 2;
  bool merge = 3;
}
message Redis {
  string addr = 1;
  string password = 2;
  google.protobuf.Duration dial_timeout = 3;
  int32 db = 4;
  google.protobuf.Duration read_timeout = 5;
  google.protobuf.Duration write_timeout = 6;
  int32 pool_size = 7;
  int32 min_idle_conns = 8;
  google.protobuf.Duration pool_timeout = 9;
  google.protobuf.Duration conn_max_idle_time = 10;
  google.protobuf.Duration conn_max_life_time = 11;
}
message RabbitMQ {
  string url = 1;
  google.protobuf.Duration heartbeat = 2;
  google.protobuf.Duration dial_timeout = 3;
  int32 prefetch_count = 4;
  bool prefetch_global = 5;
  int32 delivery_mode = 6;
  bool auto_ack = 7;
}
message Consul {
  string address = 1;
  string datacenter = 2;
  string token = 3;
  google.protobuf.Duration dial_timeout = 4;
}
