syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service AuthService {
  // 使用邮箱发起账号注册
  rpc StartEmailRegistration(StartEmailRegistration.Request) returns (StartEmailRegistration.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/start-email-registration"
      body: "*"
    };
  }

  // 校验邮箱注册验证码
  rpc VerifyEmailRegistration(VerifyEmailRegistration.Request) returns (VerifyEmailRegistration.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/verify-email-registration"
      body: "*"
    };
  }

  // 使用手机号发起账号注册
  rpc StartPhoneRegistration(StartPhoneRegistration.Request) returns (StartPhoneRegistration.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/start-phone-registration"
      body: "*"
    };
  }

  // 校验手机号注册验证码
  rpc VerifyPhoneRegistration(VerifyPhoneRegistration.Request) returns (VerifyPhoneRegistration.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/verify-phone-registration"
      body: "*"
    };
  }

  // 使用密码登录账号
  rpc LoginByPassword(LoginByPassword.Request) returns (LoginByPassword.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/login-by-password"
      body: "*"
    };
  }

  // 登出当前登录账号
  rpc Logout(Logout.Request) returns (Logout.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/logout"
      body: "*"
    };
  }
}

message StartEmailRegistration {
  message Request {
    string email = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyEmailRegistration {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message StartPhoneRegistration {
  message Request {
    string phone = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyPhoneRegistration {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message LoginByPassword {
  message Request {
    string account = 1;
    string password = 2;
  }
  message Reply {
    string token = 1;
    Account account = 2;
  }
}

message Logout {
  message Request {}
  message Reply {}
}
