syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service AuthService {
  // 使用邮箱发起账号注册
  rpc RegisterEmail(RegisterEmail.Request) returns (RegisterEmail.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/register-email"
      body: "*"
    };
  }

  // 校验邮箱注册验证码
  rpc VerifyEmailRegister(VerifyEmailRegister.Request) returns (VerifyEmailRegister.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/verify-email-register"
      body: "*"
    };
  }

  // 使用手机号发起账号注册
  rpc RegisterPhone(RegisterPhone.Request) returns (RegisterPhone.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/register-phone"
      body: "*"
    };
  }

  // 校验手机号注册验证码
  rpc VerifyPhoneRegister(VerifyPhoneRegister.Request) returns (VerifyPhoneRegister.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/verify-phone-register"
      body: "*"
    };
  }

  // 使用密码登录账号
  rpc LoginPassword(LoginPassword.Request) returns (LoginPassword.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/login-password"
      body: "*"
    };
  }

  // 登出当前登录账号
  rpc Logout(Logout.Request) returns (Logout.Reply) {
    option (google.api.http) = {
      post: "/v1/user/auth/logout"
      body: "*"
    };
  }
}

message RegisterEmail {
  message Request {
    string email = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyEmailRegister {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message RegisterPhone {
  message Request {
    string phone = 1;
    string password = 2;
    string name = 3;
    optional string nickname = 4;
  }
  message Reply {
    string code_token = 1;
  }
}

message VerifyPhoneRegister {
  message Request {
    string code = 1;
    string code_token = 2;
  }
  message Reply {}
}

message LoginPassword {
  message Request {
    string account = 1;
    string password = 2;
  }
  message Reply {
    string token = 1;
    Account account = 2;
  }
}

message Logout {
  message Request {}
  message Reply {}
}
