syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service PreferencesService {
  // 获取当前登录账号的偏好设置
  rpc GetCurrent(GetCurrentPreferences.Request) returns (GetCurrentPreferences.Reply) {
    option (google.api.http) = {
      post: "/v1/user/preference/get-current"
      body: "*"
    };
  }

  // 更新当前登录账号的偏好设置
  rpc Update(UpdatePreferences.Request) returns (UpdatePreferences.Reply) {
    option (google.api.http) = {
      post: "/v1/user/preference/update-current"
      body: "*"
    };
  }
}

message GetCurrentPreferences {
  message Request {}
  message Reply {
    Preference preference = 1;
  }
}

message UpdatePreferences {
  message Request {
    optional string language = 1;
    optional string timezone = 2;
    optional string theme = 3;
    optional string mobile_theme = 4;
    optional bool enable_web_notify = 5;
    optional bool enable_email_subscribe = 6;
  }
  message Reply {
    Preference preference = 1;
  }
}
