syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "common/enums/language.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service PreferencesService {
  // 获取当前登录账号的偏好设置
  rpc GetCurrent(GetCurrentPreferences.Request) returns (GetCurrentPreferences.Reply) {
    option (google.api.http) = {
      post: "/v1/user/preference/get-current"
      body: "*"
    };
  }

  // 更新当前登录账号的偏好设置
  rpc UpdateCurrent(UpdateCurrentPreferences.Request) returns (UpdateCurrentPreferences.Reply) {
    option (google.api.http) = {
      post: "/v1/user/preference/update-current"
      body: "*"
    };
  }
}

message GetCurrentPreferences {
  message Request {}
  message Reply {
    Preference preference = 1;
  }
}

message UpdateCurrentPreferences {
  message Request {
    optional string timezone = 2;
    optional string theme = 3;
    optional string mobile_theme = 4;
    optional common.enums.Language language = 7;
  }
  message Reply {
    Preference preference = 1;
  }
}
