syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service RelationService {
  // 当前账号关注目标账号
  rpc Follow(FollowRelation.Request) returns (FollowRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/follow"
      body: "*"
    };
  }

  // 当前账号取消关注目标账号
  rpc Unfollow(UnfollowRelation.Request) returns (UnfollowRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/unfollow"
      body: "*"
    };
  }

  // 当前账号拉黑目标账号
  rpc Block(BlockRelation.Request) returns (BlockRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/block"
      body: "*"
    };
  }

  // 当前账号取消拉黑目标账号
  rpc Unblock(UnblockRelation.Request) returns (UnblockRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/unblock"
      body: "*"
    };
  }

  // 分页查询当前账号关注的账号列表
  rpc ListFollowing(ListFollowingRelations.Request) returns (ListFollowingRelations.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/list-following"
      body: "*"
    };
  }

  // 分页查询当前账号的粉丝账号列表
  rpc ListFollowers(ListFollowersRelations.Request) returns (ListFollowersRelations.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/list-followers"
      body: "*"
    };
  }

  // 分页查询当前账号拉黑的账号列表
  rpc ListBlocked(ListBlockedRelations.Request) returns (ListBlockedRelations.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/list-blocked"
      body: "*"
    };
  }

  // 查询当前账号与目标账号之间的关系
  rpc GetStatus(GetStatusRelation.Request) returns (GetStatusRelation.Reply) {
    option (google.api.http) = {
      post: "/v1/user/relation/get-status"
      body: "*"
    };
  }
}

message FollowRelation {
  message Request {
    int64 target_id = 1;
  }
  message Reply {}
}

message UnfollowRelation {
  message Request {
    int64 target_id = 1;
  }
  message Reply {}
}

message BlockRelation {
  message Request {
    int64 target_id = 1;
  }
  message Reply {}
}

message UnblockRelation {
  message Request {
    int64 target_id = 1;
  }
  message Reply {}
}

message ListFollowingRelations {
  message Request {
    PageRequest page = 1;
  }
  message Reply {
    PageReply page = 1;
    repeated Relation rows = 2;
  }
}

message ListFollowersRelations {
  message Request {
    PageRequest page = 1;
  }
  message Reply {
    PageReply page = 1;
    repeated Relation rows = 2;
  }
}

message ListBlockedRelations {
  message Request {
    PageRequest page = 1;
  }
  message Reply {
    PageReply page = 1;
    repeated Relation rows = 2;
  }
}

message GetStatusRelation {
  message Request {
    int64 target_id = 1;
  }
  message Reply {
    RelationStatus status = 1;
  }
}
