syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

service TfaService {
  // 校验当前登录账号的二步验证码
  rpc Validate(ValidateTfa.Request) returns (ValidateTfa.Reply) {
    option (google.api.http) = {
      post: "/v1/user/tfa/validate"
      body: "*"
    };
  }

  // 开始启用二步验证
  rpc BeginEnable(BeginEnableTfa.Request) returns (BeginEnableTfa.Reply) {
    option (google.api.http) = {
      post: "/v1/user/tfa/begin-enable"
      body: "*"
    };
  }

  // 确认二步验证码并正式启用二步验证
  rpc ConfirmEnable(ConfirmEnableTfa.Request) returns (ConfirmEnableTfa.Reply) {
    option (google.api.http) = {
      post: "/v1/user/tfa/confirm-enable"
      body: "*"
    };
  }

  // 校验二步验证码并关闭二步验证
  rpc Disable(DisableTfa.Request) returns (DisableTfa.Reply) {
    option (google.api.http) = {
      post: "/v1/user/tfa/disable"
      body: "*"
    };
  }

  // 获取当前登录账号的二步验证状态
  rpc GetCurrent(GetCurrentTfa.Request) returns (GetCurrentTfa.Reply) {
    option (google.api.http) = {
      post: "/v1/user/tfa/get-current"
      body: "*"
    };
  }
}

message ValidateTfa {
  message Request {
    string code = 1;
  }
  message Reply {
    bool verified = 1;
  }
}

message BeginEnableTfa {
  message Request {}
  message Reply {
    bytes data = 1;
    string content_type = 2;
  }
}

message ConfirmEnableTfa {
  message Request {
    string code = 1;
  }
  message Reply {}
}

message DisableTfa {
  message Request {
    string code = 1;
  }
  message Reply {}
}

message GetCurrentTfa {
  message Request {}
  message Reply {
    Tfa tfa = 1;
  }
}
