syntax = "proto3";

package common.api.app.bbs.v1.user;

import "bbs/v1/user/model.proto";
import "gnostic/openapi/v3/annotations.proto";
import "google/api/annotations.proto";

option go_package = "common/api/gen/bbs/v1/user;user";

// TOTP 认证接口。
service TotpService {
  // 开始启用 TOTP。
  rpc BeginEnable(BeginEnableTotp.Request) returns (BeginEnableTotp.Reply) {
    option (google.api.http) = {
      post: "/v1/user/totp/begin-enable"
      body: "*"
    };
  }

  // 确认 TOTP 验证码并正式启用 TOTP。
  rpc ConfirmEnable(ConfirmEnableTotp.Request) returns (ConfirmEnableTotp.Reply) {
    option (google.api.http) = {
      post: "/v1/user/totp/confirm-enable"
      body: "*"
    };
  }

  // 校验 TOTP 验证码并关闭 TOTP。
  rpc Disable(DisableTotp.Request) returns (DisableTotp.Reply) {
    option (google.api.http) = {
      post: "/v1/user/totp/disable"
      body: "*"
    };
  }

  // 获取当前账号的 TOTP 状态。
  rpc GetCurrent(GetCurrentTotp.Request) returns (GetCurrentTotp.Reply) {
    option (google.api.http) = {
      post: "/v1/user/totp/get-current"
      body: "*"
    };
  }
}

// 开始启用 TOTP。
message BeginEnableTotp {
  message Request {}
  message Reply {
    // TOTP 绑定 URL。
    string url = 1;
    // TOTP 二维码图片数据。
    bytes qr_code = 2;
  }
}

// 确认 TOTP 验证码并正式启用 TOTP。
message ConfirmEnableTotp {
  message Request {
    // TOTP 验证码。
    string code = 1;

    option (gnostic.openapi.v3.schema) = {required: "code"};
  }
  message Reply {}
}

// 校验 TOTP 验证码并关闭 TOTP。
message DisableTotp {
  message Request {
    // TOTP 验证码。
    string code = 1;

    option (gnostic.openapi.v3.schema) = {required: "code"};
  }
  message Reply {}
}

// 获取当前账号的 TOTP 状态。
message GetCurrentTotp {
  message Request {}
  message Reply {
    // TOTP 认证状态。
    Totp totp = 1;
  }
}
