syntax = "proto3";

package common.api.app.bff_bbs.v1.content;

import "bff_bbs/v1/content/article.proto";
import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "common/proto/gen/bff_bbs/v1/content;content";

// BreezemoonService 提供社区短动态入口。
service BreezemoonService {
  rpc Create(CreateBreezemoon.Req) returns (CreateBreezemoon.Resp) {
    option (google.api.http) = { post: "/v1/content/breezemoon/create" body: "*" };
  }
  rpc PagePublic(PagePublicBreezemoons.Req) returns (PageBreezemoons.Resp) {
    option (google.api.http) = { post: "/v1/content/breezemoon/page-public" body: "*" };
  }
  rpc PageWatching(PageWatchingBreezemoons.Req) returns (PageBreezemoons.Resp) {
    option (google.api.http) = { post: "/v1/content/breezemoon/page-watching" body: "*" };
  }
  rpc PageMember(PageMemberBreezemoons.Req) returns (PageBreezemoons.Resp) {
    option (google.api.http) = { post: "/v1/content/breezemoon/page-member" body: "*" };
  }
}

message CreateBreezemoon {
  message Req {
    string content = 1;
  }
  message Resp {
    Breezemoon breezemoon = 1;
  }
}

message PagePublicBreezemoons {
  message Req {
    optional string cursor = 1;
    uint32 size = 2;
  }
}

message PageWatchingBreezemoons {
  message Req {
    optional string cursor = 1;
    uint32 size = 2;
  }
}

message PageMemberBreezemoons {
  message Req {
    string name = 1;
    optional string cursor = 2;
    uint32 size = 3;
  }
}

message PageBreezemoons {
  message Resp {
    repeated Breezemoon rows = 1;
    optional string next_cursor = 2;
  }
}

message Breezemoon {
  int64 id = 1;
  string content = 2;
  AccountProfile author = 3;
  optional string city = 4;
  google.protobuf.Timestamp created_at = 1000;
}
