syntax = "proto3";

package common.api.app.infra.v1;

import "google/api/annotations.proto";
import "common/common.proto";
import "infra/v1/model.proto";

option go_package = "common/api/gen/infra/v1;v1";

// Oss 服务
service InfraOssService {

  // 获取上传文件凭证
  rpc GetUploadToken (GetUploadTokenOss.Request) returns (GetUploadTokenOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/get-upload-token"
      body: "*"
    };
  }

  // 审核 oss 对象
  rpc Audit (AuditOss.Request) returns (AuditOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/audit"
      body: "*"
    };
  }

  // 分页查询 oss 对象
  rpc Page (PageOssOss.Request) returns (PageOssOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/page"
      body: "*"
    };
  }

  // 七牛上传回调
  rpc QiniuUploadCallback (QiniuUploadCallbackOss.Request) returns (QiniuUploadCallbackOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/qiniu/upload-callback"
      body: "*"
    };
  }

  // 七牛增量审核回调
  rpc QiniuIncrementAuditCallback (QiniuIncrementAuditCallbackOss.Request) returns (QiniuIncrementAuditCallbackOss.Reply) {
    option (google.api.http) = {
      post: "/v1/oss/qiniu/increment-audit-callback"
      body: "*"
    };
  }

}

message GetUploadTokenOss {
  message Request {
    // 上传文件数量
    int32 num = 1;
  }
  message Reply {
    // 上传凭证列表
    repeated UploadToken upload_token = 1;
  }
}

message AuditOss {
  message Request {
    // 文件key
    string key = 1;
    // 审核状态
    bool status = 2;
    // 审核原因
    optional string reason = 3;
  }
  message Reply {}
}

message PageOssOss {
  message Request {
    common.PageRequest page = 1;
    OssQueryParams query = 2;
  }
  message Reply {
    common.PageReply page = 1;
    repeated Oss rows = 2;
  }
}

message QiniuUploadCallbackOss {
  message Request {
    string key = 1;
    string hash = 2;
    int64 size = 3;
    string bucket = 4;
    string name = 5;
    string mime_type = 6;
    int64 upload_by = 7;
    string upload_by_name = 8;
  }
  message Reply {}
}

message QiniuIncrementAuditCallbackOss {
  message Request {
    // 任务ID
    string id = 1;
    // 管道
    string pipeline = 2;
    // 状态码
    int32 code = 3;
    // 描述
    string desc = 4;
    // 请求ID
    string reqid = 5;
    // 输入 bucket
    string inputBucket = 6;
    // 输入 key
    string inputKey = 7;
    // 审核项列表
    repeated Item items = 8;
  }
  message Reply {}
}